### ISSUE TITLE
TypeError in training.

### ISSUE THREAD

**Issue by petroskey** [nianticlabs/monodepth2#1]
Thank you for sharing your great code. Your kind instruction in usage is a great help in setting the environment. The simple prediction test using your trained model worked successfully, but the we have some error in training. I would be appreciate any help from you. Thank you in advance.

python train.py --model_name stereo_model \
>   --frame_ids 0 --use_stereo --split eigen_full

Training model named:
   stereo_model
Models and tensorboard events files are saved to:
   /root/tmp
Training is using:
   cuda
Using split:
   eigen_full
There are 45200 training items and 1776 validation items

Training
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/workspace/trainer.py", line 186, in train
    self.run_epoch()
  File "/workspace/trainer.py", line 198, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/workspace/datasets/mono_dataset.py", line 174, in __getitem__
    self.brightness, self.contrast, self.saturation, self.hue)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 725, in get_params
    if brightness > 0:
TypeError: '>' not supported between instances of 'tuple' and 'int'

**Comment by mdfirman** [comment]
Thanks for the bug report! Could you please give the output of the following commands to show what version of pytorch and torchvision are you using:

```
python -c "import torch; print(torch.__version__)"
python -c "import torchvision; print(torchvision.__version__)"
```

I suspect this is to do with the slight pytorch/torchvision api change in how augmentation parameters are specified. I assumed the rule was that pytorch 1.0+ required tuples, while pytorch <1.0 required scalars; see https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L68.

But it seems from your bug that this isn't the case.

As a quick fix for your case, try changing [this line](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L68) to 

```
        # Need to specify augmentations differently in pytorch 1.0 compared with 0.4
        if False:
            self.brightness = (0.8, 1.2)
            self.contrast = (0.8, 1.2)
```

**Comment by mdfirman** [comment]
I've pushed a [fix](https://github.com/nianticlabs/monodepth2/commit/2e0c2613b0f4c9b353a6c080df4a99f8c4f0ac48) which should solve this problem. Could you please pull and see if you can run now?

Thanks

**Comment by petroskey** [comment]
Hi mdfirman,

Thank you for your kind response. Sorry for my late reply.
As I ran the fixed code you provided, it started training! 
Of course the trained model also gives a great depth map.
I really appreciate your kind help:)

Best regards.

Training model named:
   mono_model
Models and tensorboard events files are saved to:
   /root/tmp
Training is using:
   cuda
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items

Training
epoch   0 | batch      0 | examples/s:   2.3 | loss: 0.15459 | time elapsed: 00h00m13s | time left: 00h00m00s
epoch   0 | batch    250 | examples/s:  20.7 | loss: 0.14810 | time elapsed: 00h02m38s | time left: 11h39m58s
...

**Comment by mdfirman** [comment]
Thanks, glad it works.

I have opened an [issue](https://github.com/pytorch/vision/issues/905) with torchvision to address this upstream parameter inconsistency.
