### ISSUE TITLE
batch size changed and error occur

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#10]
Sorry to bother you again~
Due to memory limitation, I change the batch_size from 12 to 2. And then there's an error.
![image](https://user-images.githubusercontent.com/28101548/58748971-3ab5e880-84c3-11e9-92c4-ee264c12ae6b.png)
I didn't change other place.

**Comment by mdfirman** [comment]
Thanks for the issue. I'll push a fix tomorrow. For now, try changing `for j in range(4)` in `log()` to `for j in range(2)`.

**Comment by sunnyHelen** [comment]
Ok, thank you very much~

**Comment by boom4ever** [comment]
> Sorry to bother you again~
> Due to memory limitation, I change the batch_size from 12 to 2. And then there's an error.
> ![image](https://user-images.githubusercontent.com/28101548/58748971-3ab5e880-84c3-11e9-92c4-ee264c12ae6b.png)
> I didn't change other place.

Hi bro~Do you have this file calib_cam_to_cam.txt and calib_velo_to_cam.txt
Could you give me this file?
Thank you very much

**Comment by boom4ever** [comment]
> Thanks for the issue. I'll push a fix tomorrow. For now, try changing `for j in range(4)` in `log()` to `for j in range(2)`.

Hi bro~Do you have this file calib_cam_to_cam.txt and calib_velo_to_cam.txt
Could you give me this file?
Thank you very much

**Comment by mdfirman** [comment]
Pushed a fix here:
https://github.com/nianticlabs/monodepth2/commit/5cc5c85e70d4788ce33b3461e63f8a5b810f2776

Thanks again for the issue
