### ISSUE TITLE
How far can this model predict?

### ISSUE THREAD

**Issue by HarderThenHarder** [nianticlabs/monodepth2#100]
I use the model mono_640x192(which found here[*https://storage.googleapis.com/niantic-lon-static/research/monodepth2/mono_640x192.zip*]) to predict the depth. The tank's real distance is 250m(I calculate this distance in my unity), but I use the monoDepth2 model to get the disp_image and calculate the depth by (focal * baseline / disp ->718.856 * 0.54 / 22), the result is about 14m.
![BattleScene_1](https://user-images.githubusercontent.com/36854507/68109795-721f3a00-ff26-11e9-8a26-6859eda1ee6d.jpg)
![image](https://user-images.githubusercontent.com/36854507/68110103-3042c380-ff27-11e9-80c1-acd9c5f11b08.png)
There is a big difference between real distance & predict distance, so I wanna know if this model can predict the `right distance` even if the object is `250m` away from the camera. If so, I will check if there was something wrong in my code.<br>
Looking forward your response!<br>

**Comment by mdfirman** [comment]
Hi there, thanks for your interest in this repository!

In fact the maximum depth that our models can predict is 100m – this is set during training as `max_depth` parameter.

However, depth predictions beyond ~40m or so are tricky for the models, as they are trained from images with fairly small baselines.

Furthermore, your example image is synthetic and our models are trained on real data. This may means that your predictions are less accurate.

**Comment by HarderThenHarder** [comment]
Thanks a lot for your response!
