### ISSUE TITLE
How to get plasma image from KITTI Depth Ground Truth?

### ISSUE THREAD

**Issue by VictorCVision** [nianticlabs/monodepth2#101]
Hi, I would like to know how to convert a Depth Ground Truth into plasma image.

I mean, I have a RGB image:

![0000000005](https://user-images.githubusercontent.com/57361777/68133493-18971b00-fee6-11e9-903a-28b14d8686ac.png)

and its depth map (Ground Truth):

![0000000005](https://user-images.githubusercontent.com/57361777/68133534-2fd60880-fee6-11e9-8231-c0aa0a959aac.png)

How convert it to plasma image? How do you get those images? Like this:

![plasma](https://user-images.githubusercontent.com/57361777/68133826-b4288b80-fee6-11e9-889c-f1a9f4760042.png)

Because when I try the results are very bad due to the sparse depth map.

Beforehand thank you very much.

**Comment by mrharicot** [comment]
Hi,
The ground truth is sparse, so you have to either interpolate the values or ignore them when rendering.
If you want to interpolate here is what we used for monodepth v1:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L115

The colormap is also applied to the inverse depth.

**Comment by VictorCVision** [comment]
Where can I see an example? Because I'm getting errors to use it! I have tried to send the image as a PIL image and as a numpy array, but none works.

CODE

import numpy as np
import PIL.Image as pil

image_path = "/content/0000000010_depth.png"
input_image = pil.open(image_path)
gt = lin_interp(input_image.size, image)

**Error:**

QhullError: QH6019 qhull input error: can not scale last coordinate.  Input is cocircular
   or cospherical.   Use option 'Qz' to add a point at infinity.

**Comment by mrharicot** [comment]
This function doesn't work on images but takes an image shape and a vector of size Nx3 where the first two coordinates are the xy position of the points in the image and the last coordinate is the corresponding depth or inverse depth.
You can find an example use in the same file on monodepth:
https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L218

**Comment by VictorCVision** [comment]
Sorry, but I don't understand it yet. Image_shape is = (370, 1226), but a vector of Nx3? That's a matrix, isn't it? But 'x' has 370 values, 'y' has 1226 values and the last axis has 453620 (see image). It is not possible to generate a matrix with vectors of different sizes.

![n3](https://user-images.githubusercontent.com/57361777/68172842-a0a90f00-ff3e-11e9-98a8-b288a829c2e7.png)

**Comment by mrharicot** [comment]
I would suggest reading the documentation for the KITTI data.

The image is a single channel 16bit PNG. Pixels with value 0 are _invalid_, that means the ground truth depth is very sparse.
If you select the valid pixels only and associate them with their corresponding xy location (using np.where as well as np.meshgrid) then you can construct a Nx3 matrix holding the data you need to use the function.

**Comment by VictorCVision** [comment]
Yes, I get it, you're right. But it doesn't work yet.

*** CODE ***
import PIL.Image as Image

image_path = "/content/0000000010.png"
# Load image, convert to numpy array and divide by 256
depth_map = np.asarray(Image.open(image_path)) / 256

# Get location (xy) for valid pixeles
x, y = np.where(depth_map > 0)
# Get depth values for valid pixeles
d = depth_map[depth_map != 0]

# Generate an array Nx3
xyd = np.stack((x,y,d)).T

gt = lin_interp(depth_map.shape, xyd)

************************************************************************************

That's my result:

![gt](https://user-images.githubusercontent.com/57361777/68252234-947a8b80-ffea-11e9-8611-4f2444dfd82f.png)

**Comment by mrharicot** [comment]
You likely need to swap `x` and `y`

**Comment by VictorCVision** [comment]
Yes, It was necessary to swap them. I added plasma color map and that's my result...

![gt_plasma](https://user-images.githubusercontent.com/57361777/68253074-a78e5b00-ffec-11e9-9413-dd373138679f.png)

Thank you very much.

**Comment by compvision-developer** [comment]
> Yes, I get it, you're right. But it doesn't work yet.
> 
> *** CODE *** import PIL.Image as Image
> 
> image_path = "/content/0000000010.png" // Load image, convert to numpy array and divide by 256 depth_map = np.asarray(Image.open(image_path)) / 256
> 
> // Get location (xy) for valid pixeles x, y = np.where(depth_map > 0) // Get depth values for valid pixeles d = depth_map[depth_map != 0]
> 
> // Generate an array Nx3 xyd = np.stack((x,y,d)).T
> 
> gt = lin_interp(depth_map.shape, xyd)
> 
> import matplotlib.pyplot as plt plt.figure(figsize=(10, 10)) plt.imshow(depth_map) plt.title("Input", fontsize=22) plt.figure(figsize=(10, 10)) plt.imshow(gt) plt.title("Ground Truth", fontsize=22)
> 
> That's my result:
> 
> ![gt](https://user-images.githubusercontent.com/57361777/68252234-947a8b80-ffea-11e9-8611-4f2444dfd82f.png)

----------------------------------------------------------------------------------------------------------------------------------------
I don't know if I'm stupid in asking this question.

But, I'm unable to reason why in the https://github.com/nianticlabs/monodepth2/issues/101#issuecomment-550055146 written by [VictorCVision](https://github.com/VictorCVision), the np.array is divided by 256 to get the depth_map.

Also, what is the unit of depth (is it meter ?) in general for the projected groundtruth PNG files.
(Ex gt PNG file: KITTI_dataset/2011_09_26/2011_09_26_drive_0001_sync/proj_depth/groundtruth/image_02/0000000005.png)

@VictorCVision @mrharicot

**Comment by daniyar-niantic** [comment]
Hi @compvision-developer 

The format used for projected groundtruth PNG files follows KITTI dataset documentation:
https://github.com/joseph-zhong/KITTI-devkit#dataset-description

**Comment by compvision-developer** [comment]
Hi @daniyar-niantic 

Thank you very much for the help. 
Finally, now I'm confident about the correctness of `depth_map` values that I get by using @VictorCVision [***CODE***](https://github.com/nianticlabs/monodepth2/issues/101#issuecomment-550055146) .
 
But, I still want to know, what's the reason behind employing `256.0` value for groundtruth encoding/decoding (officially done by KITTI dataset creators) ?

@VictorCVision @mrharicot

**Comment by daniyar-niantic** [comment]
@compvision-developer Did you read the "Data format" section of the readme? https://github.com/joseph-zhong/KITTI-devkit#data-format
