### ISSUE TITLE
Did you provide the related code for predicting the depth of different data-sets?

### ISSUE THREAD

**Issue by TengFeiHan0** [nianticlabs/monodepth2#102]
I would like to test its performance on a new dataset, but I didn't find the related code.

**Comment by mrharicot** [comment]
Hi,
you can use [`test_simple.py`](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py) which outputs a colormapped inverse depth as well as the raw output from the network.

**Comment by TengFeiHan0** [comment]
it seems like the file only works on a single image very well. I am trying to test the whole dataset

**Comment by mdfirman** [comment]
`test_simple.py` can also be run on a folder of images if you point `--image_path` towards a folder. You can also very simply modify the for loop [here](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L109) to loop over whatever you want, e.g. if you have a text file with image names.
