### ISSUE TITLE
Combining 2D detection with disparity maps to learn object 3D geometry 

### ISSUE THREAD

**Issue by tareeqav** [nianticlabs/monodepth2#104]
@mrharicot Many thanks for your help so far!  I was hoping you would give some insight on the following:

![sample_detections](https://user-images.githubusercontent.com/53956168/68639925-221b1700-04d4-11ea-89cc-38c6f3cce564.gif)

During Tesla's autonomy day, they demo'd a system where the radar's outputs were used to train a network to infer the size of an object along the Z axis in the camera coordinate frame, i.e. 3D object detection.

Since the disparity map shown above can be converted to a depth map, where each pixel in the bounding box represents its distance from the camera's origin, then it is reasonable to assume that a network (perhaps a convolutional LSTM) could be trained to perform a similar thing using disparity instead of radar output.

As you're well familiar, the brightness of the object increases as the car moves closer to it, and as you can see above the size of the 2D bounding box also increases.

Thus the depth in the Z direction becomes a function of two things:
```
1. the change in the diagonal/size of the 2D bounding box

  1.1. More or less the object's size as the car approaches it because it can also be moving across from that car as it is stopped at a street light.  

  1.2. In that case the 2D box is mostly constant in size.

2. the change of the brightness of the pixels inside the 2D box.
```

Please feel free to ignore the question since it's not related to your project directly.  As I said previously I am not a researcher, just a self-learner trying to teach myself the techniques of autonomous driving.

**Comment by mrharicot** [comment]
Hi,
I have a couple questions:
1. How did you obtain the bounding box shown in this gif?
2. Is your goal to infer the size and/or distance of the object in the bounding box?
monodeph2 already predicts depth (up to scale) so you can simply get the distance of the object as some function of the depth distribution (mean, min, median, etc.) in the bounding box.
Did I miss something?

**Comment by tareeqav** [comment]
Many thanks for your reply! 

The goal is to infer the 3D size of the objects and draw cuboids around them to give each object an outline and localize it to the car.  This would be useful of course while passing objects on the freeway, etc.

The bounding boxes were generated using a pytorch [yolov3](https://github.com/ayooshkathuria/pytorch-yolo-v3) implementation

You did not miss anything! I think you actually outlined two problems with this approach:

1.  If I use a multi-step LSTM, then I can't use a single frame to perform this localization at inference time, so it is no different in that way to just using the disparity.
2.  There is no way for this approach to distinguish between an object moving in the same direction as the car vs. an object moving across from the car.  

Maybe the better solution is the bird's eye view of the disparity.  I'll investigate that a little more before coding the LSTM.  The fact that the vehicle is moving lends itself nicely to a time series approach, but might not be the correct way to do this task.  WIP!

**Comment by mrharicot** [comment]
I am still confused regarding your goal here.
What are your inputs and outputs?
