### ISSUE TITLE
Umeyama alignment and scaling for ATE-5 computation

### ISSUE THREAD

**Issue by hemangchawla** [nianticlabs/monodepth2#107]
Hello,

Why is the standard Umeyama's algorithm not used for aligning the 5-frame trajectories when computing the ATE-5 metric?

**Comment by mdfirman** [comment]
Thanks for the pointer! For the ATE5 metric we followed Zhou et al, who align using this method:
https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/pose_evaluation_utils.py#L7

Have you seen anyone else using Umeyama's algorithm?

Thanks

**Comment by hemangchawla** [comment]
TUM group's tools  (https://vision.in.tum.de/data/datasets/rgbd-dataset/tools)  also recommended by authors of KITT, use the Umeyama algorithm. The same TUM group also presented the paper http://jsturm.de/publications/data/sturm12iros.pdf which is referred by the authors of ORB SLAM in computation of ATE. So pretty much everyone in the geometry based SLAM community has been using the Umeyama algorithm for aligning trajectories while computation of the ATE.

**Comment by mdfirman** [comment]
Thanks for the pointer. We followed what previous methods in monocular depth estimation did, for a fair comparison with them. It would be good to align the different communities (SLAM and monocular depth estimation) on this point. Our models and code are all available so it should be pretty straightforward to re-evaluate our models using this different evaluation method.
