### ISSUE TITLE
Computing ATE-5 for ORB- SLAM keyframe based method

### ISSUE THREAD

**Issue by hemangchawla** [nianticlabs/monodepth2#108]
Hello,

How do you make the 5-frame snippets from the output of ORB-SLAM full in Table 4 of supplementary material?
ORB-SLAM outputs only the Keyframe poses (monocular case) and therefore the creation of snippets is unclear.
Also in this case of ATE-5 computation, do you use 5 Keyframes of ORB SLAM or Keyframes corresponding to 5 frames of the Ground Truth trajectory?

**Comment by mrharicot** [comment]
Hi,
We used the data provided by Tinghui on his SfMLearner github
https://github.com/tinghuiz/SfMLearner#pose
You can have a look at the pose evaluation code for more information:
https://github.com/nianticlabs/monodepth2/blob/master/evaluate_pose.py
