### ISSUE TITLE
Are the camera intrinsics used during inference?

### ISSUE THREAD

**Issue by tbrouns** [nianticlabs/monodepth2#109]
So the camera intrinsics are defined at:

https://github.com/nianticlabs/monodepth2/blob/bd03a9ec1305082e80199bc2753ef5adb252e405/datasets/kitti_dataset.py#L24-L27

Which are utilized during network training, but what about during pose inference? In other words, is `K` being used when running:

https://github.com/nianticlabs/monodepth2/blob/bd03a9ec1305082e80199bc2753ef5adb252e405/evaluate_pose.py

I suspect not, because changing `K` at inference time does not affect the trajectory error of the saved model.

**Comment by mrharicot** [comment]
Hi,
You're right! The intrinsics are not used at test time for pose estimation.
