### ISSUE TITLE
Key in depth_predition_example.ipynb

### ISSUE THREAD

**Issue by BenQLange** [nianticlabs/monodepth2#11]
Hi,
Cool stuff! 
They key model_name in the depth_prediction_example notebook is flipped. It should be "model_name = "mono_640x192".

**Comment by mdfirman** [comment]
Thanks for the bug report – I've pushed [a fix](https://github.com/nianticlabs/monodepth2/commit/85c2f98729ca99387538ce7f691258be08ed6c58) now.
