### ISSUE TITLE
A question regarding CUDA

### ISSUE THREAD

**Issue by neilyoung** [nianticlabs/monodepth2#111]
Hi,

I read the code makes use of GPUs. My End 2013 MPB Pro is supporting OpenGL and OpenCL natively according to the specs:

https://support.apple.com/en-gb/HT202823

The GPU is an Intel Iris. I'm now having a doubt, if I'm supposed to install CUDA support explicitly from 
here https://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html

Second question: Is CUDA used at all for image depth calculation or just required for training?

TIA

**Comment by mrharicot** [comment]
Hi,

Pytorch only support gpu with cuda.
cuda is only supported by nivida gpus, intel iris won't work in this case.

Our code should work without a GPU (and cuda) but we haven't tested it so some tweaks might be needed.

While it is possible to train on the CPU, it would be unbearably slow (at least 100X slower), especially on a 2013 laptop.

**Comment by neilyoung** [comment]
@mrharicot Thanks you very much for this info
