### ISSUE TITLE
.npy files

### ISSUE THREAD

**Issue by neilyoung** [nianticlabs/monodepth2#112]
Hi,

Is there some information available about the internal structure of the .npy files after conversion?

Sorry, if it is obvious. I didn't find.

**Comment by daniyar-niantic** [comment]
@neilyoung your questions are about numpy and python, please consult https://docs.scipy.org/doc/numpy/user/quickstart.html

**Comment by neilyoung** [comment]
@daniyar-niantic Right, I know, it is a numpy array. But what about the internal structure? How to interpret that programmatically? I suppose it is the binary depth information, but I don't know the structure of the array content. Am I wrong?

**Comment by daniyar-niantic** [comment]
The same function that creates numpy arrays also produces visualizations of the depth. Any ambiguities in the structure should be recoverable by following this block of code: https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L136
