### ISSUE TITLE
How to get quantitative results?

### ISSUE THREAD

**Issue by petroskey** [nianticlabs/monodepth2#114]
Hi, thank you for your great code!
How can I reproduce the quantitative results in Table 1 in your paper?
In the experiment, did you use the evaluation dataset or test dataset to get this result?
Thank you in advance.

**Comment by mrharicot** [comment]
Hi,
For quantitative results please read the [evaluation section](https://github.com/nianticlabs/monodepth2#-kitti-evaluation) in the readme as well as Section 4 in the [paper](https://arxiv.org/pdf/1806.01260.pdf).

**Comment by petroskey** [comment]
Thank you for your kind reply, @mrharicot. I understand it!
