### ISSUE TITLE
How to predict depth for a video?

### ISSUE THREAD

**Issue by leftecnu** [nianticlabs/monodepth2#115]
Hello,
I want to know how to predict depth for a video with the pretrained model, and how to get the depth of every pixel of every frame in the video.
Thanks.

**Comment by mrharicot** [comment]
Hi,
You need to extract every frame of the video using any tool you want ([ffmpeg](https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence) for instance).
You can then use [`test_simple.py`](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py) to evaluate the model on the entire directory of images.

**Comment by neilyoung** [comment]
Confirmed. Works. Put the frames into a separat folder and configure the path to the folder instead of a single file.  2 frames per second on my non-cuda machine
