### ISSUE TITLE
Structure of scaled_disp (not an issue)

### ISSUE THREAD

**Issue by neilyoung** [nianticlabs/monodepth2#117]
I'm referring to this line in `test_simple.py`.

`scaled_disp, _ = disp_to_depth(disp, 0.1, 100)
`

I need to serialise the result. While running the code on a different thread I'm catching an exception trying to make a JSON object from the returned `scaled_disp`:

`RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
`

A `detach` call did raise another exception:

`json.dumps(scaled_disp.cpu().detach().numpy())
`

`TypeError: Object of type 'ndarray' is not JSON serializable`

I found the solution on the web like so:

```
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)

json.dumps(scaled_disp.cpu().detach().numpy(), cls=NumpyEncoder)
```

This returned the following object (for the test_image):

[[[
  [192 floats],
  ...
]]]

The inner array of 192 floats repeated 640 times, which matches the `mono+stereo_640x192` model.

In your opinion: Is this the correct interpretation of the data returned by the depth estimation?

**Comment by mdfirman** [comment]
This is outside the scope of this project, but:

1. Yes, the data should be 192 x 640 array of floats.
2. json is probably not the best format for serialising numpy arrays. Try `np.save` instead

Thanks

**Comment by neilyoung** [comment]
Thanks a lot

**Comment by neilyoung** [comment]
@mdfirman PS: I agree on the JSON serialising, but a numpy serialising would force me to have numpy on the client side too... I would like to separate the depth calculation from the image provisioning. In between is a network.
