### ISSUE TITLE
Dataset and Training

### ISSUE THREAD

**Issue by manuelcasal** [nianticlabs/monodepth2#118]
Hello.

Could you explain how I have to do  to define a new dataset?. After doing that, how I have to do in order to train the system? 

I tried several ways and I am getting errors. 

Thanks in advance

**Comment by mrharicot** [comment]
Hi,
What errors are you getting?
You have to create a new dataset class that inherits from [mono_dataset](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py).
Then simply replace the kitti dataset with your new one in the trainer.
