### ISSUE TITLE
How to align input RGB image with output depth

### ISSUE THREAD

**Issue by 619862306** [nianticlabs/monodepth2#119]
![test_image](https://user-images.githubusercontent.com/49178624/70289507-e55ee900-180f-11ea-8d9e-bf9cb6e9684f.jpg)
![normal](https://user-images.githubusercontent.com/49178624/70289535-ff003080-180f-11ea-8e7e-3b17a4100eac.png)
As shown in the figure, the input and output do not match in size. How can they be aligned?

**Comment by mrharicot** [comment]
Hi,

Do you mean the object borders do not always match?

monodepth2 was trained on kitti, any test images differing from the training set won't always produce the expected result.
Moreover this is a self-supervised method so it tends to have fuzzier borders than supervised methods.

**Comment by neilyoung** [comment]
@619862306 OT, but how did you manage to produce a grayscale depth image and does that have an impact on the achievable "frame rate" (here: number of images processable per second).

**Comment by mrharicot** [comment]
@neilyoung you can achieve this simply by changing the colormap to `"gray"`
https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L140

**Comment by neilyoung** [comment]
@mrharicot Cool. Thanks for sharing.

**Comment by amyjim9907** [comment]
HI, 
how can I transform the output depth into the real distance
it's there any transform function? thx
