### ISSUE TITLE
Why "num_frames_to_predict_for" is set to 2 when pose_mode_type is "seperate_resnet"?

### ISSUE THREAD

**Issue by Tonsty** [nianticlabs/monodepth2#120]
"num_frames_to_predict_for" is set to 2 when pose_mode_type is "seperate_resnet",
but I found in the "predict_poses" function 
`                   

                    outputs[("cam_T_cam", 0, f_i)] = transformation_from_parameters(

                        axisangle[:, 0], translation[:, 0], invert=(f_i < 0))
`
axiangle[:, 0] and translation[: ,0] seem only to use the first frame's prediction,
and then either axiangle[:, 1] or translation[: ,1] is never used. 
So I wonder if  "num_frames_to_predict_for" should be set to 1 in this case.

**Comment by mrharicot** [comment]
Yes, I believe this was a bug, in practice it won’t matter as there are no gradients flowing through these outputs so it won’t have any impact on training.

**Comment by Tonsty** [comment]
@mrharicot , thanks for your reply.
yes, it does not affect the training process because no gradiets are propagated backward, but it does waste some space to store the extra weights.
