### ISSUE TITLE
Question about evaluating pose

### ISSUE THREAD

**Issue by hyBlue** [nianticlabs/monodepth2#124]
Hi, I have some questions about comparing gt pose and predicted pose.

In evaluate_pose.py,
```python
def dump_xyz(source_to_target_transformations):
    xyzs = []
    cam_to_world = np.eye(4)
    xyzs.append(cam_to_world[:3, 3])
    for source_to_target_transformation in source_to_target_transformations:
        cam_to_world = np.dot(cam_to_world, source_to_target_transformation)
        xyzs.append(cam_to_world[:3, 3])
    return xyzs
```
in this function, I wonder why you use
`np.dot(cam_to_world, surce_to_target_transformation)`
instead of
`np.dot(source_to_target_transformation, cam_to_world)`

I think what we have to compute is the pose of np.eye(4) after transformation, so the equation should be T * xyz  and the code be `np.dot(source_to_target_transformation, cam_to_world)`, but isn't it?  

Second question is, 
while loading the GT pose data,
```python
for i in range(1, len(gt_global_poses)):
        gt_local_poses.append(
            np.linalg.inv(np.dot(np.linalg.inv(gt_global_poses[i - 1]), gt_global_poses[i])))
```
I wonder why you use
`np.dot(np.linalg.inv(gt_global_poses[i - 1]), gt_global_poses[i])`
instead of
`np.dot(gt_global_poses[i], np.linalg.inv(gt_global_poses[i - 1]))`
The predicted pose of your network is the relative transformation
from frame i-1 to i, then I think that this transformation should be the T of equation, 
P_t = T * P_t-1
then, relative motion T shoud be `np.dot(gt_global_poses[i], np.linalg.inv(gt_global_poses[i - 1]))`, isn't it?
I want to figure out my mistakes.
Thanks

**Comment by daniyar-niantic** [comment]
Both of your questions are about matrix order conventions.

Depending what your transformations mean the ordering might change. E.g. what is a transformation from source to target, or from target to source; what is being transformed, the camera pose or 3D points?

As long as everything is consistent, it shouldn't affect results.
