### ISSUE TITLE
Fine tuning - Pose estimation

### ISSUE THREAD

**Issue by drake666** [nianticlabs/monodepth2#127]
I've precedently asked a question about fine tuning monodepth2 on a different dataset (NuScenes) and your answer was really useful. However, I've just realized that I needed a small clarification about the fine-tuning of the pose estimation block (pose encoder and pose decoder). 

I'm using the "separate_resnet" pose model type and I've noticed that, in the Trainer class, both pose encoder and pose decoder parameters are fed to the optimizer if we're doing monocular vision. 

Does it means that the pose encoder and pose decoder will be correctly fine tuned on my chosen dataset and the pose ground truth is not needed? The reprojection_losses and the identity_reprojection_losses will be enough to correctly adjust the weight of both models?

Thanks again for your time!

**Comment by mrharicot** [comment]
Yes, the optimizer is created with the parameters from all the models so everything will be optimized.
