### ISSUE TITLE
Clarification about Pose angle and translation

### ISSUE THREAD

**Issue by ezorfa** [nianticlabs/monodepth2#128]
Hi @mrharicot !

One value of the axis angle is :
`tensor([[[[-1.0324e-03, -1.3413e-04,  5.2381e-04]],

         [[-4.1887e-04, -2.8635e-04,  1.9561e-04]]],

        [[[-1.0355e-03, -4.7055e-05,  4.0181e-04]],

         [[-8.7016e-04, -1.6312e-04,  7.2282e-05]]],

        [[[-1.1224e-03,  8.9183e-05,  6.3316e-04]],

         [[-5.2438e-04, -3.2808e-04,  2.2116e-04]]],

        [[[-1.0126e-03,  1.0477e-04,  3.9709e-04]],

         [[-5.4035e-04, -2.7966e-04,  1.6084e-05]]]], device='cuda:0',
       grad_fn=<SliceBackward>) ` **axis angle**

My question is, Why does it predict two values of axis angles for outputs[('axisangle', 0, -1)] ?

Thankyou!

**Comment by mrharicot** [comment]
Hi,
I believe this is an indexing bug where we predict two poses instead of a single one, but which doesn't affect accuracy as no gradients flow back through it.

**Comment by hemangchawla** [comment]
@mrharicot So the index 0 is the correct value to be used? We drop index 1? If we change the code to output 12x1x1x3 axis angle and translations, would it affect anything?
