### ISSUE TITLE
how to train without depth gt

### ISSUE THREAD

**Issue by Songminkee** [nianticlabs/monodepth2#13]
I want to train using data, but I want to do it without depth ground truth.

how can i possible?

**Comment by mdfirman** [comment]
Hi, thanks for the question. Are you training with KITTI?

Depth ground truth isn't needed for training on KITTI; it is only used for monitoring the training progress in the  [`compute_depth_losses`](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L494) function.

If you don't have lidar ground truth files available for the KITTI dataset, the code _should_ automatically [detect this](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L88), and proceed to [not load depth](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L187).

Does this help?

**Comment by Songminkee** [comment]
thanks for your answer
