### ISSUE TITLE
A question regarding training with ground-truth

### ISSUE THREAD

**Issue by neilyoung** [nianticlabs/monodepth2#131]
I am able to perform my own training from stereo without providing the ground-truth information. I’ve read on a previous issue (https://github.com/nianticlabs/monodepth2/issues/13) that providing the ground-truth allows to measure the error, but does it help the training or does it just give an indication about the accuracy? Can a depthmap computed from stereo disparity (StereoBM) be used for this or is it too inaccurate?

**Comment by mrharicot** [comment]
The depth isn't used as a signal for training, only as a measure of accuracy.
A stereo disparity could be a reasonably good proxy for measuring accuracy, as long as you keep in mind that it is imperfect.
If you want a better proxy I would recommend using one of the SOTA deep stereo methods.

**Comment by neilyoung** [comment]
@mrharicot Thanks for the answer. So basically you are saying, that having a ground-truth aside would help to estimate the error of the training, but would not have any impact on the training results at all. Did I get that right?

Thank you

**Comment by mrharicot** [comment]
Yes. You obviously can also use the ground truth as a training signal, but you would need to implement this yourself.
