### ISSUE TITLE
how to split custom data?

### ISSUE THREAD

**Issue by mvenka24** [nianticlabs/monodepth2#133]
Hi,

it is recommend to do eigen split for stereo images.

- for custom data, is it enough to remove still frames, shuffle and split sequence between train, test and val? or is there a script to do eigen split?

- for stereo training how to select left and right frames?

- we feed 3 consecutive frames for model. how we need to keep all 3 frames in train_files.txt or just one middle frame? 

- for Monocular + stereo training, I created separated class, changed camera intrinsic, random shuffle, split. but model collapses in first epoch ( loss starts at 0.00001 in first epoch and goes to -0.00000 in second epoch). am I missing something?
 

Thnaks,
Madhu.

**Comment by alwynmathew** [comment]
> for custom data, is it enough to remove still frames, shuffle and split sequence between train, test and val? or is there a script to do eigen split?

Monocular training: You should remove still frames as there isn't ego-motion between the consecutive frame. Training with video frames with no ego motions doesn't help supervision or may severely affect the training.
Stereo training: You don't need to remove still images as stereo cameras itself give ego from one view to another.
Then split and shuffle the frames, you're done.

> for stereo training how to select left and right frames?

If you are using exact same cameras in your stereo setup and if these stereo cameras are rectified, writing a dataloader will be pretty easy as both have the same intrinsic and the extrinsic only change in direction(left to right and righ to left). 

monodepth has a pretty clean [dataloader](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py)
```
file_path = 2011_10_03/2011_10_03_drive_0034_sync 1757 r
folder, frame_index, side = file_path.split()
```

> we feed 3 consecutive frames for model. how we need to keep all 3 frames in train_files.txt or just one middle frame?

Only the middle frame will be in train_files.txt

> for Monocular + stereo training, I created separated class, changed camera intrinsic, random shuffle, split. but model collapses in first epoch ( loss starts at 0.00001 in first epoch and goes to -0.00000 in second epoch). am I missing something?

Loss starts at 0.00001? That doesn't look good. You have to go through your code again.
