### ISSUE TITLE
What's the evaluation data used in Monodepth2 paper

### ISSUE THREAD

**Issue by ruili3** [nianticlabs/monodepth2#137]
In paper _Digging Into Self-Supervised Monocular Depth Estimation_ , the testing result is said to be run on **KITTI 2015**. I wonder what exactly is test data **KITTI 2015**, is that the **raw data containing 697 testing images** (--eval_split="eigen" in the code) or the **refined depth data on new KITTI depth benchmark** containing 652 testing images (--eval_split="eigen_benchmark" in the code)? I want to make my experiment results to be consistent with the original work.

P.S. I download the **refined depth data on new KITTI depth benchmark** and run your evaluation code with the corresponding GT, the results seems very different from that of raw dataset. 

Thanks a lot!

**Comment by mrharicot** [comment]
Hi,

We report our main results on the raw KITTI data on 697 images chosen by Eigen, hence the split name.
The KITTI benchmark results correspond to the refined ground truth.
We describe the splits in the readme:
https://github.com/nianticlabs/monodepth2#-kitti-evaluation

I hope this helps!

**Comment by ruili3** [comment]
Thank you a lot! It addresses my concerns!

Clément Godard <notifications@github.com> 于2020年2月3日周一 上午4:02写道：
