### ISSUE TITLE
Format of input

### ISSUE THREAD

**Issue by brooda** [nianticlabs/monodepth2#139]
Hi, I am trying to perform RGB->D conversion using my dataset. 

I have for every frame: 
1. RGB images in png format
2. Depth maps in png format. Those are grayscale images. Depth of a pixel is encoded in color (0-255)cm

Currently I am training the model, but on test I am getting nonsense results, so I want to check, where I am doing something wrong. 

Is there something wrong in format, that I am using?

Also, question about output, network is outputting:
![image](https://user-images.githubusercontent.com/13292836/73841534-275dd880-481b-11ea-9328-c6aee05fd34c.png)

How should colors be interpreted?

**Comment by daniyar-niantic** [comment]
Monodepth2 is trained with self-supervision from stereo pairs, or video stream under certain conditions. It is not designed to train from supervised data (RGB and Depth pairs), please consider other methods.

**Comment by brooda** [comment]
Thank you. Can you suggest any solution, that would fit my use-case?

**Comment by mrharicot** [comment]
Hi,
You are looking for a supervised method, here's a recent one.
https://github.com/ialhashim/DenseDepth
