### ISSUE TITLE
 png but added a jpg extension

### ISSUE THREAD

**Issue by brucemuller** [nianticlabs/monodepth2#14]
Hi

Just to let you know that test_simple saved a png but added a jpg extension which might confuse for the initial test example. Great work!

Bruce

**Comment by mdfirman** [comment]
Hi, thanks for the interesting issue! 

This is interesting – when I inspect the saved file that I get (on OSX) it seems to be a jpg:
```
$ file assets/*.jpg
assets/test_image.jpg:      JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=5, orientation=upper-left, xresolution=74, yresolution=82, resolutionunit=2], baseline, precision 8, 638x235, frames 3
assets/test_image_disp.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 100x100, segment length 16, baseline, precision 8, 638x235, frames 3
```
What platform are you using, and what tool are you using to inspect the saved file with?

Thanks

**Comment by brucemuller247** [comment]
Hi ;-) Hmmmm that's weird. I'm using Ubuntu 16.04 and I was just viewing files in the GUI file explorer...

**Comment by mdfirman** [comment]
Ok, thanks. Can you provide a screenshot or similar? And are you using the provided `test_image.jpg` or your own? (Not that I think it would make much difference). It would also be useful to know your matplotlib version; I'm on 2.2.3 on Ubuntu and 2.2.2 on OSX. Thanks

**Comment by NaveenSehgal** [comment]
I'm using CentOS and get the same error as @mdfirman . 

![error](https://user-images.githubusercontent.com/23645582/59200757-f1baff80-8b66-11e9-8eb6-2b0a57c43c9e.png)

The "starts with 0x89 0x50" indicates that it's actually a .png file. GNU can open the image regardless but my default system viewer isn't able to. When I change .jpg -> .png in test_simple.py everything works fine for me.

**Comment by brucemuller** [comment]
@mdfirman no problem, the screen it similar to that provided by @NaveenSehgal, thanks!

I am using the provided test image. Matplotlib = 2.0.2 on Ubuntu 16.04. I'm using conda but it won't let me update matplotlib any further

**Comment by mdfirman** [comment]
Thanks. I wonder if there is a simpler fix than this, but I've pushed a new branch which saves the images using PIL rather than plt.
https://github.com/nianticlabs/monodepth2/tree/pil_image_saving

Could you please give this a go and see if you have the same problem? Thanks

**Comment by brucemuller** [comment]
That fixed it :) thanks

By the way is anyone from your group going to CVPR next week? If so it would be great to say hi! I'm travelling from University of York. I'm interested in doing homography estimation with a new road scene dataset my supervisor has links to but I'm really interested in your work on here in the longer term :)

**Comment by daniyar-niantic** [comment]
@brucemuller Gabriel Brostow and I are going to CVPR, we should be able to talk there. Are you by any chance supervised by Will Smith at York?

**Comment by mdfirman** [comment]
I've merged the `pil_image_saving` into master now, so all should be well now! Thanks for the interesting issue.

**Comment by brucemuller** [comment]
@daniyar-niantic hi! Yes Will is my supervisor! It would be great to meet you both!

**Comment by daniyar-niantic** [comment]
@brucemuller Hey. CVPR this time was very big, so we couldn't chat there. I was going through my notes and I've just noticed that you were at BMVA two weeks ago. We should've chatted there!

**Comment by brucemuller** [comment]
@daniyar-niantic  Hi! I know, it was my first conference in general and somewhat overwhelming! Maybe they can split the conference in half!? And yes we should have chatted at the technical meeting, I particularly enjoyed hearing what Niantic have been doing. That day was also quite intense  and I've been meaning to go over my notes (now I'm past a paper deadline). I was wondering, would it be possible to get both your presentation slides for that day? I'd love to go back over the talk.

My research will be progressing soon into relative pose estimation from road scenes (we have access to a huge private collaborator dataset on driving footage from a calibrated multi camera set up). I'm initially intending to assume road planarity and investigate a deep homographic estimation. But I'm intending to use your monodepth2 as a base of operations and also experiment with the depth estimation. I was wondering, is your current set up for depth estimation fairly reliant on training on heavily overlapping road track images? Because I would like to train on image pairs which don't assume a strong overlap.

It would be great to keep in touch and potentially collaborate in the future. I've connected with you and Michael on LinkedIn and my email is (brm512@york.ac.uk) in case it's easier to communicate on those channels :)
