### ISSUE TITLE
How to train with Custom Dataset (weird results)

### ISSUE THREAD

**Issue by ArmanAstudUc3m** [nianticlabs/monodepth2#140]
Hi,

First of all, thank you for such an amazing CNN.

I'm trying to train the net with an especial KITTI split, comparing the obtaining depth images and the Kitti depth image (similar to the results provided from this CNN).

**Dataset Struct**:
Kitti/
-----sp_split/
--------------right_color/
----------------------------00000.JPEG
----------------------------XXXX.JPEG
-------------depth/
----------------------------00000.PNG
----------------------------XXXX.PNG

If I run a **pre-trained model**:
![Screenshot from 2020-02-06 08-23-59](https://user-images.githubusercontent.com/56833420/73916121-12d21c80-48bd-11ea-930f-fca268cc5226.png)

But if I run my **new model**
![Screenshot from 2020-02-06 08-36-53](https://user-images.githubusercontent.com/56833420/73916134-1bc2ee00-48bd-11ea-9b3d-1c2de9f2ee2c.png)

**This is the Class for the Dataset:**
![Screenshot from 2020-02-06 08-46-37](https://user-images.githubusercontent.com/56833420/73916191-3f863400-48bd-11ea-9619-9621e08cd061.png)

**This is how I run the trainer script:**

CUDA_VISIBLE_DEVICES=1 python train.py --model_name Kitti_sp --data_path=/data/kitti/sp_split/right_color/ --height=1024 --width=1024 --dataset=Kitti_sp --split=Kitti_sp

**Terminal_response:**
Training model named:
   Kitti_sp
Models and tensorboard events files are saved to:
   /home/user/tmp
Training is using:
   cuda
Using split:
   Kitti_sp
There are 2205 training items and 1360 validation items
Training

**Comment by mrharicot** [comment]
Hi,
I am confused by the `for i in range(8):` loop in your code. What is the goal here?
Otherwise I don't see anything obvious in your dataloader.

**Comment by mdfirman** [comment]
@ArmanAstudUc3m – can I check, is the aim here to _supervise_ with the depths you are loading? Or are you training self-supervised, and just loading in ground truth depths too for comparison?

Thanks
