### ISSUE TITLE
Pose Evaluation for 3-frame snippet.

### ISSUE THREAD

**Issue by ezorfa** [nianticlabs/monodepth2#141]
Hi @mrharicot !

How can I adapt your script evaluate_pose.py to work with 3-frame snippet? 

I tried with using frame_ids as `[0,1,2]` with `drop_last = True`. However, there is this error:

`Traceback (most recent call last):
  File "evaluate_pose.py", line 134, in <module>
    evaluate(options.parse())
  File "evaluate_pose.py", line 123, in evaluate
    ates.append(compute_ate(gt_local_xyzs, local_xyzs))
  File "evaluate_pose.py", line 43, in compute_ate
    scale = np.sum(gtruth_xyz * pred_xyz) / np.sum(pred_xyz ** 2)
ValueError: operands could not be broadcast together with shapes (5,3) (4,3)`

Thankyou!

**Comment by mrharicot** [comment]
Hi,
You can change the track length here:
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/evaluate_pose.py#L118

**Comment by ezorfa** [comment]
Hi @mrharicot !
Could you please elaborate on this? For 3-frame snippet, to what value should i change the track lenght to?

Thankyou!

**Comment by ezorfa** [comment]
@mrharicot  I wanted to train the pose network with 3 frame inputs. Which means I also need to evaluate on 3 frames. I was unable to make it to work. I think I dont have to change the track_length.

**Comment by mrharicot** [comment]
I see, then you need to pass the `--pose_model_input all` when training.

**Comment by ezorfa** [comment]
@mrharicot I have trained it successfully. Now, I am trying to evaluate, which is where I get the above error.

**Comment by linClubs** [comment]
ValueError: operands could not be broadcast together with shapes (5,3) (4,3)

Hello, how did you solve this problem?
