### ISSUE TITLE
Regarding Depth Evaluation

### ISSUE THREAD

**Issue by ezorfa** [nianticlabs/monodepth2#142]
Hi @mrharicot !

Could you please let me know if the method for depth evaluation of yours (evaluate_depth.py) and of SfMLearner by TZhou's  is same? Because when I tested with TZhou's script, my results were pretty bad.

Thankyou!

**Comment by mrharicot** [comment]
Hi,
As far as I know the evaluation from SfMLearner was based on monodepth 1.
I have compared our evaluation with theirs and found the results to be very very close so I am surprised.
What model are you evaluating?
