### ISSUE TITLE
Question about auto-masking approach

### ISSUE THREAD

**Issue by abeyang00** [nianticlabs/monodepth2#144]
This may sound silly but

Why does performance suffer when 'camera is stationary or there is object motion in the scene'?

I get that the dynamic object changes too quickly so inferring depth for dynamic objects can be difficult but why for static scenes? 

Thanks in advance

**Comment by mdfirman** [comment]
Hi thanks for your interest!

Most forms of 3D reconstruction (including monodepth) operate under a 'static scene moving camera' assumption, which is broken when either (a) the camera doesn't move, or (b) objects in the scene move.

(a) Performance suffers when the camera doesn't move as any depth prediction whatsoever will cause perfect reprojection, so the system can end up learning bad depths – often depths of infinity, as seen in sky regions.

(b) When objects in the scene move, perfect reprojection can only be achieved by predicting the wrong depth of objects.

Does this help at all?

**Comment by abeyang00** [comment]
Thank you for the answer.

In addition can you think of it as

(a) Because the scene doesn't move, the change in frames will be zero and there won't be any updates in backpropagation?
(b) And unless you know the speed for those dynamic objects, correspondence will have no meaning?

Thank you!

**Comment by abeyang00** [comment]
Thank you for the quick reply.

I have one more question.

(a) why will any depth prediction can cause a perfect reprojection??

**Comment by mdfirman** [comment]
Because if the camera doesn't move (or only undergoes rotation) there will be no translational baseline. Translational motion is required to learn about the 3D shape of an object/scene using this approach.

Mathematically: When there is no motion the 3D geometry means that the gradient of the reconstructed image with respect to the depth map will be zero.
