### ISSUE TITLE
about test video

### ISSUE THREAD

**Issue by Leon1995-ai** [nianticlabs/monodepth2#145]
How do I estimate the pixel depth in the video stream in real time from my own camera?
thanks

**Comment by mdfirman** [comment]
Hi there, what you are asking is slightly outside the scope of this project.

However, I would recommend looking at this demo: 
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html
as a way to load the stream from a webcam into python in real time. 

You should then be able to combine this with some of the code from `test_simple.py` to make a real-time monodepth predictor. 

Good luck!
