### ISSUE TITLE
How can I download KITTI dataset in China?

### ISSUE THREAD

**Issue by wbzhang233** [nianticlabs/monodepth2#146]
### **中文**
Kitti数据集我倒是有，不过这个repo下载的会根据kitti_archives_to_download.txt这个文本下载，然后有很多splits文本用于抽取kitti数据集图片，国内网速超慢，上github求助也是迫不得已。百度许久没找到帖子，有没有国人出来指点一下？

**Comment by mrharicot** [comment]
Hi,
I'm sorry to hear it's difficult to download KITTI in China, unfortunately I don't know of any other way to obtain it.
Maybe someone at your university has a local copy?
I am going to close the issue for now as it has been a week, but please let us know if you find a way!

**Comment by nijiushi** [comment]
Excuse me, do you have the ground truth of kitti11?
