### ISSUE TITLE
Multi-GPU Training and Training Hangs

### ISSUE THREAD

**Issue by danxuhk** [nianticlabs/monodepth2#147]
Dear authors, I have met two different issues:
(i) I used Pytorch 1.0.1 and Python 3.6.6. When I run the training script, it hangs there as shown below:
![image](https://user-images.githubusercontent.com/8382926/74976337-72cdd480-5420-11ea-8381-7a97bb23c328.png). Do you know why it happens?
(ii) I also change the OrderedDict to ModuleDict in order to enable the multi-gpu training. Is it correct to do that?

Thanks.

**Comment by mdfirman** [comment]
Hello, thanks for your interest here.

Does the code hang after you have made the changes you describe?  Or using the original unmodified code?

In general, we don't support multi-GPU training – all our experiments were run on a single GPU. I would recommend asking in a pytorch forum for support in converting the code to multiGPU, thanks!

**Comment by mdfirman** [comment]
See also https://github.com/nianticlabs/monodepth2/issues/5 for tips for multiGPU support

**Comment by mrharicot** [comment]
@danxuhk Have you had any luck?

**Comment by danxuhk** [comment]
Yes, I have modified it successfully for the multi-gpu training. Thanks a lot.

**Comment by mrharicot** [comment]
Great! Could you share the modifications so that others can reproduce it?

**Comment by cswwp** [comment]
> Yes, I have modified it successfully for the multi-gpu training. Thanks a lot.

Do you mind share your modify method? @danxuhk
