### ISSUE TITLE
How to load modules in C++ via torchscript?

### ISSUE THREAD

**Issue by hassaanhashmi** [nianticlabs/monodepth2#149]
Hi,

I am trying to convert the modules to scripted format to load them via libtorch (using torch::jit::load()). So far I have been unsuccessful.

**Comment by mdfirman** [comment]
Hi, thanks for your interest! Your question is well outside the scope of this repo, but I will leave this issue open for a week or so to see if anyone else has any ideas. You might be better off asking in a specific torchscript forum.

Thanks

**Comment by hassaanhashmi** [comment]
Thank you for the reply and keeping the issue open.

**Comment by hassaanhashmi** [comment]
Found an implementation here: [ZHEQIUSHUI/monodepth2-cpp](https://github.com/ZHEQIUSHUI/monodepth2-cpp)

**Comment by yan99033** [comment]
Feel free to check out [my implementation](https://github.com/yan99033/MiDaS-cpp) on how to load a torchscript model and run inference in C++. My project uses MiDaS as the depth prediction model, but with proper modification you should be able to swap the model and run depth prediction.
