### ISSUE TITLE
Training with rectified stereo pairs

### ISSUE THREAD

**Issue by msceme** [nianticlabs/monodepth2#150]
What is the use of K matrix when training only with stereo rectified images?

**Comment by mdfirman** [comment]
In our implementation we treat stereo training as a special case of mono training, where we know poses in advance. So when training on stereo we still throw the predictions out into a 3D point cloud, then reproject this into the other camera to look up corresponding color values.

In practice you could of course re-implement this step to bypass the use of K, instead using predicted disparity to look up pixels along scanlines, much like the monodepth1 paper did.
