### ISSUE TITLE
Disparity ramps

### ISSUE THREAD

**Issue by msceme** [nianticlabs/monodepth2#151]
In monodepth1, disparity ramps can be seen when training on stereo pairs. Why disparity ramps are not seen with monodepth2 if only training with stereo images?

**Comment by mrharicot** [comment]
Hi,
I believe two main things explain the lack of ramps in monodepth2 S:
- The flip augmentation means that the network cannot get used to the location of occlusion edges, they will be on the left or on the right of occluders with a 50% chance. In monodepth1 they are always located on the left.
- Monodepth2 produces generally sharper predictions and tends to favor sharp discontinuities.

However the stereo model, while lacking ramps, suffers from edge fattening: thin objects appear larger and occlusion edges do not always line up with the image edges.

I hope this helps!

**Comment by msceme** [comment]
Thanks for the explaination. Flip augmenation was also applied in monodepth1, but still that causes ramps.

**Comment by mrharicot** [comment]
Hi,
In mdp1 the flip augmentation also swapped both images, resulting in the disparities always moving in the same direction as the original stereo pair.
In mdp2, we can get either the left or the right image as input, and they can also be flipped, meaning that there isn't a "dominant" direction as it was the case in mdp1, hence the network cannot get used to a specific edge being the occlusion edge.

**Comment by msceme** [comment]
Thanlks for reply. Does padding also give rise to these effecst?
Because in this https://github.com/nianticlabs/monodepth2/issues/20#issuecomment-503789112 you have mentioned that border padding avoids zero disparities on the edge of the images.

**Comment by mrharicot** [comment]
The grid_sample padding mode border only affects the behavior of the network on edge of the image. I believe both the use of flipping and border mode contribute to the lack of disparity ramp on the edge of the image.
