### ISSUE TITLE
do I have to use velodyne_points/data/{:010d}.bin? 

### ISSUE THREAD

**Issue by caikw0602** [nianticlabs/monodepth2#152]
Thank you for your sharing codes. It is really greate. I wanna train my own sequence images data by using mono2. Now, I am learning this code. Would you like to tell me that do I have to use the velodyne_points/data/{:010d}.bin"velodyne_points/data/{:010d}.bin" please? I just wanna get my depth information from my own video data. Thanks a lot. Look forward to your reply.

**Comment by msceme** [comment]
I think it is just for validation

**Comment by mrharicot** [comment]
Hi,
The depth data is only used as a metric when training, it is not needed.
You can simply return False in the function `check_depth`
