### ISSUE TITLE
Contradiction between pytorch 0.4.1 and Tesla T4

### ISSUE THREAD

**Issue by jeanttz** [nianticlabs/monodepth2#153]
Tesla only supports cuda10, while pytorch 0.4.1 does not have a version of cuda10。Can you provide a solution？thank you.

**Comment by mrharicot** [comment]
Hi,
I would recommend trying with more recent versions of pytorch.
Let us know if it works!

**Comment by daniyar-niantic** [comment]
@jeanttz have you resolved the issue? Please share your findings here.
