### ISSUE TITLE
Error in the val split for benchmark data

### ISSUE THREAD

**Issue by anupamsobti** [nianticlabs/monodepth2#154]
Please refer to this issue: https://github.com/intel-isl/MiDaS/issues/18#issuecomment-593947184

It seems some images are missing in the benchmark val split. 
The corrected list is attached.
[val_files.txt](https://github.com/nianticlabs/monodepth2/files/4284941/val_files.txt)

**Comment by daniyar-niantic** [comment]
@mrharicot do you know if there was a process to remove some images from the val split?

**Comment by mrharicot** [comment]
I believe the difference comes from the fact that I did not include the raw sequences of the "person" category:
http://www.cvlibs.net/datasets/kitti/raw_data.php?type=person
