### ISSUE TITLE
Train my custom data

### ISSUE THREAD

**Issue by cswwp** [nianticlabs/monodepth2#156]
If i train my custom data, whether i need to update my camera matrix to replace K  kittidataset?

**Comment by mdfirman** [comment]
Hi – yes, this would be needed. If you know the camera that the data was captured with you might be able to approximate K based on camera spec sheets, which might be good enough.

**Comment by daniyar-niantic** [comment]
Please see other issues, for example:
https://github.com/nianticlabs/monodepth2/issues/26
https://github.com/nianticlabs/monodepth2/issues/140
