### ISSUE TITLE
distance units and distance measurement

### ISSUE THREAD

**Issue by ma-siddiqui** [nianticlabs/monodepth2#159]
Hi,

Kindly explain how can I get the pixel distance in meters using depth estimation. In my case, camera is fixed at certain angle and capturing images. I have camera position  (x, y). Using your approach, how can I get the location of object and distance to camera.

Thanks,
Muhammad Ajmal Siddiqui

**Comment by daniyar-niantic** [comment]
Please see other issues on the topic, for example:
https://github.com/nianticlabs/monodepth2/issues/96
https://github.com/nianticlabs/monodepth2/issues/94
https://github.com/nianticlabs/monodepth2/issues/91
https://github.com/nianticlabs/monodepth2/issues/66
