### ISSUE TITLE
Scaled translation in PoseCNN

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#16]
Why do you scale translation just for `posecnn` but not for `shared` or `separate`? 

https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/trainer.py#L372

**Comment by mdfirman** [comment]
Thanks for the question. This scaling is done to replicate the strong baseline used for depth+pose estimation in the _Learning Depth from Monocular Videos using Direct Methods_ baseline work. If you remove that scaling, you will have something very similar to the Zhou et al. paper.

We never tried using this inverse depth scaling with our own networks; if you get any results from running this, please do share them here.

Thanks
