### ISSUE TITLE
monodepth2 prediction in windows 10

### ISSUE THREAD

**Issue by fabien-w** [nianticlabs/monodepth2#163]
Any chance that monodepth2 (only prediction) works in Windows 10 ? i usually run deep learning models on windows 10 with a RTX gpu and keras.

**Comment by fabien-w** [comment]
for those who want to know, the prediction works in windows 10.

**Comment by ebrarsahin** [comment]
Is there any differencies about commands ?

**Comment by fabien-w** [comment]
No there are no differencies

Em seg., 29 de mar. de 2021 às 11:07, ebrarsahin ***@***.***>
escreveu:
