### ISSUE TITLE
Training with Mono camera video

### ISSUE THREAD

**Issue by sujayj78** [nianticlabs/monodepth2#165]
Hi, thanks for the amazing work @mrharicot and team!
I have gone through your paper and repo but I haven't been able to understand how to trian a monocular video exactly. Could you kindly guide me through this procedure. Also, with the intrinsics of the camera used in the video can I obtain real depth from the disparity maps created after training?
First time trying out a self-supervised approach so pardon me if I'm sounding silly. 
Looking forward to your reply!
Thanks!

**Comment by msceme** [comment]
Are you having problem with dataloader to train your own dataset?

**Comment by sujayj78** [comment]
I have managed to inherit and modify the MonoDataset class for training on the monocular camera video. I went through the past issues and realised the way frames have to be split. So I have understood the training procedure, but I want to know how can I determine the true distance of the disparity map which is predicted?

**Comment by msceme** [comment]
You have to inverse the disparity to get depth i.e depyh=1/disparity and then scale the depth map to get true distance.

**Comment by msceme** [comment]
From my understanding, there is no direct way to get absolute distance for video based methods.

**Comment by sujayj78** [comment]
> You have to inverse the disparity to get depth i.e depyh=1/disparity and then scale the depth map to get true distance.

Yeah, but this wouldn't be the true distance. I'm not sure if this makes sense, correct me if I'm wrong but can we apply a formula similar to the stereo vision formula of Dist = B*f/disp?
The issue will be that we don't have a baseline value, but if we could calibrate for a known object distance value then could we find the baseline with the following expression B = Dist*disp/f?
Excuse me if it sounds crazy, just shooting in the dark

**Comment by msceme** [comment]
> > You have to inverse the disparity to get depth i.e depyh=1/disparity and then scale the depth map to get true distance.
> 
> Yeah, but this wouldn't be the true distance. I'm not sure if this makes sense, correct me if I'm wrong but can we apply a formula similar to the stereo vision formula of Dist = B_f/disp? The issue will be that we don't have a baseline value, but if we could calibrate for a known object distance value then could we find the baseline with the following expression B = Dist_disp/f?
> Excuse me if it sounds crazy, just shooting in the dark

https://github.com/nianticlabs/monodepth2/issues/66

**Comment by pg37013** [comment]
> I have managed to inherit and modify the MonoDataset class for training on the monocular camera video. I went through the past issues and realised the way frames have to be split. 

@sujayj78, could you explain me how did you do this, please? I can't understand how to train on a monocular camera video.
