### ISSUE TITLE
.png option in evaluate_depth.py

### ISSUE THREAD

**Issue by DavidMorillaCabello** [nianticlabs/monodepth2#166]
I don't know if there is any reason but the option to load .png format files is not possible in the script evaluate_depth.py.

If there is no particular reason to not include it, I can create a PR.

Thank you for all your work and the clarity of your code and explanations!

**Comment by mrharicot** [comment]
Hi,
There's actually a reason to not have the extension choice when evaluating the model: we wanted to make sure everyone evaluated on the same original and unchanged png test images. 
I hope this helps!

**Comment by DavidMorillaCabello** [comment]
Perfect! Thank you very much. I will add it for my specific case.
