### ISSUE TITLE
Measure real world distance by mono+stereo output

### ISSUE THREAD

**Issue by stereomatchingkiss** [nianticlabs/monodepth2#168]
From the test_simple.py, we can see

```
output = depth_decoder(encoder(input_color))
disp, _ = disp_to_depth(output[("disp", 0)], 0.1, 100)
```

According to [issue 94](https://github.com/nianticlabs/monodepth2/issues/94) and [issue 47](https://github.com/nianticlabs/monodepth2/issues/47), 

No matter this is disparity or depth, all we need to do is figure out the scale(constant) of different camera when using the pretrained model?

Like 

`disp /= 5.4`

Since the model is trained with fix focal length and ratio, would the accuracy drop down a lot if the image have different ratio or the camera got different focal length, or both? Thanks

**Comment by mrharicot** [comment]
Hi,
You would more likely be looking for a depth scaling factor:
`depth *= factor`

It is really expected to have a drop in accuracy for different focal lengths and aspect ratio, however it is unclear by how much.

**Comment by stereomatchingkiss** [comment]
> You would more likely be looking for a depth scaling factor:
> `depth *= factor`

If I am correct, disp and depth, their difference could be adjusted by a constant.

`D=(f*b/disp)`

So at the end, no matter it is depth or disp, find a proper factor is all I need to do?

The output,

```
output = depth_decoder(encoder(input_color))
disp, _ = disp_to_depth(output[("disp", 0)], 0.1, 100)

```

disp is disparity or depth? Thanks

> It is really expected to have a drop in accuracy for different focal lengths and aspect ratio, however it is unclear by how much.

Thanks, will try

**Comment by stereomatchingkiss** [comment]
I think I find the answer, it is disparity, depth need to inverse it. 1/disp. 
So what you mean is use the 1/disp(depth) multiply with a constant.

**Comment by Varat7v2** [comment]
@stereomatchingkiss As you have mentioned to multiply with a constant factor. What would be the value? Thanks in advance.
