### ISSUE TITLE
Training with DistributedDataParallel

### ISSUE THREAD

**Issue by zCompKid** [nianticlabs/monodepth2#170]
If you are trying to train the models with DistributedDataParallel, this might help :) 

Added lines of codes related the DDP to the _Trainer_ are as follows:
     
    def __init__(self, gpu, ngpus_per_node, options):
            self.opt = options

            self.opt.gpu = gpu
            self.ngpus_per_node = ngpus_per_node
            ## Setup DDP
            if self.opt.multi_gpu:
                self.opt.rank = self.opt.rank * ngpus_per_node + gpu
                dist.init_process_group(backend=self.opt.dist_backend, init_method=self.opt.dist_url,
                                world_size=self.opt.world_size, rank=self.opt.rank)

            self.device = torch.device("cpu" if self.opt.no_cuda else "cuda", self.opt.gpu)
            
            #Repeated for all the models     
            self.models["encoder"].to(self.device)
            if self.opt.multi_gpu:
                self.models["encoder"] = DDP(self.models["encoder"],  device_ids=[self.opt.gpu], broadcast_buffers=False, find_unused_parameters=True) ## Multiple GPU
            self.parameters_to_train += list(self.models["encoder"].parameters())

                
            if self.opt.multi_gpu:
                self.opt.batch_size = int(self.opt.batch_size / ngpus_per_node)
                self.opt.num_workers = int(self.opt.num_workers / ngpus_per_node)

            if self.opt.multi_gpu:
                train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)
            else:
                train_sampler = None

            self.train_loader = DataLoader(
                train_dataset, self.opt.batch_size, shuffle=(train_sampler is None),
                num_workers=self.opt.num_workers, pin_memory=True, drop_last=True, sampler=train_sampler)
            self.val_loader = DataLoader(
                val_dataset, self.opt.batch_size, shuffle=(train_sampler is None),
                num_workers=self.opt.num_workers, pin_memory=True, drop_last=True)

            self.save_opts()

            self.train()

            if self.opt.multi_gpu:
                dist.destroy_process_group()

The _train_ code is as follows:

    if opts.multi_gpu:
            gpu_devices = ','.join([str(id) for id in opts.gpu_devices])
            os.environ["CUDA_VISIBLE_DEVICES"] = gpu_devices
            ngpus_per_node = torch.cuda.device_count()
            opts.world_size = ngpus_per_node * opts.world_size
            mp.spawn(Trainer,
            args=(ngpus_per_node, opts),
            nprocs=ngpus_per_node)

**Comment by zshn25** [comment]
Hey @zCompKid, I am trying DistributedDataParallel but it gives me this error

`RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)
`

Did you come across it?

**Comment by zCompKid** [comment]
Hey @zshn25, I didn't come across this error.
Did you move all tensors to the same device (`.to(self.device)`)? 
I think your input is on GPU1, while the weight parameter is on GPU0.

**Comment by zshn25** [comment]
Thanks you. Yes, I had to send the DDP model to the rank and not to cuda

**Comment by Saadi-AI** [comment]
hey @kaleab-k, Could you please share the code for DDP? I am not able to run my training with DDP.

Can you share the modified trainer.py, train.py and options.py that includes the changes you've made to run in for multi-gpu's via DDP. Thanks
