### ISSUE TITLE
Can I revise resnet encoder, depth decoder?

### ISSUE THREAD

**Issue by kimwongyuda** [nianticlabs/monodepth2#175]
I use my custom images using resize to 1242 * 722.
It is quite different with kitti dataset which is 1242 * 375.
So, I think if i change featrues size of encoder and decoder, 640* 192 into 640 * 372, it will work well.
What do you think about it?

**Comment by mrharicot** [comment]
Hi,
What is the original resolution of your images?
The network architecture only supports input images of size that are a multiple of 32.

**Comment by kimwongyuda** [comment]
Original width and height of input is 3440 and 2000.

**Comment by mrharicot** [comment]
Then you could resize your images to a rough width/height ratio of 1.72, as long as they are multiple of 32.
Note that it doesn't have to be exactly 1.72, but anything reasonably close to it should be fine.
