### ISSUE TITLE
the usage of cpu

### ISSUE THREAD

**Issue by sunjieee** [nianticlabs/monodepth2#176]
when I use this code to train a model, I find out the usage of cpu is almost full (I just run one). how can I set the code to avoid this situation？
![image](https://user-images.githubusercontent.com/9414266/81266017-9fd07180-9076-11ea-89d0-e7515b6152f6.png)

**Comment by mrharicot** [comment]
Hi,
The best way would be to resize the input images to their training size beforehand, to limit the preprocessing done in the dataloader.
Also it seems that you are training a yolov3 model at the same time, I would recommend training only one model at once.
