### ISSUE TITLE
Slow image processing 

### ISSUE THREAD

**Issue by AliChalhoub** [nianticlabs/monodepth2#178]
Hello!
I want to ask I am getting images from my drone and applying this library on my images to get the depth, but the recognition of the depth is **very slow,** any recommendation to make it faster?**(i.e: instead of having 4 fps, i hope to have 0.5 fps, between each image)**

**Comment by mrharicot** [comment]
Hi,
Are you using a GPU for inference?
How are you using the model? Did you write a script that feeds a new frame to the model as soon as it arrives?

**Comment by AliChalhoub** [comment]
First thank you for your reply, 

No, we are using **CPU** because I don't have Nvidia (required to be able to use CUDA, the repository program will automatically run on **GPU** if it detects Nvidia), and because when such program will be deployed it'll run on the drone's internal computer which certainly won't have Nvidia, and yes I trimmed the repository's program and edited it removing unnecessary printing and args parsing, and made it wait to receive an image via multiprocessing pipe, and return the result through pipe as well, so the program never terminates which makes it run faster because every time it runs from the start it has to load the encoder and the model.

Plus, we're using the test_simple.py code, edited such that it loads model and encoder and loops waiting for image through pipe, so its only overhead is the ML inference part, we need to know if this runs as **single thread **or could we somehow edit it to run as multiple processes, because we're strictly limited to running on **CPU**?
 And what if we get a PC with NVIDIA GPU would it solve the whole problem?

**Comment by mrharicot** [comment]
I believe pytorch's cpu backend is vectorized, although I am not sure whether it is multi-threaded for parallel operations.
GPUs are extremely fast at computing tensor operations, a CPU will be ~10X slower (on a workstation).
Monodepth2 despite being a relatively small model is still going to be too slow for realtime cpu inference, esepecially for a drone.
You could replace the resnet18 encoder with a mobilenetv2, wich would result in a drop in accuracy but a speed gain.
