### ISSUE TITLE
Output of the inference

### ISSUE THREAD

**Issue by anakita** [nianticlabs/monodepth2#179]
Hi, great work @mrharicot and team!
I ran the inference command to get the output disparity and the corresponding .npy file 
Command-
`python3 test_simple.py --image_path assets/0000060.jpg    --model_name mono_640x192`

I also got a npy file which I tried to load and here is the sample output:

> [[[[3.4278197  3.3950658  3.3973174  3.3912811  3.3686352  3.3464653
    3.2518392  3.1820812  3.1390328  3.0870607  3.0016708  2.8973062
    2.7342424  2.546234   2.429884   2.3708951  2.2974162  2.232391
    2.1577797  2.1114192  2.0614338  2.0345578  2.0086186  1.9935632
    1.987232   1.9797275  1.9732852  1.9661956  1.9630319  1.9581286
    1.948411   1.9375421  1.9289595  1.9166619  1.9107251  1.9026166
    1.7388816  1.7249755  1.71395    1.7069464  1.7036624  1.6963787]

I wanted to know what exactly do these numbers mean?
Any suggestion is appreciated.
Thankyou

**Comment by lalithnag** [comment]
The .npy file contains the scaled disparity image for the file you passed as input for prediction. You can visualise it using matplotlib or opencv.

**Comment by mrharicot** [comment]
The output is scaled inverse depth, it is not metric, which means that you need to scale it by a single (unknown) scalar to obtain meters.
