### ISSUE TITLE
 How to use one model on different datasets? (Make3D dataset)

### ISSUE THREAD

**Issue by jianan86** [nianticlabs/monodepth2#18]
Hi,

1. You reported performance on the Make3D dataset using models trained on KITTI. Could you give more details, why you choice a center crop of 2 × 1 ratio? Is it because of different camera intrinsics?
2. Have you tried training different datasets with different intrinsics? In this way, a model can be adapted to different datasets, right?

Best regards

**Comment by mdfirman** [comment]
I'll answer question 2, and leave 1 to @mrharicot !

No, we haven't tried this, but it could be possible. See [this recent paper](https://arxiv.org/abs/1904.04998) from Google where the intrinsics are learned during training time for some inspiration.

**Comment by jianan86** [comment]
Thank you for your reply and recommendation. I have read this paper, they use two CNN, one for depth, another for predicting pose and camera intrinsics, then use them during training. But two CNN are independent of each other, not share weights. That means, in the inference phase, depth prediction network can't sense the change of camera intrinsics. I found [another paper](https://arxiv.org/abs/1904.02028) and hope it’ll work.
I'll wait for @mrharicot  to answer question 1. :)

**Comment by mdfirman** [comment]
Great, thanks for the paper pointer. It's CVPR this week so don't expect your first question answered until next week! Thanks.

**Comment by mrharicot** [comment]
Hi,
The crop of 2x1 was chosen because this was how we originally did it in monodepth 1 where the images had a 2x1 ratio (256x512). This is probably not the best way of doing it, especially since we trained on resized kitti images from their original 3.3x1 ratio.
I hope this helps!

**Comment by jianan86** [comment]
Hi

Thank you for your reply. As you prompted me, I have read paper of monodepth 1 again and got the answer. Thank you both again, Looking forward to your more works.

Best regards
