### ISSUE TITLE
Image normalisation in range 0 and 1

### ISSUE THREAD

**Issue by lalithnag** [nianticlabs/monodepth2#180]
Hi, thanks for your work and prompt responses to the issues! I had one question regarding images being in the range 0 to 1. Is it necessary to have our input images in this range? I am finding it hard to locate where the images from the KITTI dataset are being normalized in the range 0 and 1. Could you please point me to that part of the code? 
Thanks!

**Comment by mrharicot** [comment]
Hi,
`torchvision.transforms.ToTensor()` does this!

**Comment by lalithnag** [comment]
Nice! Thanks for clarifying
