### ISSUE TITLE
Getting Depth in meters

### ISSUE THREAD

**Issue by AliChalhoub** [nianticlabs/monodepth2#181]
Hi there! 
Is there a way to get the depth of each point in the image, like a 2x2 matrix (i,j) each (i,j) is a point in the image and in the matrix the value of the depth at this point??

**Comment by lalithnag** [comment]
Hi, the `pred_depth` in evaluate_depth.py [here](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L205) gives you the required depth matrix. You can then reshape it as follows:
`import numpy as np
pred_depth = pred_depth.flatten()` to get a matrix of size 2x(number of pixels)
