### ISSUE TITLE
Using Args and Options from options.py in test_simple.py 

### ISSUE THREAD

**Issue by AliChalhoub** [nianticlabs/monodepth2#182]
Hi there!
I want to ask you how can I use **Args** and **Options** from `options.py ` in `test_simple.py ` 

for example if I want to change in args **max depth** using `--max_depth` which is by default **100** and  I want to make it **50**

**Comment by mrharicot** [comment]
Hi,
The `test_simple.py` script was only meant to easily test the pretrained models on images. These models have been trained with `max_depth = 100`.
These unit are not meters, unless you changed this parameter when training a model there is not reason to change it in `test_simple`.

However if you do need to change it, simply edit this line:
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/test_simple.py#L133
