### ISSUE TITLE
Using Cuda 

### ISSUE THREAD

**Issue by AliChalhoub** [nianticlabs/monodepth2#184]
Hi, 
I want to ask you if I want to use CUDA with the GPU, instead of the CPU, what command should I use to download CUDA? Is there any `pip-command` that download CUDA or `anaconda-cmd` ?

**Comment by mrharicot** [comment]
Hi,

To install cuda you need a recent nvidia gpu.
Here's an example:
https://askubuntu.com/questions/799184/how-can-i-install-cuda-on-ubuntu-16-04

Please keep the issues for problems related to monodepth2's code, stackoverflow is probably a better place for questions like this! :)
