### ISSUE TITLE
Scaling issues with stereo evaluation

### ISSUE THREAD

**Issue by ahmeda14960** [nianticlabs/monodepth2#188]
Hello all,

I've been attempting to evaluate Monodepth2 on images generated from AirSim in order to compare depth predictions with the ground truth depth distances. 

I have been using `test_simple.py` to generate the NumPy files containing the disparities with the 'mono+stereo_1024x320' model. As far as I understand, since the baseline for the KITTI dataset is known we can directly apply a scaling factor to the inverse of the disparities created by a stereo trained model to gain depth estimates. I did so in the following manner:

```python
# load in the disparity arrays generated by test_simple.py
pred = np.load(pred_dir)
# for some reason the disparity arrays are (1, 1, 320, 1024)
pred = pred[0][0]
# This ratio is fixed because of the stereo
# baseline from the KITTI dataset
ratio = 5.4
pred_depth = ratio / pred
pred_depth[pred_depth < 0] = 0
pred_depth[pred_depth > 80] = 80
```

However, I began to suspect I'm doing something wrong with the scaling as I used the imshow function to qualitatively visualize differences between the ground truth and depth predictions.

Here is the `pred_depth` array from above:
![scaled_depths](https://user-images.githubusercontent.com/30680697/82283875-98a63f00-9965-11ea-990d-a746bf964fa1.png)

And here is the ground truth from AirSim:
![ground_truth_scaled](https://user-images.githubusercontent.com/30680697/82284086-25e99380-9966-11ea-8548-3e35c8167034.png)

Of course, I understand that AirSim likely doesn't exactly match the intrinsic camera specifications for the KITTI dataset, but the RMSE values between the ground truth and depth predictions seemed too large. After doing some digging I realized that `test_simple` also outputs a normalized jpeg file with the disparity of each image used in the evaluation set, and these images actually looked pretty reasonable. Here is the first one from the dataset:
![CityEnviron0_disp](https://user-images.githubusercontent.com/30680697/82284433-0868f980-9967-11ea-9bce-d27ea92c0570.jpeg)

And this is the code from `test_simple` that generated the jpeg above
```python
 # Saving colormapped depth image
disp_resized_np = disp_resized.squeeze().cpu().numpy()
vmax = np.percentile(disp_resized_np, 95)
normalizer =  mpl.colors.Normalize(vmin=disp_resized_np.min(), vmax=vmax)
mapper = cm.ScalarMappable(norm=normalizer, cmap="magma")
colormapped_im = (mapper.to_rgba(disp_resized_np)[:, :, :3] * 255).astype(np.uint8)
print('Type for array', colormapped_im.dtype)
im = pil.fromarray(colormapped_im)
```
Now, this next part is why I think I'm doing something wrong. I applied the same code above to created a colormapped depth image to the depth predictions I created in the `pred_depth` array in the first code block above, and the following image was the result:
![sample](https://user-images.githubusercontent.com/30680697/82284708-a3fa6a00-9967-11ea-9ccd-02a146618b4f.jpeg)

If I'm understanding the code from `test_simple` correctly, scaling by the ratio for the KITTI dataset should not affect how the normalized image looks like. And yet there is a clear difference above. Does anyone know why this might be the case? 

P.S. I have tried looking through past issues on the Github page but none of them *quite* match the issue I'm facing, although if I missed a relevant issue please let me know!

**Comment by ahmeda14960** [comment]
Hello all,

Just wanted to bring this issue up. If there's anything wrong with my submission or a point of clarification that I can provide please let me know!

**Comment by mrharicot** [comment]
Hi,
I think the difference comes from the depth clipping you do:
```python
pred_depth[pred_depth < 0] = 0
pred_depth[pred_depth > 80] = 80
```
This is only necessary for kitti evaluation.

Now regarding your airsim question, is the focal length similar to the one used in KITTI?
If both the focal length and the scene content (essentially driving situation) are different, you can't really expect the model to do a reasonable job.

**Comment by ahmeda14960** [comment]
Hey Clement,

Thanks for catching that!

As for the focal length question, this has been something I've been struggling to fully understand on my end. I saw on the README that the KITTI dataset has a stereo baseline of 54 cm, but I read their paper and did not see any mention of the focal length of the cameras they used. What is the relationship between the stereo baseline and the focal length?

As for AirSim, the only setting I can change in this regard is a 'field of view' parameter that allows me to change the field of view in degrees. I've attempted to discern how I should change this to match the focal length used in the KITTI dataset by using the following formula I found on a [photography](https://shuttermuse.com/calculate-field-of-view-camera-lens/) website which is:

![image](https://user-images.githubusercontent.com/30680697/83365120-dc407600-a373-11ea-8ace-c63c5175917c.png)


The only issue is I would need to find the sensor depth which AirSim doesn't define, so it's hard to say but the data I have above most likely does not exactly match the KITTI camera settings. 

With that being said, I don't really have a background in computer vision concepts, so I'm potentially missing something here. Do you have any recommended sources on the topic? I've mostly been working off of definitions I have found around this repo and on various internet websites.

Thanks!

**Comment by mrharicot** [comment]
Hi,
It seems that [UE4's cameras](https://docs.unrealengine.com/en-US/Gameplay/Framework/Camera/index.html) specify the vertical FOV.

KITTI's images have a height of 375 (some scenes have a bit less but let's ignore that for now) and a focal length of 720 pixels, form this we can calculate the vertical FOV in degrees:

```python
fov = np.rad2deg(2 * np.arctan2(0.5 * height, focal))
> fov = 29.193151050988345
```

Regarding learning computer vision here are some books that I recommend:
http://www.computervisionmodels.com/ (I learnt through this one)
http://szeliski.org/Book/ (a classic)

I hope this helps!

**Comment by ahmeda14960** [comment]
Thank you so much Clement! I'll make sure to check out both of the resources :)
