### ISSUE TITLE
Is it possible to train datasets which have different intrinscin matrix simultaneously?

### ISSUE THREAD

**Issue by Jinho-P** [nianticlabs/monodepth2#189]
I make my custom dataset with different two camera (but not stereo system)
(camera 1 with intrinsic K1 and camera 2 with intrinsic K2)
I take images from camera1 and camera2, then, I make total dataset likes

custom_dataset/camera1/data(+calib_cam_to_cam.txt)/*.png
custom_dataset/camera2/data(+calib_cam_to_cam.txt)/*.png
(each calib_cam_to_cam.txt include thier own intrinsic parameter)

But, in 'kitti_dataset.py', it is possible to take only one K intrinsic parameter. 
(in kitti dataset, it is cam2 parameter maybe)

I want to train using 'mono' method with whole images from different cameras...
Do you have some advise? Can I use self.K in kitti_dataset.py as variable?

**Comment by mrharicot** [comment]
Hi,
Yes it is absolutely possible, but you will have to write a new dataset to handle this and make sure it returns the data in the same format as our dataloader.

**Comment by Jinho-P** [comment]
Hi !!

I try to use multiple self.K with one dataloader.

1. Prepare datasets which having different intrinsic parameters.
custom_dataset/camera1/data(+calib_cam_to_cam.txt)/.png
custom_dataset/camera2/data(+calib_cam_to_cam.txt)/.png
I will use these data at the same time
2. Modify dataset code.
I will use split_train information to some flag for choosing self.K value.
If train data is coming from camera1, then self.K = K1
else train data is coming from camera2, then self.K = K2
It is changed in one dataloader. 

I think if dataloader collect multiple data from camera1 and camera2 simultaneously for batch,
It can be the problem to preparing self.K value because some data need to k1 but other need K2...
Is it possible to do this? Or, Is it impossible?

**Comment by mrharicot** [comment]
Hi,
You cannot use `self.K` anymore as it is member variable shared among all the samples.
You need to modify the dataloader such that it doesn't use `self.K`.
You can write a separate function which takes care of creating K for a given sample instead.
