### ISSUE TITLE
The test result of stereo model on my own dataset is bad

### ISSUE THREAD

**Issue by ltshan** [nianticlabs/monodepth2#190]
Hi, 
   Thanks for your innovative work on distance measurment using DNN.

   I studied your monodepth2 and 1 for two more weeks ans can start training and testing on kitti dataset. My question is that the test result is bad after traning on my dataset. 
   My dataset is about 3000 left and right rectified images ,which are put in image_02 and image_03 accordingly. intrinstics K values are also changed by our cameras. 
   My train command is as below:
   python train.py --log_dir stereo_weights/ --model_name stereo --use_stereo --frame_ids 0 --data_path ../stereo --width 960 --height 320 --split eigen_zhou

  The snapshot of  training log is below:
![image](https://user-images.githubusercontent.com/25599553/82728630-26967700-9d24-11ea-8338-d25b4b83fa72.png)

The test image being inpput to trained model is shown as  below.
![000316](https://user-images.githubusercontent.com/25599553/82728672-8a20a480-9d24-11ea-9d50-e4020d8e8d46.jpg)

But the result disparity image is bad as below:
![000316_disp](https://user-images.githubusercontent.com/25599553/82728694-bfc58d80-9d24-11ea-909d-23948a380d0e.jpg)
 
Could you give some advice by my above comments?  thanks again.

**Comment by mrharicot** [comment]
Hi,
Did you make sure your intrinsics are normalized?
Can you share a couple example stereo pairs?
There's a big occluder on the left of the image, are all images like this?

**Comment by ltshan** [comment]
Hi 
Thanks for your quick response.
Yes, my intrinstics alre normalized. 
My one set of training left and right images are shown as below, which exist some occluder.  And all of images, including training and testing, looks like it. 
![image](https://user-images.githubusercontent.com/25599553/82741657-1c599480-9d87-11ea-9c33-c9b10476708d.png)

**Comment by mrharicot** [comment]
I'm afraid monodepth2 cannot cope with situations like this without modifications.
I would suggest creating a mask which matches this occluder and use it to ignore the loss in this region.

**Comment by ltshan** [comment]
ok.  
I'll change the dataset to test  again, thanks.
