### ISSUE TITLE
Question about SSIM implementation

### ISSUE THREAD

**Issue by wintertee** [nianticlabs/monodepth2#191]
Hello,
I'm confusing about the [SSIM implementation](https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/layers.py#L218)...

I think (but I'm not sure) that `nn.AvgPool2d(3, 1)` here is meant to calculate the mean value in a 3*3 block, and with a padding, `SSIM()` finally returns a SSIM index map with the same size of the original input.

But in [Zhou Wang, Alan Conrad Bovik, Hamid Rahim Sheikh, and Eero P Simoncelli. Image quality assessment: from error visibility to structural similarity. TIP, 2004.](https://www.cns.nyu.edu/pub/lcv/wang03-preprint.pdf), it is written:

> In this paper, we use an 11 × 11 circularsymmetric Gaussian weighting function with standard deviation of 1.5 samples, normalized to unit sum.

Does the 3*3 average pooling correspond to the *standard deviation of 1.5* ?

**Comment by mrharicot** [comment]
Hi,
Great question! We do not use the actual SSIM function but a simplified version of it.

**Comment by wintertee** [comment]
I see. Thank you very much : )
