### ISSUE TITLE
Question about calculating depth using disparity value

### ISSUE THREAD

**Issue by taiyar-046** [nianticlabs/monodepth2#194]
Since I know the relationship between depth and disparity is: depth = fu * b / disparity, where fu is the camera intrinsic and b is the baseline between the stereo camera, your code to calculate this is depth = b / disparity. May I know why you do like that?

**Comment by mrharicot** [comment]
Hi,
Please have a look at previous issues:
https://github.com/nianticlabs/monodepth2/issues/159#issuecomment-599712590
