### ISSUE TITLE
Time required to test a picture

### ISSUE THREAD

**Issue by liubron** [nianticlabs/monodepth2#195]
Hi，I am using test_simple.py to test a picture, but I only have a CPU, and the test time is about 1 second. May I ask, how long will it take for you to test a picture with GPU? Or how many FPS can be achieved during the test with GPU?

**Comment by mrharicot** [comment]
Hi,
`test_simple` hasn't really been optimized for speed, but on a GPU monodepth2 runs in the order of a few milliseconds.

**Comment by liubron** [comment]
I want to apply this model to the 30 FPS scenario. If GPU is used, is it applicable?

**Comment by mrharicot** [comment]
Yes, on a desktop-class gpu it should be able to reach this framerate.
