### ISSUE TITLE
The ground truth velodyne depth of kitti.

### ISSUE THREAD

**Issue by MRinel** [nianticlabs/monodepth2#197]
Hi, amazing work for depth prediction! I have a few questions on kitti ground truth and visualization.
The ground truth velodyne depth being very sparse, how to interpolate it for visualization?
like:(from kitti depth prediction/ annotated depth map dataset)
![image](https://user-images.githubusercontent.com/28338959/83972902-6dd05a80-a915-11ea-99cc-3901884deda0.png)
visualize :
![image](https://user-images.githubusercontent.com/28338959/83972920-8f314680-a915-11ea-9b91-b4c0d4c85942.png)
I tried to complete the depth map, but it didn't work as well as above.
In addition, RMSE is calculated using the original sparse depth map, right?

**Comment by mdfirman** [comment]
If you are trying to densify the depth maps for visualisation there are a few options.

You could try out scipy's interp2d function (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html). 

There is also at least one option on [this thread](https://github.com/tinghuiz/SfMLearner/issues/45).

And yes, all the metrics are computed on the sparse depth map.

Thanks
