### ISSUE TITLE
the size of numpy outputs don't meet the ones of color images

### ISSUE THREAD

**Issue by DrChanging** [nianticlabs/monodepth2#198]
Thank you for your wonderful work!
I applied the pre-trained model in an indoor environment(test every model from 640x192 to 1024x320).
The colored disp_images are actually better than expected.
It could tell the relative depth of different surface in a scene, that's really amazing!
However, unlike the colored disparity images, the numpy (I also saved them as .txt) outputs have different size from the input images.
For instance, the input image is a 640x480 image, the disp_image would be 640x480.
But in the numpy file there are only 640x192 values (depends on the model loaded).
Anybody knows how to fix this? Is retraining the only way to solve it?

**Comment by mdfirman** [comment]
Hello, and thank you for your interest in the repo!

The way the prediction works is that your input image is resized to the size that the network has been trained with. So your 640x480 image was resized to 640x192 to be input to the network, at [this line](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L118). The numpy file is then saved at this network output resolution (640x192).

However, the visualisation is resized to the size that your input image was ([here](https://github.com/nianticlabs/monodepth2/blob/master/test_simple.py#L127)). This is why you see a discrepency. 

Whether it makes more sense for you to use the output at 640x192 or 640x480 will depend on what you plan to use it for! 

Hope this helps.
