### ISSUE TITLE
two inputs compute identity_reprojection_losses

### ISSUE THREAD

**Issue by Darknesszlx** [nianticlabs/monodepth2#199]
In trainer.py, line432-445, why two inputs, for example, inputs[("color", 0, source_scale)] and inputs[("color", 's', source_scale)], compute identity_reprojection_losses, since there are no learnable params in these two params.

**Comment by mdfirman** [comment]
Hi there,

This is used in the computation of the identity reprojection loss for automasking – eqn 5 in the paper.

There aren't any learnable parameters in the computation of this value, but it is necessary for computing eqn 5. 

I hope this helps!
