### ISSUE TITLE
How to do forward warping?

### ISSUE THREAD

**Issue by ezorfa** [nianticlabs/monodepth2#200]
@mrharicot @macaodha @mdfirman 

Hi everyone,

I was playing with your code and see that you have used inverse warping. I would like to know how to achieve forward warping. Anyone has any information about any paper that utilizes this warping technique?

Thank you!

**Comment by davdmc** [comment]
If it's for applying it to the network, there was a [discussion](https://github.com/nianticlabs/monodepth2/issues/87) in the closed issues why it's not advisable. But it also includes multiple resources about the theory of forward/inverse warping.

**Comment by mrharicot** [comment]
@davdmc great answer! the linked thread is a great resource.
