### ISSUE TITLE
Will this method work for very small camera movement?

### ISSUE THREAD

**Issue by sieme97** [nianticlabs/monodepth2#202]
Can we get pose and depth if the camera motion is too small? For example, if the camera just moves 1 mm.

**Comment by daniyar-niantic** [comment]
This method relies on reprojection to estimate depth and pose, which means that it needs sufficient baseline between frames. If the camera moves only 1mm between frames, it would not be enough. You could try choosing frames that are further away from each other in time (and as a consequence in space)? At the end of the day, it is hard to say without knowing what kind of data you are working with.
