### ISSUE TITLE
Custom dataset : Size issue

### ISSUE THREAD

**Issue by amsdak15** [nianticlabs/monodepth2#205]
Hello, Thank you for your good work.  I have a few doubts which I am stating below.

I am planning to train on my custom monocular dataset. For that, I have created a  new dataloader class subset of MonoDataset, but I fail to understand how the different image sizes play a role in the code.

I mean there is an original image size of the training images. Then there is a resized image size which is specified in the code and there is an input image size which we specify in the options or terminal when we train the model.

I have images that are stored in the datapath with the original image size(1240 x 716). But when I specify the width and height parameters while training as 1240 x 716, it shows Cuda error: out of memory. I have a Nvidia GPU of 8 GB.

My training images are 1003 and validation images are 12. 

In order to resolve this issue, do I need to resize the images in the datapath separately beforehand to a lower resolution(say 320 x 192) and keep the intrinsic matrix unchanged and only change the input image size to the lower size(320 x 192)?

I will be greatly thankful if you could help me.

**Comment by mdfirman** [comment]
Thanks for your interest. No, you don't need to resize the images beforehand. You should be able to just choose a height and width to train the model with, using the `--width` and `--height` flags. Images will be resized to this size in the dataloaders, and this will also be the input dimensions for the model.

1240 x 716 is a very large size, especially for an 8GB GPU. I'd recommend trying something small to start with, for example `--height 128 --width 224`. Then if training works ok you can then increase the image size.

By the way, the number of training images you have seems quite small. If training struggles, I would recommend starting with a pretrained KITTI model we provide and finetuning on your dataset (perhaps at a lower learning rate).

Good luck – let us know how you get on!

**Comment by amsdak15** [comment]
Thank you for your kind response. Your solution really helped me achieve good results.

Currently, I am training on my dataset with more number of images(15000) and an image resolution of 512x384 for training the network. However, the predicted depth map is mostly black( depth decoder output being either 0 or above 100). However, when I train with smaller image resolution( say 320x192), it is able to predict good depth. I am not able to find the reason for this type of results. Also, randomly sometimes, it is able to predict depth properly when training with an image resolution of 512x384 but most of the time it fails to do so. 

What can be the possible reason for this and what can I do to get good results?

Thank you in advance.
