### ISSUE TITLE
Issue with the ImageNet pretrained model

### ISSUE THREAD

**Issue by KunB-Fighting** [nianticlabs/monodepth2#211]
It seems that kernels in the pretrained model are all 1x1 not 3x3, and thus cannot be loaded.
`Loading encoder weights...
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    trainer = Trainer(opts)
  File "/home/kunb/Codes/monodepth2/trainer.py", line 108, in __init__
    self.load_model()
  File "/home/kunb/Codes/monodepth2/trainer.py", line 642, in load_model
    self.models[n].load_state_dict(model_dict)
  File "/home/kunb/Installed/Anaconda3/envs/scsfm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetEncoder:
        size mismatch for encoder.layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for encoder.layer1.1.conv1.weight: copying a param with shape torch.Size([64, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).

 torch.Size([512, 256, 3, 3]).
        size mismatch for encoder.layer4.0.downsample.0.weight: copying a param
with shape torch.Size([2048, 1024, 1, 1]) from checkpoint, the shape in current
model is torch.Size([512, 256, 1, 1]).
        size mismatch for encoder.layer4.0.downsample.1.weight: copying a param
with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layer4.0.downsample.1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layer4.0.downsample.1.running_mean: copying a
param with shape torch.Size([2048]) from checkpoint, the shape in current model
is torch.Size([512]).
        size mismatch for encoder.layer4.0.downsample.1.running_var: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layer4.1.conv1.weight: copying a param with shape torch.Size([512, 2048, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
        size mismatch for encoder.fc.weight: copying a param with shape torch.Size([1000, 2048]) from checkpoint, the shape in current model is torch.Size([1000, 512]).
`

**Comment by mrharicot** [comment]
Hi,
Can you share what command you ran and what modifications you did to the code?

**Comment by KunB-Fighting** [comment]
Hi,
I use the command 
`python train.py \
--data_path /data/kunb/kitti_raw/raw_data_downloader --png \
--model_name retrain_mono+stereo \
--frame_ids 0 -1 1 --use_stereo \
--load_weights_folder /home/kunb/Codes/monodepth2/models/mono_resnet50_640x192 \`
and I clone a original version from github for test and didn't edit it, but the result is still the same.

**Comment by mrharicot** [comment]
Well that's confusing!
What versions of `pytorch`, `torchvision` and `python` are you using?

**Comment by KunB-Fighting** [comment]
this is the information from conda
`python                    3.6.10               h7579374_2    defaults
torch                     1.0.1                    pypi_0    pypi
torchvision               0.4.2           cuda100py36hecfc37a_0    defaults`

**Comment by KunB-Fighting** [comment]
I download the parameters from the address in

> Finally, we provide resnet 50 depth estimation models trained with ImageNet pretrained weights and trained from scratch.

**Comment by mrharicot** [comment]
Oooh my bad. You need to pass `--num_layers 50` as you are trying to load the resnet50 model.

**Comment by KunB-Fighting** [comment]
Thanks a lot !!! That really saves me !!!
