### ISSUE TITLE
Something wrong in training with custom datasets

### ISSUE THREAD

**Issue by TSAI-CHANCHANG** [nianticlabs/monodepth2#213]
Hi,
Thank you a lot for your amazing work.

I am trying to train the net using another dataset called RGB-D Dataset 7-Scenes
https://www.microsoft.com/en-us/research/project/rgb-d-dataset-7-scenes/

**Environment**
(I am using Colaboratory provided by Google)
Tesla K80
CUDA         10.1
Python       3.6.9
pytorch      1.5.1+cu101
torchvision 0.6.1+cu101 
**Dataset struct**
7scenes/
-----office/
--------------seq-01/
-------------------depth/
----------------------------frame-000000.depth.png
----------------------------frame-XXXXXX.depth.png
-------------------rgb/
----------------------------frame-000000.color.png
----------------------------frame-XXXXXX.color.png
-------------seq-0X/

-----chess/
-----fire/

**My class**
```python
from __future__ import absolute_import, division, print_function

import os
import skimage.transform
import numpy as np
import PIL.Image as pil

from .mono_dataset import MonoDataset

class SevenDataset(MonoDataset):
    def __init__(self, *args, **kwargs):
        super(SevenDataset, self).__init__(*args, **kwargs)

        self.K = np.array([[585, 0, 320, 0],
                           [0, 585, 240, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)
        self.full_res_shape = (1242,375)

    def check_depth(self):
        return True

    def get_color(self, folder, frame_index, side, do_flip):
        f_str = "frame-{:06d}.color{}".format(frame_index, ".png")
        image_path = os.path.join(self.data_path, folder, "rgb", f_str)
        color = self.loader(image_path)
        if do_flip:
            color = color.transpose(pil.FLIP_LEFT_RIGHT)
        
        return color

    def get_depth(self, folder, frame_index, side, do_flip):
        f_str = "frame-{:06d}.depth{}".format(frame_index, ".png")
        image_path = os.path.join(self.data_path, folder, "depth", f_str)
        depth = self.loader(image_path)
        if do_flip:
            depth = depth.transpose(pil.FLIP_LEFT_RIGHT)
        
        return depth
```

in `option.py`, I also add some choice to make the trainer choose my dataset:
add `7scenes` to `--split`
add `seven` to `--dataset`
and I also modify the relevant part in `trainer.py`
I also generate my own `train_files.txt` and `val_files.txt` so the `trainer` can train.
Something like:
```
chess/seq-01 1
chess/seq-01 2
chess/seq-01 3
chess/seq-01 4
chess/seq-01 5
chess/seq-01 6
...
```

And I run the following command:
```sh
python /content/drive/My\ Drive/monodepth2/train.py --data_path /content/drive/My\ Drive/monodepth2/splits/7scenes --model_name mono_model --split 7scenes --dataset seven --height 480 --num_workers 0 --batch_size 2
```
It gives the result as follows:
```sh
Training model named:
   mono_model
Models and tensorboard events files are saved to:
   /root/tmp
Training is using:
   cuda
Using split:
   7scenes
There are 998 training items and 998 validation items

/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Training
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3226: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
epoch   0 | batch      0 | examples/s:   2.1 | loss: 0.07911 | time elapsed: 00h00m01s | time left: 00h00m00s
Traceback (most recent call last):
  File "/content/drive/My Drive/monodepth2/train.py", line 18, in <module>
    trainer.train()
  File "/content/drive/My Drive/monodepth2/trainer.py", line 190, in train
    self.run_epoch()
  File "/content/drive/My Drive/monodepth2/trainer.py", line 222, in run_epoch
    self.compute_depth_losses(inputs, outputs, losses)
  File "/content/drive/My Drive/monodepth2/trainer.py", line 519, in compute_depth_losses
    depth_pred = depth_pred[mask]
IndexError: too many indices for tensor of dimension 4
```

It seems the problems are relevant to the `--num_workers`. 
Any idea to solve this problem?

P.s.: When I run this code on my own PC, since my CPU is 6 core 12 thread CPU, I set num_of_workers as default value `12` and `--batch_size` as default `12`. It can load the data but soon the GPU is out of memory (I am using RTX 2060 6GB). When I also set ‘--num_workers’ as 0, same error occurs.

**Comment by mrharicot** [comment]
Hi,
It seems that you have a few issues here.

1. `self.K` should be normalized by the image width (first row) and height (second row).
2. Your error also says `too many indices for tensor of dimension 4`. It seems that the inputs are the wrong shape. Are you sure `color` and depth` are the right shapes? they should be respectively 3xhxw and 1xhxw.

**Comment by TSAI-CHANCHANG** [comment]
Thank you for replying!
1. so I just replace the `self.K` as follows, then is ok?
```python
self.K = np.array([[585/480, 0, 320/480, 0],
                           [0, 585/640, 240/640, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)
```
2. I found my error is due to the mistake in the function `get_depth`, this function should load depth using `PIL.Image.open`, not the loader in the class.
3. Well, I know it is very little to train a model, in fact, this dataset contains enough data (about 5000+ for each scene), I just want to try to run the whole code successfully then add more data to training.
Whatever, thank you for your suggestions!

**Comment by mrharicot** [comment]
Hi,

1. No you flipped width and height.
```python
self.K = np.array([[585/640, 0, 320/640, 0],
                           [0, 585/480, 240/480, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)
```
Good luck!
