### ISSUE TITLE
Question about stereo_T[0, 3] = side_sign * baseline_sign * 0.1

### ISSUE THREAD

**Issue by Darknesszlx** [nianticlabs/monodepth2#214]
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/datasets/mono_dataset.py#L196

why it's 0.1, but not 0.2, 0.3... or other values?

**Comment by mrharicot** [comment]
Hi,
The network sometimes struggled to train properly at the beginning with a baseline of 1.0, reducing it by 10x made it much more stable.
I hope this helps!
