### ISSUE TITLE
kitti_utils.py

### ISSUE THREAD

**Issue by jilner** [nianticlabs/monodepth2#215]
Thanks for the great job.
I find a question in kitti_utils.py  in   “velo = velo[velo[:, 0] >= 0, :]”，  and I see the official kitti in run_demoVelodyne.m  it may be  “velo = velo[velo[:, 0] >= 5, :]”.
And I don not know the physical meaning of this operation  "velo_pts_im[:, :2] = velo_pts_im[:, :2] / velo_pts_im[:, 2][..., np.newaxis]", could you help me?
Best wishes.

**Comment by mrharicot** [comment]
Hi,
1. That is indeed different, nice catch. I believe we originally wrote this to match Eigen's matlab code. I doubt there will be much of a difference though.
2. This is a projection, we divide `[x, y]` by `z`
I hope this helps!

**Comment by jilner** [comment]
> Hi,
> 
> 1. That is indeed different, nice catch. I believe we originally wrote this to match Eigen's matlab code. I doubt there will be much of a difference though.
> 2. This is a projection, we divide `[x, y]` by `z`
>    I hope this helps!

Thank you  very  much！
