### ISSUE TITLE
What is the maximum reliable depth that this model can predict?

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#218]
Hi, Thank you for your excellent paper. I have a question (which may be a little unprofessional).

  In the depth map, the outline of objects close to the camera is relatively clear, but the accuracy of distant objects gradually decreases. Finally, some objects in the RGB image do not appear in the depth map. Is there a maximum reliable prediction distance?

  The problem can also be described as: when the depth of the object predicted by this model is infinite (In fact, that object is not infinitely far away from the camera), what is the approximate distance between the object and the camera? 

  The problem can also be described as: when the depth information predicted by the model is no longer reliable, what is the approximate distance between the object and the camera?

  Thank you for taking the time to answer my unprofessional questions!

**Comment by mrharicot** [comment]
Hi,
This is a question difficult to answer, there's no distance at which the network stops being reliable.
Typically with stereo methods the uncertainty in depth grows with the square of the depth:
https://robotics.stackexchange.com/questions/11749/estimate-disparity-error-for-depth-accuracy-estimation

The added complexity here is that it's a neural network preditcting from a single image on top of that, so I would assume it is at least as unreliable as the stereo case.

Also monodepth2 doesn't predict infinite depths, we map the prediction to be between 0.1 and 100 units.

I hope this helps!

**Comment by whyygug** [comment]
Hi, thank you for your reply. It really helps me understand the depth estimation. Thank you!
