### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by YJonmo** [nianticlabs/monodepth2#219]
Hi again and thanks for this great work.

I was wondering if there is any way to resume a semi trained network. I was training a network but the server stopped working sometime in the middle of the training. I cannot find a key such as --continue or --resume in the options. Do you I have to load a the last trained model?

Regards,
Jacob

**Comment by mrharicot** [comment]
Hi,
You can restore a training session using `--load_weights_folder` and pass the checkpoint folder you want to load.
We do not save other info such as epoch number and so on so it will restart from epoch 0.

I hope this helps!

**Comment by YJonmo** [comment]
Thanks for the info.

I have one other question. It may sound silly but it could save some time for me:

I am trying to train the model with more than 2 frames in order to get a better pose estimation. So I am setting the number of the input frames to 5 or 7 like below setting but I get errors: 

OUTPUT='3DprintedKnee_Stereo_Mono1234_PredicMaskAll'
mkdir -p $OUTPUT
DataSet='3DPrintedKnee_Stereo1234'
python train.py --data_path $DATA_Folder --split $DataSet --log_dir $OUTPUT/ --png --no_eval --dataset Custom --height 256 --width 256 --frame_ids 0 -1 -2 -3 1 2 3 --use_stereo --predictive_mask --disable_automasking --pose_model_input all 

  File "/home/xxxxxxx/Python/monodepth2-master/trainer.py", line 318, in predict_poses
    axisangle[:, i], translation[:, i])
IndexError: index 2 is out of bounds for dimension 1 with size 2

The  print(np.shape(axisangle))   print(np.shape(translation)) gives me  :
torch.Size([12, 2, 1, 3])
torch.Size([12, 2, 1, 3])
Which I believe should be something like [12, 6, 1, 3]

I also tried to use the posecnn using this setting and I still got error:
OUTPUT='3DprintedKnee_Stereo_Mono123_PredicMask_posecnnAll'
mkdir -p $OUTPUT
DataSet='3DPrintedKnee_Stereo'
python train.py --data_path $DATA_Folder --split $DataSet --log_dir $OUTPUT/ --png --no_eval --dataset Custom --height 256 --width 256 --frame_ids 0 -1 -2  1 2  --use_stereo --disable_automasking  --pose_model_type posecnn --pose_model_input all

  File "/home/xxx/Python/monodepth2-master/trainer.py", line 370, in generate_images_pred
    axisangle = outputs[("axisangle", 0, frame_id)]
KeyError: ('axisangle', 0, 's')

Any idea?

Alternatively, please let me know how I should used more than one frame (stereo pairs) to train the model. 

Cheers,
Jacob

**Comment by mdfirman** [comment]
I think the problem is that in a few places we have hardcoded the number of frames the pose net predicts for, e.g. here:
https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L77

In general when doing pose with more frames you have the option of either (a) getting the pose net to simultansouly predict the relative pose between all the frames (I think this is the route you are pursuing; I think Zhou et al. also took this route), or (b) making separate pairwise predictions between the target frame and each source frame in turn.
