### ISSUE TITLE
Intrinsic matrix

### ISSUE THREAD

**Issue by logsanand** [nianticlabs/monodepth2#220]
Hi,
       Thanks a lot for the code. I am new to this and trying to understand the code. The intrinsic matrix is generally of dimension 3 cross 3 and from your code, I could see it as of 4 cross 4. Please can you mention what is the last dimension?.

**Comment by mrharicot** [comment]
Hi,
The last column is just a 1 in the last row (as with an identity matrix).
I'm not entirely sure why I made it a 4x4 matrix back when I wrote the code but you're correct, it's typically a 3x3. :)
