### ISSUE TITLE
How do I save the depth map as a uint16 image?

### ISSUE THREAD

**Issue by JeisonPham** [nianticlabs/monodepth2#221]
I want to save the depth map as a uint16 image and I tried referencing https://github.com/nianticlabs/monodepth2/issues/76#issuecomment-533791514 for help but my depth map produced is just a white image. 
![0_img_depth](https://user-images.githubusercontent.com/20037757/88019786-663ccd80-cadf-11ea-9e18-a718e34c780b.jpeg)
is there some preprocessing I need to do before hand?

**Comment by mrharicot** [comment]
Hi,
`uint16` is an unsigned integer between 0 and `2**16 - 1`, so you need to map the disparity or depth image to that range.
We actually do this in the code to export for the online kitti benchmark:
https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L158

I hope this helps!

**Comment by surfii3z** [comment]
> I want to save the depth map as a uint16 image and I tried referencing [#76 (comment)](https://github.com/nianticlabs/monodepth2/issues/76#issuecomment-533791514) for help but my depth map produced is just a white image.
> ![0_img_depth](https://user-images.githubusercontent.com/20037757/88019786-663ccd80-cadf-11ea-9e18-a718e34c780b.jpeg)
> is there some preprocessing I need to do before hand?

I also have this problem when writing the image with .jpeg/.jpg extension. When I write the image with uint16 with .png then it seems OK.

**Comment by mrharicot** [comment]
If you want to write the depthmap as a jpeg you need to cast it to uint8 first (integer between 0 and 255) or uint16 [0, 65535]

**Comment by Saquibkhan456** [comment]
Just multiply the float32 depthmap by 4000 and then convert it to int16. To retrieve the depth values, just divide it by 4000 again when you need it.
