### ISSUE TITLE
Different evaluation results using similar method.

### ISSUE THREAD

**Issue by poornimajd** [nianticlabs/monodepth2#222]
Thank you for the excellent work!
When I tried the kitti evaluation script on a few kitti images,using the velodyne raw .bin files, I got the following results:
![kittimono2](https://user-images.githubusercontent.com/31023599/88059652-c89ada00-cb82-11ea-9cb9-be2ce7c4700c.png)
But when I used the below code from kitti_utils to save the depth images(using opencv)
https://github.com/nianticlabs/monodepth2/blob/master/kitti_utils.py#L96
and generated the gt_depth.npz using export _gt_depth.py, then by using the same kitti_eval code, I get the following result:
![kittimono2own](https://user-images.githubusercontent.com/31023599/88059998-3fd06e00-cb83-11ea-9060-d65d29f654d9.png)
What is it that is going wrong?
Ideally both methods are the same, but why is the result so different?
Any suggestion is greatly appreciated.

**Comment by mrharicot** [comment]
Hi,
I am not sure I understand what you did differently between the two evaluations?
What format did you use to save the depth images? You should save them using numpy as they are floating point images.

**Comment by poornimajd** [comment]
There is no difference in the two procedures and hence the result should be same.I saved it in .tif format (32-bit floating point number) and it gave similar results,in both the methods.Thank you for the suggestion.
