### ISSUE TITLE
training on custom dataset

### ISSUE THREAD

**Issue by tonytu16** [nianticlabs/monodepth2#225]
Hello, does the format of the RGB images have to be jpg? I am aiming to train on a dataset that is in .JPEG format but it can't seem to find those files (my file path is correct). Thank you. 

<img width="771" alt="Screen Shot 2020-07-26 at 12 29 09 PM" src="https://user-images.githubusercontent.com/33640387/88487608-9cdd7280-cf3b-11ea-988e-1259f5ba190a.png">

**Comment by mrharicot** [comment]
Hi, the format does not have to be jpeg, you can simply use whatever you want in the image loading function:
https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L202
Your dataloader should probably inherit from mono_dataset rather than kitti_dataset.

**Comment by tonytu16** [comment]
Hi, thank you for your reply. I changed the self.K, resolution, and replaced the data in KITTI_dataset with my images. The data seems to load but after training for 3 minutes I keep getting this keyerror. Any idea why? Thank you!

![Screen Shot 2020-07-26 at 1 48 37 PM](https://user-images.githubusercontent.com/33640387/88489054-b59f5580-cf46-11ea-81eb-6fd00de4d6eb.png)

**Comment by mrharicot** [comment]
As you can see in the error message you are trying to read `None` into `self.side_map[side]` which means that `side` is `None` for some reason.

**Comment by daniyar-niantic** [comment]
@tonytu16 have your managed to fix your issue?
