### ISSUE TITLE
Few questions regarding the evaluation script for ground truth as image

### ISSUE THREAD

**Issue by anakita** [nianticlabs/monodepth2#228]
Thanks for the great work!
I have the depth map from zed camera as the ground truth,for example as shown below:
![depth_27](https://user-images.githubusercontent.com/64612239/88766496-c1348b80-d195-11ea-9ead-4264d39561f0.jpg)

I converted the image(depth map) to .npy file and then converted it to gt_depths.npz using the following code(a part of export_gt_truth.py)
```
path='./'
gt_depth=np.load('00000000.npy') #name of the .npy file
gt_depths.append(gt_depth.astype(np.float32)/256) #I saved the .npy file in float32 format
output_path = os.path.join(path, "gt_depths.npz")
```
I used this .npz fle as input to evaluate_depth.py with scale_factor=0.63 (as the camera baseline is 63mm)
I have the following questions:

1.How to know if we need to divide by 256?

2.Does it matter even if we do not divide it by 256 (in case of custom dataset),because the median scaling factor in the evaluation script takes care of it?

3.I got the values for all the metrics using the above stated method,but can someone help me out to know if this method is the right way to evaluate the predictions when we have the direct depth image as ground truth?

4.If I want to limit the evaluation only to a certain distance ,for example only 20m , then only changing MAX_DEPTH=20, in options.py is sufficient?

Thanks in advance for the answers.

**Comment by mrharicot** [comment]
Hi,
Before I start, I need to point out that the evaluation you are trying to use was solely made for KITTI.
However you can use it as a reference or inspiration for writing your own evaluation.
The image you are showing is actually (likely) inverse depth, was that on purpose?

1. This is only necessary when loading the 16bit PNG depths from KITTI.
2. Once loaded the ground truth isn't altered and only the predicted depth is aligned to it using median scaling.
3. The metrics used for KITTI seem to be standard and also used for the NYUv2 evaluation. Just make sure your ground truth depth really is in meters.
4. Yes that should be fine!

I hope this helps!

**Comment by anakita** [comment]
Thanks for the quick reply!


> The image you are showing is actually (likely) inverse depth, was that on purpose?

The image which I have shown is the depth image and not the inverse.

I will recheck the units of the depth and try the evaluation again,if needed.

**Comment by mrharicot** [comment]
> The image which I have shown is the depth image and not the inverse.

It seems to be inverse depth, as closer points appear brighter than further ones, unless you used an inverse colormap.
