### ISSUE TITLE
Custom dataset output

### ISSUE THREAD

**Issue by logsanand** [nianticlabs/monodepth2#229]
Hello,
             Thanks a lot for the code. I created a dataset and updated the K, image etc and trained the model. After training, when I tested it with a single image(KITTI), I got the output same as the input image with the disparity colour scale and range. It looked exactly similar like input image, buildings and other features and only the colour scale was different. I would like to know whether I should modify some other details.
![kitti1_disp](https://user-images.githubusercontent.com/48712112/88916547-8cdcd000-d266-11ea-9ef8-516484ae4676.jpeg)

Thanks!!!

**Comment by daniyar-niantic** [comment]
Hi @logsanand 
Do you know if your model actually managed to train? Do disparity maps in tensorboard look reasonable?

**Comment by logsanand** [comment]
Hi Daniyar,
                   Actually it didn't, I happened to tune it now. Now it looks much better. Thanks for your reply.
