### ISSUE TITLE
How to work in indoor scene

### ISSUE THREAD

**Issue by xieqingxing** [nianticlabs/monodepth2#23]
Hi,thanks for your work
I want to train ASN model use stereo mode in indoor scene,I change max_depth in option.py,but the model not fit.maybe need to changes more parameters? hope you get me some advice,thank you

**Comment by daniyar-niantic** [comment]
Hi @xieqingxing,

Have you also changed the [intrinsics](https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L24) and [extrinsics](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L193) for the indoors dataset?

**Comment by xieqingxing** [comment]
thanks for you quickly reply
I have changed the  intrinsics,but haven't changed extrinsics.thanks your tips
