### ISSUE TITLE
Is the groundtruth of KITTI dataset's depth range from 0 to 80 meters? 

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#231]
Hi, I would like to ask a question, is the groundtruth of KITTI dataset's depth range from 0 to 80 meters? Or is it larger than 80 meters, but we cut it artificially to within 80 meters?
I am confused because the information I consulted on the Internet says that KITTI dataset used Velodyne HDL-64E rotating 3D laser scanner, whose range is 120m.

**Comment by mrharicot** [comment]
Hi,
The LIDAR samples can have a depth larger than 80m, I believe we originally capped the depths at 80m to match Eigen's experiments.
