### ISSUE TITLE
why use contrast transform in ColorJitter?

### ISSUE THREAD

**Issue by Darknesszlx** [nianticlabs/monodepth2#234]
https://github.com/nianticlabs/monodepth2/blob/101dd03f00e0d8e9bcd8a8d760f94bc2820f5549/datasets/mono_dataset.py#L69-L80

in pytorch, contrast transform in ColorJitter is to blend image and mean(image).
https://github.com/pytorch/vision/blob/c547e5cbbf25e46870abb2e925b42c67c3367afc/torchvision/transforms/functional_tensor.py#L109-L129

for example, in stereo images, the mean of left and right image may be different, so contrast transform may led to left and right images is not doing the same transform. It breaks photo-consistency in source left and right images.

**Comment by daniyar-niantic** [comment]
Hi @Darknesszlx 

The color augmented image is used as input to the network, but reprojection loss is computed using original images, so the photo-consistency is not changed.
