### ISSUE TITLE
About the teaser gif

### ISSUE THREAD

**Issue by rxqy** [nianticlabs/monodepth2#239]
Hi, thanks for sharing the code.
Which model do you use to generate the teaser gif? The stereo model or mono model?
If mono, which strategy do you use to scale the estimated depth? One same scaling factor or a scale per image as in the eval?

**Comment by mdfirman** [comment]
Hi, thanks for your interest!

I'm pretty sure it was the `mono+stereo_192x640` model which was used. 

And for the scaling factor: I don't think it was per-frame, as this ended up causing too much visual instability as trees and other foreground objects came into view. I would say it's most likely a hard-coded vmin and vmax, which were chosen by eye to show the range of depths on this street. Sorry I don't remember exactly!

**Comment by rxqy** [comment]
Many thanks!
