### ISSUE TITLE
Unable to replicate results on make3d

### ISSUE THREAD

**Issue by hemangchawla** [nianticlabs/monodepth2#240]
Hello,

Using your code to evaluate on make3d (https://github.com/nianticlabs/monodepth2/issues/89#issuecomment-546005042)  and your provided depth checkpoint trained on KITTI eigen, we are **unable** to replicate your results for make3d.

We center crop the image to 2:1 (only height is cropped) as for kitti (mono_640x192) and pass it through the network.  The output depth map is resized to match the cropped 21 x 305 ground truth depth maps. 

This is what we get:
```
abs_rel |   sq_rel |     rmse | rmse_log |
   0.556 ,    8.714 ,   11.488 ,    0.253 ,
```
This is what you have reported in the paper:
```
abs_rel |   sq_rel |     rmse | rmse_log |
0.322,      3.589,       7.417,       0.163,
```

- Did you train on a different split of kitti while testing on make3d? We use the checkpoint for the eigen split
    - If trained on different split, can you please share it? 
    -  how many epochs did you train for?    
    - what image size did you train on?
    - which backbone did you use?
    - what other differences are there?
- Did you test only on the 135 test images or some other parts of the make3d dataset?
- Did you make additional adjustments for matching the images to ground truth depth maps while evaluation? If yes, could you please share those?
- Did you have any additional considerations while evaluating on this dataset?

Thanks

**Comment by mrharicot** [comment]
Hi,
To answer all of your questions at once: we did not do anything non standard and used the main checkpoint `mono_640x192` and the code provided in the other thread.
Have you modified the code in any way?

**Comment by Asherchi** [comment]
hello, can you shall you code that test on make3D, because I am also meeting that problem
