### ISSUE TITLE
cannot train raw kitti dataset on google colab

### ISSUE THREAD

**Issue by yamnaben** [nianticlabs/monodepth2#242]
hello, i hope you ar doing okay and thank you in advance for your help.
i have a problem with training raw kitti dataset in google colab, i have the data installed and coverted to jpg in google drive but it keeps time out while training, i installed cuda 9.1 in colab could you please help me.
thanks.

**Comment by mrharicot** [comment]
Hi,
It is impossible for us to help you if you don't provide more information.
I have very little experience in using both colab and google drive.
Did you modify the code in any way? Can you properly load images from google drive with colab outside our code?

**Comment by yamnaben** [comment]
Hello,
Thank you for your replay.
For the code i didn't  change it, when i train kitti data for mono it takes
a lot of times and google drive keep dismount, and i dont have problems
loading data from drive to colab.
