### ISSUE TITLE
Hi, i have some questions about depth map!

### ISSUE THREAD

**Issue by PangJian123** [nianticlabs/monodepth2#243]
The generated depth map has brighter color closer to the camera. Does it mean that the pixels closer to the camera have larger pixel values? If so，how to make the pixels farther from the camera larger than those near the camera?   Thank you very much!!!!!

**Comment by mrharicot** [comment]
Hi,
The color image generated by the script isn't the actual depth map but a visualization of it, or more precisely of the inverse depth.
You can change the colormap used or show depth instead.
https://github.com/nianticlabs/monodepth2/blob/101dd03f00e0d8e9bcd8a8d760f94bc2820f5549/test_simple.py#L133-L142

**Comment by PangJian123** [comment]
Hi, I try to convert the 2D array of depth map directly to grayscale image, But most areas of the generated image are black. I want to use depth map to generate fog. But the closer the object is to the camera, the higher the fog density. Are there any choices in the colormap that can achieve my purpose, or how to show depth directly? Thank you very much ！

**Comment by mdfirman** [comment]
I think here you would be much better off loading in the npy disparity file and processing that directly to make your desired colormap image.

**Comment by YQ-Yang** [comment]
> Hi, I try to convert the 2D array of depth map directly to grayscale image, But most areas of the generated image are black. I want to use depth map to generate fog. But the closer the object is to the camera, the higher the fog density. Are there any choices in the colormap that can achieve my purpose, or how to show depth directly? Thank you very much ！

hello,I have some question about the fog estimation.Do you find any good method to do this job?
