### ISSUE TITLE
Training on Custom Dataset produces inverted results

### ISSUE THREAD

**Issue by hamzarawal** [nianticlabs/monodepth2#245]
Hi,
I trained the model with mono settings for DTU dataset where there are multiple images of the same object from different views. Strangely the output of Depth Decoder (disparity) is depth but it should be inverse depth. 

Following is an example image with the predicted disparity:

![disp_prediction](https://drive.google.com/uc?export=view&id=1ycKOmI17G8fmOqY0KwEBE-XcScRgGXIe "Disparity Prediction")

As per the convention of Monodepth2, the near pixels should have been bright and far away pixels should have been dark. But exactly the opposite is happening here.

Note: I have changed the K matrix for the dataset. But I have not changed the min and max depth options.

**Comment by mrharicot** [comment]
Hi,
The DTU dataset is definitely a challenging one for a monocular depth prediction.
By the look of the disparity, I would say it did not manage to train properly.
Did you make sure to normalize the intrinsics matrix K ?

**Comment by hamzarawal** [comment]
Hi,
Yes, I normalized the K matrix. The problem is not there. I investigated the problem and concluded that the DTU dataset is not compatible with Monodepth2. Monodepth2 formulates the problem of depth using disparity equations which are ideally defined for a stereo case. DTU is a multi-view stereo (MVS) dataset and cannot be considered a stereo case and thus Monodepth2 fails here.
There is another major difference between DTU and KITTI. In KITTI, if we visually see the disparity between stereo pairs, we observe that near objects (cars, etc.) move more than far away objects (sky, etc.). It can be seen in the following gif

![image](https://drive.google.com/uc?export=view&id=1cDV0pMte-NPDF-Y1D4VJjriA-3jXxfPK)

In DTU however, the camera moves such that the nearer portions of the objects move relatively less than the faraway portions. Thus Monodepth2 has inverted behavior. It can be seen in the following gif

![image](https://drive.google.com/uc?export=view&id=1E7rJ8OeEH5mFQM9bJJGZxgauT9QcNxzG)

**Comment by mrharicot** [comment]
Hi,
monodepth2 does not make stereo assumptions other than in the stereo training mode.
If you were to train monodepth2 on MVS pairs and treat it as the mono mode, it _could_ work.
However predicting the pose and the depth reliably in such training scenario is going to be challenging problem and is likely an open research problem.
