### ISSUE TITLE
From Disparity Map to Point Cloud?

### ISSUE THREAD

**Issue by 10Exahertz** [nianticlabs/monodepth2#248]
I want to get the 3D point cloud. Since I am editing the output depth images given in the test_simple.py I would like to know how to input a depth image and get the 3D point cloud output. 

I tried the standard methods for projecting a depth map to 3D using the standard:
Z = ((baseline * f_x) / (d_im * p)) baseline is 0.1, focal length is 8 mm calibrated to pixels, and d_im is the depth 1-255
X = (j - centerX)*Z / f_x
Y = (i - centerY)*Z  / f_y

What I end up with however, is a depth map that looks great up close but explodes rather quickly.

![image](https://user-images.githubusercontent.com/34243218/93407679-ba0a2f80-f860-11ea-8373-5fc065f7b222.png)

![image](https://user-images.githubusercontent.com/34243218/93407755-dd34df00-f860-11ea-8282-6a503bebf093.png)

**Comment by mrharicot** [comment]
Hi,
From my understanding you seem to be using the colormapped image instead of the raw (inverse) depth output from the network:
https://github.com/nianticlabs/monodepth2/blob/101dd03f00e0d8e9bcd8a8d760f94bc2820f5549/test_simple.py#L134
We save the inverse depth as a numpy array ending in `_disp.npy`.

**Comment by 10Exahertz** [comment]
Okay I used the npy file, it works well. Is there any way I could use the depth maps generated (that you know of I can play around with the constants myself to match the npy data I suppose). I was wondering what the focal lengths used during training were?

Thanks for the help!

**Comment by mrharicot** [comment]
I am not sure I understand your question.
The `.npy` file contains the inverse depth (not metric, it is up to scale) you simply need to load it and invert it to get depth, no need for a focal parameter.

**Comment by 10Exahertz** [comment]
Isnt the focal parameter necessary to get the X and Y 3D location via:
X = x*Z / f_x
Y = y*Z/ f_y

Is this the correct method to translate the pixels to 3D?

**Comment by mrharicot** [comment]
Oh to go back to 3D, my bad! I missunderstood.
Then yes you can use the BackprojectDepth module:
https://github.com/nianticlabs/monodepth2/blob/101dd03f00e0d8e9bcd8a8d760f94bc2820f5549/layers.py#L139
```python
K = np.array([[focal / width, 0, 0.5, 0],
              [0, focal / height, 0.5, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]], dtype=np.float32)
inv_K = torch.from_numpy(np.linalg.pinv(K))[None]
backproject = BackprojectDepth(1, height, width)
point_cloud = backproject(depth, inv_K)
```
for kitti the original focal ratio is 
```python
K = np.array([[0.58, 0, 0.5, 0],
              [0, 1.92, 0.5, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1]], dtype=np.float32)
```
However if you test with a different dataset/image ratio, you might want to experiment with different focals.

I hope this helps!

**Comment by 10Exahertz** [comment]
Right so if the camera I am using has a focal length of 9mm (effective), then use that (in terms of pixels of course) instead of the trained ones?

**Comment by mrharicot** [comment]
It's unclear whether using the focal length of the test camera will result in the most accurate result given that the network was trained with a single focal (the kitti one). You might need to experiment to try and figure out what works.
