### ISSUE TITLE
Different intrinsics in stereo setting

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#25]
The current code takes same intrinsics for both cameras in stereo setting, but if we have different intrinsics the current code version not easy to adapt. This is because of the usage of the input dict, we have no clue which one of the images in the batch are left or right.  We have to hack in many places in the code to make it work. Is there an easy way to handle this issue?
https://github.com/nianticlabs/monodepth2/blob/2e0c2613b0f4c9b353a6c080df4a99f8c4f0ac48/datasets/mono_dataset.py#L159

**Comment by daniyar-niantic** [comment]
Hi @alwynmathew 

It is not very difficult to modify the code to handle different intrinsics for left and right view. The inputs dictionary will need to store intrinsics for the left and right cameras and specify which image is given to the network, whether it is from the left or the right camera. Then, you would need to add logic [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L355) to pass correct intrinsics to compute the loss. So, if the network sees left camera image, the inverse intrinsics passed to [`self.backproject_depth[scale]`](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L375) need to be the inverse intrinsics of the left camera and the intrinsics passed to [`self.project_3d[source_scale]`](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L377) need to be intrinsics of the right camera.

Best,

Daniyar

**Comment by mdfirman** [comment]
I agree with @daniyar-niantic , yes this sounds sensible. 

You could pass in the different intrinsics for each image via `inputs[('K', scale, frame_id)]` and `inputs[('inv_K', scale, frame_id)`.

Good luck.
