### ISSUE TITLE
ImageNet pretraining

### ISSUE THREAD

**Issue by DavidRecasens** [nianticlabs/monodepth2#250]
Hi!
First, congrats for your amazing work! It is quite elegant and effective. 

My question is related to the ImageNet pretraining that you have used to get the model's performance further. I am playing with custom datasets and I would like to try if ImageNet pretraining increases the quality of my results too. Therefore, I am wondering if you have trained the monodepth's encoder from scratch using ImageNet or, instead, imported the encoder already trained from another site. And about the decoder, is it initialized randomly? In the case you trained the encoder yourself, as train with ImageNet is not trivial, might you upload here the monodepth's models only trained with ImageNet? That would be really helpful.

Thank you! :)

**Comment by mrharicot** [comment]
Hi,
Thanks for the kind words!
We did not pretrain the models ourselves but use torchvision's pretrained models:
https://github.com/nianticlabs/monodepth2/blob/master/networks/resnet_encoder.py

I hope this helps!

**Comment by DavidRecasens** [comment]
Hi!
Thanks so much for your fast reply! 
Okay! I did not realize that lines. 

Greetings!
