### ISSUE TITLE
Custom training using monocular images and depth maps

### ISSUE THREAD

**Issue by purugupta99** [nianticlabs/monodepth2#251]
Hi, 
I have monocular RGB images and depth images for a scene and I would like to train the mono_model using these. I have seen in the readme that we can just inherit the MonoDataset class and write a custom dataloader like the kitti_dataset but I'm facing trouble as:-
- the kitti_dataset is using velodyne points but I need to use my depth maps corresponding to each image. Can you help me how I can modify the loader in this case?
- I'm not able to identify what exactly is frame_index variable used for because it is taken from the train_files.txt and there are random numbers written in it. Can you explain this please?

Thank you very much.

**Comment by mrharicot** [comment]
Hi,
You need to write the two functions `get_color` and `get_depth` which respectively load a single color image and the corresponding depth image.
https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/datasets/mono_dataset.py#L202-L209
The frame_index is just the index of a frame in a sequence. KITTI is made of multiple sequences with frames following each other in time, which are the random numbers you see in the train_files.txt file.
