### ISSUE TITLE
about train in other pytorch version

### ISSUE THREAD

**Issue by 791136190** [nianticlabs/monodepth2#254]
I modified a few places to make this project run on pytorch 1.4. However, it seems that loss cannot converge on version 1.4. Has anyone successfully trained on pytorch 1.4?

**Comment by mdfirman** [comment]
Thanks for your interest in keeping this up to date. What modifications did you have to make to get it to run on 1.4? 

Thanks

**Comment by mrharicot** [comment]
Closing this issue for now.
