### ISSUE TITLE
K

### ISSUE THREAD

**Issue by wangqiqi577** [nianticlabs/monodepth2#256]
s the K value in the code an internal reference of the camera? But it's not the same as what I found. Can you explain K to me？Thanks!

**Comment by mdfirman** [comment]
Yes, K is the intrinsics. But the K we use in the code:

- is the post-rectification intrinsics
- is normalised by dividing the top row by image width and the second row by image height
- is the average of the intrinsics for all the slightly different calibrations for the different KITTI runs.

I wonder if reading this issue thread might help:

https://github.com/nianticlabs/monodepth2/issues/43
