### ISSUE TITLE
pre-processing to remove static frames

### ISSUE THREAD

**Issue by jilner** [nianticlabs/monodepth2#257]
Hi, 
Thanks for the good job.
In section 4.1  you said "we follow Zhou et al.’s [76] pre-processing to remove static frames", where does the operation appear in the code?

**Comment by mdfirman** [comment]
The static frames are defined in their codebase in `static_frames.txt` found [here](https://github.com/tinghuiz/SfMLearner/tree/master/data/kitti).

They remove them as part of their dataloading [here](https://github.com/tinghuiz/SfMLearner/blob/master/data/kitti/kitti_raw_loader.py#L61). Instead, we remove them as a preprocessing operation to create our split txt files in the splits folder.

Hope this helps!

Thanks
