### ISSUE TITLE
Error in export_gt_depth.py for eigen_benchmark split

### ISSUE THREAD

**Issue by xianlopez** [nianticlabs/monodepth2#258]
Hi. First of all, congratulations for this great work and thanks for making the code publicly available.

Now, to the issue: When I run `python export_gt_depth.py --data_path kitti_data --split eigen_benchmark`, I get the following error:
```
Exporting ground truth depths for eigen_benchmark
Traceback (most recent call last):
  File "export_gt_depth.py", line 65, in <module>
    export_gt_depths_kitti()
  File "export_gt_depth.py", line 53, in export_gt_depths_kitti
    gt_depth = np.array(pil.open(gt_depth_path)).astype(np.float32) / 256
  File "/home/xian/anaconda3/envs/monodepth2/lib/python3.6/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'kitti_data/2011_09_26/2011_09_26_drive_0002_sync/proj_depth/groundtruth/image_02/0000000069.png'
```

I just don't have the folder `proj_depth` in `2011_09_26_drive_0002_sync`. Did anyone else encounter this same problem?

I followed the instructions in the readme, I have python 3.6.6, I have been able to train, and the command `python export_gt_depth.py --data_path kitti_data --split eigen` runs well.

**Comment by mdfirman** [comment]
For exporting the benchmark split ground truth you need the new improve benchmark depth files.

There are available from 
http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

Thanks

**Comment by khalilsarwari** [comment]
Was this resolved? For me data_depth_annotated.zip does not contain 2011_09_26_drive_0002_sync along with some other files.
