### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by petroskey** [nianticlabs/monodepth2#26]
Hi, thank you always for your support.
It seems that monodepth2 trains KITTI data with Eigen split, but I would like to train with other dataset.
The training part of your code seems to depend on KITTI format and the Eigen split algorithm.
How can I train with general dataset e.g. just a stream of frames.

Thank you in advance.

**Comment by daniyar-niantic** [comment]
Hi @petroskey 

It is an active research problem of extending self-supervised monocular depth estimation methods to the regime of training from a collection of monocular videos, due to ambiguities in camera pose, intrinsics, moving objects, etc. 

Without specifics in your question, I don't think I can come up with a specific answer. Do you want to train from mono-video? Stereo video? Are you using single camera model in all sequences? Are you sequences calibrated? Do you want to train on different split of KITTI? Do you want to train on Cityscapes datasets? Which split of Cityscapes dataset?..

**Comment by mdfirman** [comment]
Hi @petroskey , you should be able to train on arbitrary datasets by creating a new dataset subclassing from [MonoDataset](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L28). You will have to write your own split files (and place them in e.g. `splits/my_custom_split`), and modify the code in a few places. Then you can train with:
```
python train.py --dataset my_custom_dataset --data_path path/to/data --split my_custom_split
```

**Comment by petroskey** [comment]
Hi @daniyar-niantic and @mdfirman ,
Thank you for your kind and quick response.

Thank you @daniyar-niantic for your insightful suggestion.
I would like to train a mono-video, since actually monodepth2 seems to be quite a rare algorithm that learn depth from a mono-video. Actually, I don't understand well how KITTI is split in your codes and probably posted a wired question...

Thank you @mdfirman for your detailed reply and the past help about my closed post.
I got your suggestion and will try to create my custom dataset class from MonoDataset instead of KittiDataset. I also realized that I should first understand how KITTI is split.

Thank you very much for two your help:)

**Comment by mdfirman** [comment]
Thanks for your kind feedback here!

Yes how the KITTI is split takes a little understanding. The split files, importantly, only point towards images for which +1 and -1 frames are available. So images at the start and end of sequences are not included in the split .txt files.

Then the dataloader classes have the role of loading in the frame specified in that line in the txt file, together with the +1 frame and the -1 frame.

Thanks.

**Comment by petroskey** [comment]
Thank you again for your kind reply and explanation about splitting, @mdfirman ,

I got the spirit of loading KITTI in your code.
Based on your advice, I will read them again and try loading data.

Thank you very much:)

**Comment by albertchristianto** [comment]
Hello, this is a great repository.

Have you use Cityscapes dataset for training your network?
if yes, can you share the procedure to do it with your code?
thank you very much. 

best regards,
Albert christianto

**Comment by petroskey** [comment]
Hello, @albertchristianto.
I have not tried yet but would like to test it. 
I suppose that you are asking the repository masters, but my response is for just in case:)
Thank you.

**Comment by WinstonDeng** [comment]
@mdfirman Hi, I would like to train on Human Dataset (e.g. H3.6M, or Videos from Youtube), but was confused about how to build class Dataset and split file for monodepth2 code. Could you give me some advice?
