### ISSUE TITLE
Question regarding a multiplication in the Pose Decoder part

### ISSUE THREAD

**Issue by hamidrezafazlali** [nianticlabs/monodepth2#260]
Hello,

Currently, I am using the monodepth2 code and I realized something inside the code that is not mentioned anywhere else. 
Actually in the line 49 of the "pose_decoder.py" the output of the pose decoder is multiplied by 0.01. 
I want to know is there any specific reason for that? Because it will reduce the output results of the pose decoder significantly.

I really appreciate if you consider my question.

Thanks,

**Comment by mrharicot** [comment]
Hi,
The 0.01 scaling originated from Zhou17's implementation and we ourselves observed that it led to a more stable early convergence.

**Comment by hamidrezafazlali** [comment]
Thank you so much @mrharicot for the response. 
I asked this because I am actually using this pose network but with different depth estimation network and this 0.01 multiplication leads to very small values that eventually makes the tranformation matrix (T) to become identity. Therefore, instead of reonstructing from the previous or next frame, it actually copies those frames.

**Comment by mrharicot** [comment]
The scale is just here to help at the beginning of training. Another (cleaner) way would be to scale the weights once before training.
Once training has started the scale shouldn't matter as it is a linear operation and the network can learn to ignore it by having larger input values.
That being said it's still not a very satisfying way of dealing with stability so feel free to experiment with other values or maybe use normalization of some sort.
I hope this helps!

**Comment by hamidrezafazlali** [comment]
Thank you so much @mrharicot .
