### ISSUE TITLE
Loss don't drop when train on custom dataset

### ISSUE THREAD

**Issue by blacksino** [nianticlabs/monodepth2#261]
Hi,

when I train a new model on my custom dataset, the loss hardly drops through training procedure and the loss is numerically low ,which is about 0.1.

my normalized K is [[0.875,0,0.5,0],
                                 [0,1.1,0.5,0],
                                 [0,0,1,0],
                                 [0,0,0,1]]
original resolution (w1280,h1024)
and set resolution(w640,h512)

camara motion is relatively small because i am using a endoscope dataset.

This is my  custom dataset code:https://github.com/blacksino/mono

**Comment by mrharicot** [comment]
Hi,
It is difficult to know what is going wrong without looking at the data.
How much data do you have? Is it stereo?
Would you mind sharing either a stereo pair or a temporal triplet?

**Comment by blacksino** [comment]
We have about 20000 stereo image pairs ,we only use all the left images to train mono depth estimation,here are some examples.
![Left_Image000065](https://user-images.githubusercontent.com/44363764/96978392-e5172b80-1550-11eb-8450-2a0c3e5085b0.png)
![Uploading Left_Image000066.png…]()

**Comment by mrharicot** [comment]
wow these are pretty graphic!
There is barely any motion between the temporal frames, it would be very difficult to train monodepth on these.
Why not use the stereo images instead and train monodepth in stereo mode?
