### ISSUE TITLE
the compared methods

### ISSUE THREAD

**Issue by jilner** [nianticlabs/monodepth2#262]
Thanks for the good job!
Are the methods used to participate in the comparison in the paper retrained or using the original author's parameters?  If they are retrained, could you share the source code or the pretrained models?

**Comment by mdfirman** [comment]
All the comparison methods are taken from the original authors' papers – you can follow up the references to find these baselines. 

We never retrained any competing models, we just used the numbers from their papers.

**Comment by mrharicot** [comment]
Michael is right! I will add that for the new benchmark and for single-scale experiments we used their pretrained models or exported outputs to run the evaluation (when available).
