### ISSUE TITLE
Reproduce with cudnn

### ISSUE THREAD

**Issue by scott89** [nianticlabs/monodepth2#263]
Hi,

Really amazing work! I have a question regarding the cudnn version. I can reproduce the reported results with cudnn disabled. However, with cudnn acceleration (Pytorch 0.4.1+ cudnn 7.1.2) for training, the final results (abs_rel=0.118, a1=0.873) are always slightly worse than those reported in the paper. I'm wondering whether you have used cudnn for training in the experiments? If so, which version is used?

Thanks!

**Comment by mrharicot** [comment]
Hi,
That's a surprising result!
As far as I know we've been using cudnn for all our experiments.
How did you disable it?

**Comment by scott89** [comment]
I disable cudnn with `torch.backends.cudnn.enabled = False`
Is your pytorch built from source? Or installed with conda? Which cudnn is used in the experiments?
Thanks!

**Comment by mrharicot** [comment]
Very strange! What system do you have? (python version, cuda version and gpu)
As we state in the readme we simply install all the dependencies using conda and do not build anything from source.

I am not entirely sure which cudnn was used for the experiments, we state cuda 9.1 so I would guess 7.1.3 or earlier.
I need to point out that we ran experiments on multiple machines with different setups and never noticed a difference in results.

**Comment by scott89** [comment]
I have tested on a ubuntu18.04 system with one TITAN RTX gpu under the following two conda environments:

1. python 3.6.6, cuda 9.1, pytorch 0.4.1, cudnn 7.1.2 
2. python 3.7.6, cuda 10.1, pytorch 1.5.0, cudnn 7.6.3

I can only reproduce the results using setting 1 with cudnn disabled. Under setting 2 without cudnn, the best result I have achieved is abs_ref=0.116, a1=0.875

**Comment by mrharicot** [comment]
Hmmm that is very strange!
Just to make sure, you are using the `mono_640x192` model?
Can you share the command line you are running?
Finally did you convert the images to jpeg? The model was trained with jpeg images and testing with pngs results in a different output.

**Comment by scott89** [comment]
The command line I use is `python train.py` with default options at 640x192 resolution. All images are converted to jpeg format. The model is trained and tested with jpeg input. Could this be a reason? I find the option to load png images during evaluation is disabled as mentioned in  #166 
Thanks!

**Comment by mrharicot** [comment]
Looks like I misunderstood your initial issue, I thought you couldn't reproduce the evaluation using pretrained weights.
If I understand correctly you can only reproduce the reported results if you disable cudnn with cuda 9, in this case how close are the final results to the pretrained weights?
Is this reliable? In the past I have chased regressions for days which were only due to random chance, could it be the case here?
It could also be a bug with cudnn and this gpu only.
