### ISSUE TITLE
To observe further distances

### ISSUE THREAD

**Issue by naruto221** [nianticlabs/monodepth2#265]
![IMG_7313(20201021-213555)](https://user-images.githubusercontent.com/73264035/96808632-c713d300-144b-11eb-8eb4-6bd1080a3b30.JPG)
Hey, thanks for your outstanding work!
Now I want to use this network to predict further distances. We now want to observe the position of the ship's distance camera from the shore in the bridge area. At present, the estimated distance of the ship from us is about 200 meters. The size of the ship is about 50 meters to 100 meters. I want to do stereo training, the camera uses a longer focal length and a larger baseline distance（maybe 1m to 1.5m). 
I have a few questions: 
1. The river side of the ship to shoot less occlusion, training will be better? 
2. Using a longer focal length and a larger baseline distance camera to produce the Dataset, with monodepth2 training, do you think you can predict such a distance?

**Comment by mrharicot** [comment]
Hi,
1. I think your best chance is to capture from a higher position so it is easier to see the water and the distance between ships.
2. If the camera is static it might be an issue. Monocular depth models are usually trained on a lot of _varied_ data, if the camera is always in the same location it might cause issues to train.

**Comment by naruto221** [comment]
Thank you for your response！
My camera is located on the shore, it is unlikely to be as mobile as it would be for a Kitti Dataset, so would it be possible for me to film from different locations along the river to create a Dataset ,for example, shoot at four or five locations？and can a dataset training network with long focal length and long baseline the distance break through 100m to reach the predicted depth of 200m?

**Comment by mdfirman** [comment]
I think going above 100m is outside the scope of this project. It's an interesting problem, but not one that we can guarantee anything for with this code base.

Good luck!
