### ISSUE TITLE
moving objects

### ISSUE THREAD

**Issue by W1Fl** [nianticlabs/monodepth2#267]
Hi,

In my experiments, automask has solved the problem of the scene becoming a bad sample when the camera is still. However, I am concerned about whether Mododepth2 can handle the data well when objects in the scene are moving at other speeds or in other directions during training.

**Comment by mrharicot** [comment]
monodepth2 in mono mode (without stereo input) doesn't handle moving objects properly other than ignoring them.
It is still an active research topic.
