### ISSUE TITLE
Regarding the absolute distance

### ISSUE THREAD

**Issue by y-fuku-local** [nianticlabs/monodepth2#268]
This model could relative distance between object.
However, it is not possible to predict absolute distance, right?

**Comment by mdfirman** [comment]
Thanks for your interest. The models trained with stereo supervision can predict depths in absolute real-world scale. But models trained with monocular videos can only predict relative distances (or distances 'up to scale').

**Comment by y-fuku-local** [comment]
Thank you your response.
I understood.
