### ISSUE TITLE
Can I get the real depth value converted from the plasma image?

### ISSUE THREAD

**Issue by Taeyoung96** [nianticlabs/monodepth2#270]
Hi! I'm really thankful to give your great code.  
I'm actually want to get real depth value with my depth prediction image.  

For example, with your pre-trained model, I put this RGB image.  

This RGB image is from `rgbd_dataset_freiburg1_xyz`.  
<img src="https://user-images.githubusercontent.com/41863759/98771270-631b7380-2427-11eb-8d58-364e659198e3.png" alt="1305031102 175304" width="320"/>  

And I can get a depth prediction image.  
<img src="https://user-images.githubusercontent.com/41863759/98771567-1a17ef00-2428-11eb-855a-2d5a024b0f93.png" alt="0_depth" width="320"/>  

I want to get real depth value like this.  
<img src="https://user-images.githubusercontent.com/41863759/98771723-71b65a80-2428-11eb-8c1e-def6dd78d9eb.png" alt="1305031102 160407" width="320"/>  

I would like to convert it so that it can have a similar value even if it doesn't have an exact depth value.  

Are there any formulas or codes that can be applied here?  

Thanks.

**Comment by mrharicot** [comment]
Hi,

The plasma image is just for visualization, if you want the raw float32 depth output from the network you can find it in the .npy file of the same name which is outputted in the same folder.

**Comment by Taeyoung96** [comment]
I got it. Thanks for your reply.
