### ISSUE TITLE
A question about the scale factor of stereo 

### ISSUE THREAD

**Issue by ZhongkaiZhou** [nianticlabs/monodepth2#272]
Thank you for such an excellent job！I have a question: Why is the depth value obtained with a baseline of 0.1 and the depth value obtained with a baseline of 0.54 have a relationship of 5.4 times?

**Comment by mrharicot** [comment]
Hi,

This comes from the main equation in stereo: `depth = focal * baseline / disparity`.
Hence if you scale the baseline by a scalar the depth will be scaled by the same amount.

I hope this helps!

**Comment by ZhongkaiZhou** [comment]
Thank you for your patient answer. In https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/evaluate_depth.py#L205,
the disparity is only multiplied by the factor 5.4( In order to restore the 0.54 baseline, you multiply it by 5.4), and not multiplied by the focal. Can this operation get the real depth?
