### ISSUE TITLE
How is the disparity from monodepth2 and the actual disparity mapped?

### ISSUE THREAD

**Issue by kimsunkyung** [nianticlabs/monodepth2#273]
For example, If the disparity result from monodepth2 is 0.13 in [640,192], then what is its actual disparity?

**Comment by mrharicot** [comment]
Hi,

monodepth2's internal representation is inverse depth, we do not use disparity (despite the confusing name `disp` in the code, which typically means inverse depth).

You can however compute the disparity in stereo training mode using the following formula:
`disparity = focal * baseline / depth`

Where the baseline is set to 0.1 units and the focal can be obtained by looking at the intrinsics matrix K which has a normalized focal of 0.58 of the x axis, which for a 640x192 images gives a focal of 371.2 pixels.

Please note that you need to use the proper scaled depth (between 0.1 and 100) which in this case is `1 / scaled_disp`:
https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/test_simple.py#L133

I hope this helps!

**Comment by kimsunkyung** [comment]
Thank you!

**Comment by huynhbaobk** [comment]
@mrharicot mr Hi, could you explain why you choose scaled depth (between 0.1 and 100)?
