### ISSUE TITLE
Partial Depth information

### ISSUE THREAD

**Issue by amanwalia92** [nianticlabs/monodepth2#275]
Hey, thanks for your outstanding work!

I am looking to train this model on a monocular sequence where not all frames have depth information. The data is arranged in the format of the frame's previous and next capture with respect to the original frame as :
```
Current frames (t = 0) [LiDAR Available]
 - frame A
 - frame B
 - frame C 
and so on 
```
```
Previous frames (t = -1) [ No LiDAR]
 - frame A
 - frame B
 - frame C 
and so on 
```
```
Next frames (t = +1) [ No LiDAR]
 - frame A
 - frame B
 - frame C 
and so on 
```
Just to make this simpler to understand `Current frames/frame A` has `Previous frames/frame A` as the preceding frame in the capture and `Next frames/frame A` as the succeeding frame. Also frame A, B, and C have no suitable temporal linkage in between them.

The problem is that `Previous Frames` and `Next Frames` have no depth information whereas `Current frames` have LiDAR information available.  I am curious if the provided code can be used for training on this kind of data since I can modify the data loader to load the triplet temporal capture but can only provide depth data for only one frame at t = 0.

**Comment by mdfirman** [comment]
Hi, thanks for your interest! Yes I would expect that this repo would be able to do what you want. I would consider adding a loss encouraging the predicted depth for the frame at t=0 to match the LiDAR depth at t=0. 

I would expect that would help to encourage the network to use the lidar at training time.

The good thing about neural network losses is you are able to selectively apply them only to the training examples where suitable data exists.

Good luck with this project! Thanks
