### ISSUE TITLE
train model using images taken by static cameras

### ISSUE THREAD

**Issue by yuyaya-foifoi** [nianticlabs/monodepth2#276]
Hello. @mrharicot  Thank you for sharing your great research findings.

I am thinking of using images taken from static cameras to calculate the depth.
Do you think there is a possibility to avoid  [issue#265](https://github.com/nianticlabs/monodepth2/issues/265#issuecomment-714187791) or [issue#261](https://github.com/nianticlabs/monodepth2/issues/261#issuecomment-716041222) even though I use images taken by the static cameras as a training dataset? 
How about if I take images while moving the angle or zooming those static cameras?

Any opinion will be appreciated.
Thank you.

**Comment by mrharicot** [comment]
Hi,

If the camera is static you will need (mostly unique) stereo pairs to train monodepth2.
do predict depth from stereo/mvs you need different centers of projection for each image, that is to say the position of the cameras, the rotation does not induce depth effects.

**Comment by yuyaya-foifoi** [comment]
Thank you for your reply.

Couldn't it be interpreted in a way that images taken at different zoom rates have different projection centers?

**Comment by naruto221** [comment]
> Thank you for your reply.
> 
> Couldn't it be interpreted in a way that images taken at different zoom rates have different projection centers?

Do you  use mono model to train monodepth2 rather than stereo pairs to train?

**Comment by mrharicot** [comment]
> Couldn't it be interpreted in a way that images taken at different zoom rates have different projection centers?

No. Changing the zoom only modifies the intrinsic matrix, not the extrinsics.

**Comment by yuyaya-foifoi** [comment]
@naruto221 
No, I haven't trained the model yet.
I was looking to see if I could use this algorithm with a single camera first because due to the nature of the project, it's hard to install two cameras. 
Because first, we need local government permission to install a second camera and will take time. Second, budget-wise.

@mrharicot 
Thank you very much. I understand.
