### ISSUE TITLE
Training on a dataset with different depth ranges.

### ISSUE THREAD

**Issue by Beniko95J** [nianticlabs/monodepth2#279]
Hi, I want to train monodepth2 on EuRoC dataset, which includes scenes of Machine Hall and Vicon Room and I find that images of these scenes have different depth ranges. I notice that the disp_to_depth function in monodepth2 normalizes the depth to a specific range rather than just calculates 1/disp. Will this be a problem in training on a dataset that includes images with different depth ranges?

Best regards

**Comment by Beniko95J** [comment]
To be more specific, will this cause the problem that the depth estimation may have different scales in the same scene, and the odometry results from monodepth2 (frame-to-frame estimations) will also be bad due to inconsistent scales?

**Comment by mrharicot** [comment]
Hi,
monodepth2 without modifications is unlikely to be able to train on the EuRoC dataset, however you can have a look at this ICCV paper where they did so successfully.
https://openaccess.thecvf.com/content_ICCV_2019/html/Gordon_Depth_From_Videos_in_the_Wild_Unsupervised_Monocular_Depth_Learning_ICCV_2019_paper.html
