### ISSUE TITLE
Is fly-out mask being computed?

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#28]
I was wondering if you were computing a fly-out mask to mask out pixels that "fly out" when computing the re-projection loss. I didn't notice it in your paper of code.

**Comment by kwea123** [comment]
No, see #20.

**Comment by mdfirman** [comment]
Thanks @kwea123 , yes that is correct. We don't mask the fly out, but we use `border_mode='edge'` instead. Thanks.
