### ISSUE TITLE
Regarding metric estimation of depth

### ISSUE THREAD

**Issue by vineeth2309** [nianticlabs/monodepth2#280]
Hi,
Does the model returned depth have any metric relation? Also can any of the different methods used for training the mode(mono,stereo,mono+stereo) all output the same depth?

**Comment by mdfirman** [comment]
In the stereo and mono+stereo trained models, yes the network output can be transformed to be an estimate of the depth in real-world units (metres). See [this thread](https://github.com/nianticlabs/monodepth2/issues/47) for more info on how to make this conversion.

The mono-trained model, though only outputs depth 'up-to-scale', i.e. not in real world units.
