### ISSUE TITLE
about automasking apartment

### ISSUE THREAD

**Issue by ustbCXK** [nianticlabs/monodepth2#281]
Hi, thank you very much for your excellent work and bring me a lot of knowledge. With regard to the automaking section, I have some questions about the code part. As shown in the figure, according to my understanding, （idxs ） here should be the minimum mask. But here we use idxs and identity_ reprojection_ loss.shape [1] - 1) by comparison, I understand the （identity_ reprojection_ loss.shape [1]） should be two cases, 1 or the number of (- 1,1, s) (mono + stereo). I want to know, what is the purpose of this judgment?

**Comment by ustbCXK** [comment]
Well, `sorry，maybe` I didn't make it clear, identity_ reprojection_  loss.shape  [1] It may be 1 (stereo), 2 (mono), 3 (mono + stereo). At the same time, I attached the code.---trainer.py---compute_losses()--
`if not self.opt.disable_automasking:
                outputs["identity_selection/{}".format(scale)] = (
                    idxs > identity_reprojection_loss.shape[1] - 1).float()
`

**Comment by mrharicot** [comment]
Hi,

The -1 comes from the fact that `idx` are indices from `combined` which is larger than `identity_reprojection_loss` by 1 so we need to correct for it in order to compare the values.

I hope this helps!
