### ISSUE TITLE
where is the distance information?

### ISSUE THREAD

**Issue by yunxiaozimeng** [nianticlabs/monodepth2#282]
I am new about this repo and I just want to get the distances of any pixels in an image(like 0.9m, or 
 0.9inches....etc), who can tell me where  I can find them?

**Comment by ustbCXK** [comment]
To my understanding, this can not restore the absolute scale, but a relative scale.The program has an output ["depth"] ,that
is a depth map, you can use the author's weight to get each pixel value and try to read it.

**Comment by yunxiaozimeng** [comment]
> To my understanding, this can not restore the absolute scale, but a relative scale.The program has an output ["depth"] ,that
> is a depth map, you can use the author's weight to get each pixel value and try to read it.
Oh ,that is like! thank you very much!

**Comment by yunxiaozimeng** [comment]
> To my understanding, this can not restore the absolute scale, but a relative scale.The program has an output ["depth"] ,that
> is a depth map, you can use the author's weight to get each pixel value and try to read it.

I understand，thank you!^_^

**Comment by Varat7v2** [comment]
@yunxiaozimeng Did you get the actual human-readable distances? How can I get it? Thanks in advance.
