### ISSUE TITLE
Different intrinsics in a single training set

### ISSUE THREAD

**Issue by FiniteObliviate** [nianticlabs/monodepth2#283]
Hi, thanks for your sharing your great work.

I have a custom dataset that includes several fractions with different camera intrinsics. While I found that the intrinsics was set only once in the kitti_  dataset.py. So, I wonder is there a way to specify different intrinsics for different images during one training?

Thank you!

**Comment by mrharicot** [comment]
Hi,
To handle this case you will have to modify the parent class to use a member function depending on the sample whenever you need to return the intrinsics, similar to https://github.com/nianticlabs/monodepth2/issues/278.

I hope this helps!

**Comment by FiniteObliviate** [comment]
Thank you very much for such prompy reply!
By the way, I noticed that the camera intrinsics in KITTI were also slightly different. So, I guess you still use a single camera intrinsics matrix because the differences are too small to affect the results?
