### ISSUE TITLE
Question regarding the pose network

### ISSUE THREAD

**Issue by vineeth2309** [nianticlabs/monodepth2#285]
According to the paper, the pose network calculates the pose to transform T̂ n→n−1, which would mean we compute the transform between (0 -> -1) and (+1 -> 0). In the function compute_poses, we invert the transform for the (0 -> -1) making it (-1 -> 0). 
We use these transformations in the generate_images_pred function, to create the transformed images to be used in the reconstruction loss. Since we have the depth map only for image 0, we ideally would only be able to transform image (0 -> -1) and image(0 -> +1). However we computed the poses to transform images +1 and -1 to image 0.

I wanted to clarify if my understanding of what was happening is wrong, or there is a mistake in the code.

**Comment by vineeth2309** [comment]
Just needed a clarification if my understanding of what is happening is correct:
![Inverse Warping](https://user-images.githubusercontent.com/19423039/101865290-de458600-3b9b-11eb-97ff-3856f84829f1.png)

For example, in this case we start with the depth image at time frame 0, and proceed to transform it to time frame +1 using the pose from the model. This gives us the transformed version of frame 0, that is further normalized between [-1,1] to form a grid. Now this would tell us for example that point (1,1) on the image at time 0, maps to (1.2,1.2) on image at time +1. We then use bilinear interpolation to sample from the actual image at time +1 to obtain the color for the pixel (1.2,1.2). Since we know that the point (1,1) on image at time 0 corresponds to point (1.2,1.2) on image at time +1, we simply replace the colour of the pixel (1,1) of image 0 with the colour we obtained after bilinear interpolation from image at time +1. This would lead to us inverse mapping image +1 to image 0.

**Comment by ustbCXK** [comment]
> `if f_i < 0:
                    pose_inputs = [pose_feats[f_i],pose_feats[0]]
                else:
                    pose_inputs = [pose_feats[0],pose_feats[f_i]]`
I've been watching this network recently.In my opinion, what we mean here is to calculate the pose of [- 1 - > 0] and [0 - > 1].After the subsequent [- 1 - > 0] is flipped, the pose of [0 - > - 1] is obtained.

**Comment by mdfirman** [comment]
Thanks for your interest in our project!

You say:

>  Since we have the depth map only for image 0, we ideally would only be able to transform image (0 -> -1) and image(0 -> +1). 

Here I think I disagree with you. As @vineeth2309 point's out, we use backwards warping to synthesise our images. So we use the depth map for image 0 to transform the pixels from image -1 to the viewpoint of image 0.  In fact, doing this backwards warping is much easier than doing the reverse forward warping.

[See this thread](https://github.com/nianticlabs/monodepth2/issues/87) for more discussion on this same topic.

Thanks!
