### ISSUE TITLE
Why do you add random numbers when computing identity_reprojection_loss？

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#286]
![image](https://user-images.githubusercontent.com/31730585/101929357-b2fd7e00-3c11-11eb-80fe-96c59989672a.png)
What‘s the meaning of "break ties" ?
Thank you!

**Comment by mdfirman** [comment]
This is implemented to cover the case where the identity loss is exactly the same as the standard reprojection loss – which of these should have loss backpropogated to it? By adding a tiny random number we ensure that approximately 50% of the time the loss is backpropogated to the standard reprojection loss (and goes through the depth+pose networks), and 50% of the time goes to the identity reprojection image (and effectively is nulled).

In practice we found that adding this random number doesn't make any difference to scores, and so isn't necessary – it's left in from an earlier code version for posterity.

**Comment by Rashfu** [comment]
> This is implemented to cover the case where the identity loss is exactly the same as the standard reprojection loss – which of these should have loss backpropogated to it? By adding a tiny random number we ensure that approximately 50% of the time the loss is backpropogated to the standard reprojection loss (and goes through the depth+pose networks), and 50% of the time goes to the identity reprojection image (and effectively is nulled).
> 
> In practice we found that adding this random number doesn't make any difference to scores, and so isn't necessary – it's left in from an earlier code version for posterity.

Hi, @mdfirman :
Do you mean the random implementation seldom works？
Because I found that the random time cost usually accounts for more than 50% of the function `process_batch` [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L205).
