### ISSUE TITLE
Do use “ToTensor + Normalize” or only "ToTensor" ?

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#288]
Usually when we train a model, we use
 `  my_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.45, 0.45, 0.45],
                                            std=[0.225, 0.225, 0.225])
    ])
`
But I found that you only use `transforms.ToTensor()` in mono_dataset.py, why don't you use `transforms.Normalize()` ?
Thank you!

**Comment by mdfirman** [comment]
In our code we roll this normalisation into the forward pass of the resnet [here](https://github.com/nianticlabs/monodepth2/blob/master/networks/resnet_encoder.py#L89).

So it's still there, it's just done on the GPU instead of the CPU.
