### ISSUE TITLE
Translation vector for flipped image

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#29]
Does the translation get affected when an image is flipped? You have changed `tx` here:
https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L194

But instead, for flipped image principal point changes as in here:
https://github.com/ClementPinard/SfmLearner-Pytorch/blob/0caec9ed0f83cb65ba20678a805e501439d2bc25/custom_transforms.py#L55

**Comment by daniyar-niantic** [comment]
Hi @alwynmathew ,

In the outlined code of `mono_dataset`, it is not principal point of the intrinsics matrix that is flipped, but the translation vector between cameras of the extrinsics matrix.

**Comment by mdfirman** [comment]
As Daniyar says – we flip the translation, but we don't change the intrinsics. We do not flip the principal point as we assume the principal point is in the centre of the image (therefore we assume symmetric cameras). If we used intrinsics where the principal point was not centred then we would also have to flip the intrinsics.

**Comment by alwynmathew** [comment]
@mdfirman thanks for clearing up about intrinsics. As the images are rectified, principal point(intrinsics) will be unchanged and rotation(extrinsic) will be identity. But how does the translation vary when you flip a rectified image?

**Comment by mdfirman** [comment]
When we flip a rectified image, the translation's x-component is negated, as you point out.

Because the image is rectified, we don't have to worry about the translation's y and z components (both of which are zero), nor do we have to worry about the camera's rotation.
