### ISSUE TITLE
Potential bug concerning consistency between pose and depth estimations

### ISSUE THREAD

**Issue by theRealNicktchopper** [nianticlabs/monodepth2#290]
Hi,

firstly, thanks for the great work. I'm currently setting up my own framework and also made use of your implementation. While doing that I think to have found a potential error, that I'd like to discuss with you:

In the method 'generate_images_pred' in trainer.py you use disp_to_depth to generate the depth map, which is forced to take a value in the range of min_depth to max_depth (0.1 to 100). For the image warping we use both this scaled depth map and the unscaled poses. I'm aware that the scale of the scene cannot be estimated when trained in a fully unsupervised manner. However, for the image warping both the predicted poses and the depth map is used. So once the pose is predicted, the scale is set to a specific value that is unknown and the depth predictions will fit that scale as they are trained together. But a later rescaling of these depths (with disp_to_depth) would cause the depth map to have a different scale than the poses. So the poses would either have to be adjusted too or the scaling of the depth map should have been left out. Otherwise, the performance of the training will get deteriorated as the image warping won't yield completely correct results so also corrupting the photometric loss. Am i missing something or would you agree to that?

The disp_to_depth might still be necessary to keep the estimated depths in an acceptable range and to be able to train (especially in the beginning), yet I think that this should've been solved differently.

It would be great to have your opinion on that...

**Comment by theRealNicktchopper** [comment]
Ok, I just spend some more hours dealing with that and now I see that the network output is neither the inverse depth nor the depth but the raw sigmoid output in the range 0-1 which then is transformed to (unscaled) depth values constrained to be in the range 0.1 and 100. I still stick to my claim that you can't scale the depth without scaling the pose but you obviously didn't do that :) So, I think this issue is resolved and can be closed...

**Comment by mrharicot** [comment]
Yep! The poses only ever interact with the scaled depth (between 0.1 and 100) so they don't need to be adjusted at any point.
