### ISSUE TITLE
the ground truth depth map used in evaluation

### ISSUE THREAD

**Issue by xjturobocon** [nianticlabs/monodepth2#292]
Hey, I found you used the gt depth as follow in evaluation:
 `    if vel_depth:
        velo_pts_im[:, 2] = velo[:, 0]`
I understand it that the depth is in velodyne laserscanner coordinate. However, you use the predicted depth to warp the target frame to source frame, so the predicted depth is in target camera coordinate.

I think the gt depth and the predicted depth is not in the same coodinate(maybe need rotation and translation to align), so is it proper to use such gt depth to evaluate the one predicted? 

look forward to your reply, thanks!

**Comment by mrharicot** [comment]
Hi,

This is a known problem which dates back from Eigen's evaluation.
See issue https://github.com/nianticlabs/monodepth2/issues/274 for more details.

I hope this helps!
