### ISSUE TITLE
Question about bn in the decoder

### ISSUE THREAD

**Issue by LeoCho1learning** [nianticlabs/monodepth2#294]
Hi, 

Thanks for your great work!

I'm trying to modify monodpeth2 to work on my custom data with int8 quantization. And I added batch normalization in the depth decoder, but it gave much worse results compare to original network. Could you give me some advices on this?

Thanks

**Comment by kshashankrao** [comment]
Did you manage to quantize both the encoder and decoder ? If yes, what was the dip in the performance ?
