### ISSUE TITLE
the scale factor of stereo 

### ISSUE THREAD

**Issue by ZhongkaiZhou** [nianticlabs/monodepth2#295]
In stereo evaluation = focal * baseline / disparity.
But in         https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/evaluate_depth.py#L205

the disparity is only multiplied by the factor 5.4( In order to restore the 0.54 baseline, you multiply it by 5.4), and not multiplied by the focal. Can this operation get the real depth?

**Comment by mrharicot** [comment]
Hi,

monodepth2 does not use disparity, but inverse depth, as we perform a full 3d projection between views using transformation matrices. In stereo mode we force this transformation matrix to be translation only along x by 0.1 units.
0.1 was chosen to be agnostic to the actual baseline (works for both cityscapes and kitti for instance) and as it was more stable for training.
The final scale factor is only here to correct it and turn the units into meters.

I hope this helps!

**Comment by ZhongkaiZhou** [comment]
Thank you for your answer! I am new to the domain，sorry.  I also have difficulty in understanding the last sentence. Why can the predicted depth be multiplied by this scale factor to get a depth  in meters in stereo mode?

**Comment by mrharicot** [comment]
In the case of stereo training we do not predict the pose but hardcode it to be a translation along x of 0.1.
In the case of kitti we know the translation is 0.54m, as the relationship between depth and baseline (length of translation) is linear we can simply scale the output of the network by 5.4.

**Comment by ZhongkaiZhou** [comment]
Thank you very much!

**Comment by CaptainEven** [comment]
@mrharicot Hi, thanks for your kind and detailed explanation! BTW,  Where is 0.1m reflected in the code?

**Comment by anthonygofin** [comment]
> @mrharicot Hi, thanks for your kind and detailed explanation! BTW, Where is 0.1m reflected in the code?

Hi CaptainEven. Did you find the 0.1m in the code ? I am also looking for it but I can not find it.

**Comment by YuhengZhi** [comment]
@CaptainEven @anthonygofin Please see [this line](https://github.com/nianticlabs/monodepth2/blob/b676244e5a1ca55564eb5d16ab521a48f823af31/datasets/mono_dataset.py#L196), just in case you have not found it already.
