### ISSUE TITLE
Why do you clamp SSIM loss to (0,1) ?

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#296]
https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/layers.py#L248
Hi, I'm confused because it seems that there is no need to clamp it to (0,1).  
If SSIM natuarlly ranges from 0 to 1, then (1-SSIM)/2 must range from 0 to 1/2 . Or doesn't it naturally range from 0 to 1/2 ？

**Comment by mrharicot** [comment]
Hi,

SSIM is actually in the [-1, 1] range. 
The clamping is here to avoid possible overflow in case `SSIM_d` becomes too small resulting in precision issues.

Hope this helps!
