### ISSUE TITLE
Effect of the auto mask

### ISSUE THREAD

**Issue by ZhongkaiZhou** [nianticlabs/monodepth2#297]
The mask is responsible for removing pixels that do not have relative motion between adjacent frames. I have a question：Why is it that using the mask in training gives the network the ability to detect moving targets, as shown below?
![image](https://user-images.githubusercontent.com/32475718/103171727-868c6780-4889-11eb-9e09-194d37c04a6f.png)

**Comment by mrharicot** [comment]
Hi,

In this scenario the car we circled in green _appears_ to be static between all 3 images, hence it will be ignored thanks to the auto-mask. If not ignored, or handled another way, the network tends to associate appearing static with being infinitely far away.

I hope this helps!

**Comment by mnm117** [comment]
Hi! First of all thanks for your superb work and publishing it in this repository, and for your help and time...

2 points are not clear to me : 
First of all, why does the network tend to give infinite depth to static points? I think the image published in the article is about the disparity, not the depth, and the networks also try to give the fixed objects a zero disparity, which I think is true.

Second, why not use other motion detection methods to find dynamic pixels?
