### ISSUE TITLE
Question regarding training on a custom dataset

### ISSUE THREAD

**Issue by vineeth2309** [nianticlabs/monodepth2#298]
I have collected a dataset of Left and Right images using my own setup, however as the camera captures images at a high rate, there is very small motion between subsequent frames. Would this cause an issue in training?

**Comment by mrharicot** [comment]
Hi,
You can either train in stereo mode only, or simply use frames further out in your sequence with the param: `--frame_ids 0 -N N` where `N` is 1 for KITTI but could be 2, or 3 for instance in your case.
I hope this helps!

**Comment by vineeth2309** [comment]
Could the lack of motion between frames cause an issue with the automasking?

**Comment by mrharicot** [comment]
> Could the lack of motion between frames cause an issue with the automasking?

Yes, but more generally if you have very small motion between frames it will be very hard to train the model regardless.
