### ISSUE TITLE
Monodepth on Tensorflow

### ISSUE THREAD

**Issue by EnricoBeltramo** [nianticlabs/monodepth2#3]
It's present (or planned) a version of monodepth2 in Tensorflow?

**Comment by mrharicot** [comment]
Hi,
There is currently no plan to have a Tensorflow version of monodepth2.

**Comment by mdfirman** [comment]
I agree with Clement, we aren't going to make a Tensorflow version of this.

If you are _desparate_ to do this in tensorflow I would recommend starting with an existing tf-based monocular depth repo (e.g. https://github.com/tinghuiz/SfMLearner) and adding in the changes between that paper and ours.
