### ISSUE TITLE
Pose Decoder, Project3D, Data Augmentation.

### ISSUE THREAD

**Issue by sakatoable** [nianticlabs/monodepth2#302]
Hi,

Thank you for sharing the code. I have some questions! 

1: What exactly does the num_frames_to_predict_for in the pose decoder mean?  

2: The output from the pose decoder is the rotations and translations between two images. I noticed that you only use the first tensor in the second dimension when computing the transformations: 
`outputs[("cam_T_cam", 0, f_i)] = transformation_from_parameters(axisangle[:, 0], translation[:, 0], invert=(f_i < 0))`
If translation[:, 0] contains the translation vector from -1 -> 0 .. what does the second tensor in the second dimension contain? i.e: 
translation[:, 1] and axisangle[:, 1]?
3. Why do you divide the x,y dimension by the z dimension in this particular line (Project3D function): 
`pix_coords = cam_points[:, :2, :] / (cam_points[:, 2, :].unsqueeze(1) + self.eps)`
4. If you are doing data augmentation then why don't you compare to the augmented image when computing the reprojection loss? 

Thanks for your time!

**Comment by mrharicot** [comment]
Hi,

1. It basically defines the number of output layers the pose decoder has.
2. Nice catch! It is a known bug which has no impact on accuracy, the output is just ignored.
3. This is perspective projection, the basis of 3d vision. If you are unfamiliar with it you can learn from a lot of free resources such as http://www.computervisionmodels.com/ Chapter 14.
4. The augmented images typically are degraded which means that the reconstruction loss will be less informative that the original images.

I hope this helps!
