### ISSUE TITLE
Advice training on apple dataset

### ISSUE THREAD

**Issue by boeboska** [nianticlabs/monodepth2#306]
Hey Clément,

I’ve trained the monodepth2 on my own custom dataset. It only contains 1000 images which is offcourse not enough. But when I only trained on this dataset for 40 epochs the results are too bad (during inferce) in my opinion.  (see results below).

I have three question which I hope you can help me with. 

Training options:
python train.py --model_name mono_model_apple_model --png --eval_split apple_split --split apple_split --dataset apple --height 640 --width 352

My image datastructure is as follows:
Seq_1 
	0000.png
	0001.png
	..
	00065.png
..
Seq_16
	0000.png
	..
	00089.png

	
Compared to the KITTI data there is sometimes more motion between frames and sometimes a similar motion as in the KITTI data.

My preprocessing code:

class MiniappleDataset(MonoDataset):
    def __init__(self, *args, **kwargs):
        super(MiniappleDataset, self).__init__(*args, **kwargs)

        self.K = np.array([[585/720, 0, 320/720, 0], # divide by the image width
                           [0, 585/1280, 240/1280, 0],  # divide by the image height
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)
        self.full_res_shape = (720,1280) # w , h
        self.side_map = {"2": 2, "3": 3, "l": 2, "r": 3}
        # self.frame_index = None

    def check_depth(self):
        line = self.filenames[0].split()
        scene_name = line[0]
        frame_index = str(line[1])

        return False

    def get_color(self, folder, frame_index, side, do_flip):

        color = self.loader(self.get_image_path(folder, frame_index, side))
        if do_flip:
            color = color.transpose(pil.FLIP_LEFT_RIGHT)

        return color

    def get_depth(self, folder, frame_index, side, do_flip):
        f_str = "frame-{:06d}.depth{}".format(frame_index, ".png")
        image_path = os.path.join(self.data_path, folder, "depth", f_str)
        depth = self.loader(image_path)
        if do_flip:
            depth = depth.transpose(pil.FLIP_LEFT_RIGHT)

        return depth

    def get_image_path(self, folder, frame_index, side):

        image_path = os.path.join(self.data_path, folder)
        image_path = image_path + "/" + "000" + str(frame_index) + self.img_ext

        return image_path

Some training output:
epoch   0 | batch      0 | examples/s:   0.2 | loss: 0.19891 | time elapsed: 00h00m35s | time left: 00h00m00s
epoch   0 | batch     20 | examples/s:   3.8 | loss: 0.21740 | time elapsed: 00h00m42s | time left: 09h22m21s
epoch   0 | batch     40 | examples/s:   3.8 | loss: 0.23343 | time elapsed: 00h00m50s | time left: 05h30m06s
epoch   0 | batch     60 | examples/s:   3.8 | loss: 0.19297 | time elapsed: 00h00m58s | time left: 04h13m29s
epoch   0 | batch     80 | examples/s:   3.7 | loss: 0.26538 | time elapsed: 00h01m05s | time left: 03h34m19s
epoch   0 | batch    100 | examples/s:   3.3 | loss: 0.25310 | time elapsed: 00h01m13s | time left: 03h11m42s
epoch   0 | batch    120 | examples/s:   3.8 | loss: 0.23817 | time elapsed: 00h01m21s | time left: 02h56m52s
epoch   0 | batch    140 | examples/s:   3.8 | loss: 0.23041 | time elapsed: 00h01m28s | time left: 02h45m37s
epoch   0 | batch    160 | examples/s:   3.8 | loss: 0.21067 | time elapsed: 00h01m36s | time left: 02h37m13s
epoch   0 | batch    180 | examples/s:   3.7 | loss: 0.29458 | time elapsed: 00h01m44s | time left: 02h30m34s
epoch   0 | batch    200 | examples/s:   3.8 | loss: 0.26294 | time elapsed: 00h01m52s | time left: 02h25m27s
epoch   0 | batch    220 | examples/s:   3.9 | loss: 0.28354 | time elapsed: 00h01m59s | time left: 02h21m11s
epoch   0 | batch    240 | examples/s:   3.8 | loss: 0.30377 | time elapsed: 00h02m07s | time left: 02h17m39s
epoch   0 | batch    260 | examples/s:   3.8 | loss: 0.25447 | time elapsed: 00h02m15s | time left: 02h14m30s
epoch   0 | batch    280 | examples/s:   3.6 | loss: 0.21569 | time elapsed: 00h02m22s | time left: 02h11m49s
epoch   0 | batch    300 | examples/s:   3.8 | loss: 0.26174 | time elapsed: 00h02m30s | time left: 02h09m30s
epoch   0 | batch    320 | examples/s:   3.6 | loss: 0.24272 | time elapsed: 00h02m38s | time left: 02h07m28s
epoch   0 | batch    340 | examples/s:   3.7 | loss: 0.28883 | time elapsed: 00h02m46s | time left: 02h06m02s
epoch   0 | batch    360 | examples/s:   3.8 | loss: 0.20607 | time elapsed: 00h02m54s | time left: 02h04m32s
epoch   0 | batch    380 | examples/s:   3.6 | loss: 0.27471 | time elapsed: 00h03m02s | time left: 02h03m06s
epoch   0 | batch    400 | examples/s:   3.7 | loss: 0.25722 | time elapsed: 00h03m10s | time left: 02h01m55s
epoch   0 | batch    420 | examples/s:   3.8 | loss: 0.20524 | time elapsed: 00h03m18s | time left: 02h00m50s
epoch   0 | batch    440 | examples/s:   3.8 | loss: 0.28090 | time elapsed: 00h03m26s | time left: 01h59m44s

Result after 8 and 38 epochs of training:
![00026](https://user-images.githubusercontent.com/31690823/105164935-05399500-5b16-11eb-998c-9899ebb69330.png)

![00026_disp_8weight](https://user-images.githubusercontent.com/31690823/105164664-aecc5680-5b15-11eb-9fe6-86ffb88c1e42.jpeg)
![00026_disp_38 weight](https://user-images.githubusercontent.com/31690823/105164667-af64ed00-5b15-11eb-8c3b-09c28880fc5f.jpeg)

1.)	The image size is 720 x 1280 (w, h). But during training I used 352 x 640 (w, h). But I have changed the K matrix with the 720 x 1280 … this is a mistake I think?
2.)	Is my preprocess code correctly?
3.) Is there something else I did wrong?

Thank you for your help

**Comment by mrharicot** [comment]
Hi,

At a glance I don't see anything wrong with the code.
It is quite hard to tell what is going wrong here. But my first guess would be the data.
Monodepth2 was mostly built around KITTI and forward motion. 
Training it on more general scenes is more complex and would be a research paper on its own.

I hope this helps!
