### ISSUE TITLE
Where does the fixed intrinsics matrix come from?

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/monodepth2#308]
Dear Sir:

Thank you so much for sharing this great project!

In the kitti_dataset.py, there is a hardcoded intrinsic matrix, it seems been used throughout the entire training, could I know where does it come from (how to produce it)?

I'm trying to train the monodepth2 on the KITTI depth completion task, what intrinsic matrix should I use? Also, do you have any unsupervised implementation on depth completion task or any suggestions on it? 

Thank you so much!

Sincerely,
Ziyue Feng

**Comment by mrharicot** [comment]
Hi,

The focal was obtained by averaging the focals from each of the raw scenes, the principal point is fixed to be the center even though it is incorrect.
In practice it didn't seem to matter.

I hope this helps!
