### ISSUE TITLE
training on a custom dataset

### ISSUE THREAD

**Issue by orange2xiaoyu** [nianticlabs/monodepth2#310]
Hi, thank you so much for sharing this great project!

I have trained the model using my own datasets, but I found in the depth image, the cars were  holes, as shown below.

I trained with mono dataset following README.md as:
`python train.py --model_name mono_model --split eigen_zhou --dataset kitti --data_path train_data`

Do you have an idea what is going?

Thank you very much for your help!
![errors](https://user-images.githubusercontent.com/49177034/106423820-1f6f5d80-649c-11eb-9ce0-ac8b33b049d9.png)

**Comment by mrharicot** [comment]
Hi,
This is a known problem of monocular depth models trained with temporal data.
Please read the paper (see Figure 2) where we extensively discuss this issue.

**Comment by YanLiqi** [comment]
I have trained the standard mono model (not baseline) using my own datasets, but I still found in the depth image, the cars were holes. I wonder whether we need to using some costumed setting for the Auto Masking?
