### ISSUE TITLE
error when evaluate pose

### ISSUE THREAD

**Issue by njustymk** [nianticlabs/monodepth2#311]
root@5e2963c231bb:/test/code/zhou/github/code5/monodepth2-master# python evaluate_pose.py --eval_split odom_9 --load_weights_folder ./weights/mono_odom_640x192 --data_path /test/data/Kitti/Dataset/kitti_odom_test/
Traceback (most recent call last):
  File "evaluate_pose.py", line 134, in <module>
    evaluate(options.parse())
  File "evaluate_pose.py", line 73, in evaluate
    pose_encoder.load_state_dict(torch.load(pose_encoder_path))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetEncoder:
        Unexpected key(s) in state_dict: "encoder.bn1.num_batches_tracked", "encoder.layer1.0.bn1.num_batches_tracked", "encoder.layer1.0.bn2.num_batches_tracked", "encoder.layer1.1.bn1.num_batches_tracked", "encoder.layer1.1.bn2.num_batches_tracked", "encoder.layer2.0.bn1.num_batches_tracked", "encoder.layer2.0.bn2.num_batches_tracked", "encoder.layer2.0.downsample.1.num_batches_tracked", "encoder.layer2.1.bn1.num_batches_tracked", "encoder.layer2.1.bn2.num_batches_tracked", "encoder.layer3.0.bn1.num_batches_tracked", "encoder.layer3.0.bn2.num_batches_tracked", "encoder.layer3.0.downsample.1.num_batches_tracked", "encoder.layer3.1.bn1.num_batches_tracked", "encoder.layer3.1.bn2.num_batches_tracked", "encoder.layer4.0.bn1.num_batches_tracked", "encoder.layer4.0.bn2.num_batches_tracked", "encoder.layer4.0.downsample.1.num_batches_tracked", "encoder.layer4.1.bn1.num_batches_tracked", "encoder.layer4.1.bn2.num_batches_tracked".

**Comment by mrharicot** [comment]
Hi,
It appears you are using the wrong version of pytorch.
https://discuss.pytorch.org/t/solved-unexpected-key-s-in-state-dict-batches-tracked/23884

I hope this helps!
