### ISSUE TITLE
ResNet avgpool and fc layers unused

### ISSUE THREAD

**Issue by Leviosaaaa** [nianticlabs/monodepth2#313]
Hi, thank you for sharing such great work!

In the resnet_encoder, you used the classic ResNet18 or ResNet50; specifically, the features from relu layer and layer 1~5 are used by being passed to the decoders.

```python
def forward(self, input_image):
    self.features = []
    x = (input_image - 0.45) / 0.225
    x = self.encoder.conv1(x)
    x = self.encoder.bn1(x)
    self.features.append(self.encoder.relu(x))
    self.features.append(self.encoder.layer1(self.encoder.maxpool(self.features[-1])))
    self.features.append(self.encoder.layer2(self.features[-1]))
    self.features.append(self.encoder.layer3(self.features[-1]))
    self.features.append(self.encoder.layer4(self.features[-1]))
```

However, there are also avgpool and fully-connected layers in the original ResNet. To verify, I print the encoder and found the avgpool and fc layer indeed existed even though you didn't included the codes in ` class ResNetMultiImageInput`.

```python
# Terminal output of print(self.models["encoder"])
ResnetEncoder(
  (encoder): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(......)
    (layer2): Sequential(......)
    (layer3): Sequential(......)
    (layer4): Sequential(......)
    (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
    (fc): Linear(in_features=2048, out_features=1000, bias=True)
  )
)
```

So, my question is that are the avgpool and fc layers redundant here; if yes, can they be removed from the encoders; if not, how do they function.

Thank you very much!

**Comment by daniyar-niantic** [comment]
Hi @Leviosaaaa 
Yes, avgpool and fc layers are redundant and can be removed.

**Comment by Leviosaaaa** [comment]
Thank you for your prompt reply!
