### ISSUE TITLE
how to get depth of prediction ?

### ISSUE THREAD

**Issue by MrLovech** [nianticlabs/monodepth2#315]

**Comment by MrLovech** [comment]
in the paper, author convert the sigmoid output σ to depth with D = 1/(aσ + b), where a and b are chosen to constrain D between 0.1 and 100 units. here , what units represent  ?

**Comment by mrharicot** [comment]
Hi,

The units are scaled metric depth which means that they are metric up to a single scalar scale factor which is unknown in the case of monocular training but known for the stereo training case (as we know the baseline between the stereo cameras).

I hope this helps!

**Comment by MrLovech** [comment]
@mrharicot  thank you for your reply .
sorry , i still dident figure out the relationship between the image pixel value and absolutly depth. we get disp from the depth_decode network ,  here disp means diparity or something else ?  if disp is the disparity why  i use the formulation (depth  = focallength*baseline/ diparity ) to caculate the real depth and i got wrong results ? 
so , monodepth2 just can get relative depth map , not absolutly depth map right ? i really want to know how you map the image pixel value to the real world distance .

**Comment by Varat7v2** [comment]
@MrLovech Even I am looking how we can convert the monodepth pixels values to absolute depth measurement. Did you get any solutions? Thanks in advance.

**Comment by AkbarShah96** [comment]
@MrLovech @Varat7v2 You can use a single scale factor to turn predictions into metric scale. When you evaluate the results, it will also output the scale factor. Just multiple your predictions by that factor.

**Comment by Varat7v2** [comment]
@AkbarShah96 Thank you for your reply. Did you mean 5.4 as the scaling factor? I did multiply the output pixel values with it but does not look like real distances.
Note: I am running test_simple.py script. Or do I need to run evaluate_depth.py?

**Comment by AkbarShah96** [comment]
@Varat7v2 For stereo, yes, but for mono, you get a scaling factor when you run evaluate_depth.py by which you can multiply the depth predictions.
