### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by Yevkuzn** [nianticlabs/monodepth2#316]
Hi,
thanks for the wonderful work. This codebase was of great help for my research.

I would like to upload the code for my recent paper to github and make the results easily reproducible. However, I have some questions regarding the licensing:

1) I wonder if it is ok to upload the networks and layers modules of Monodepth2 to my github repository, while keeping the original license. Not needing to manually download those modules from the Monodepth2 repository will simplify the use of my method.
2) I would also like to upload there the pre-trained weights for the scale-aware modification of Monodepth2 model. I hope I can use  the non-commercial creative commons license for that model. 

Looking forward to hearing from you
Yevhen

**Comment by mdfirman** [comment]
Hi Yevhen,

Thanks for your interest! I reached out to our legal team here, and the solution we have is:

1. No, sorry – you can't take a copy of these files. But you could instead leave a placeholder file for these layers and direct people to our repo for the files to grab. You could also reimplement these files based on the descriptions in our paper.
2. No, any models created with our code or derivative works of our code must also be released under the same non-commercial licence as our original models.

Sorry if this doesn't make life as easy as you'd hoped. Thanks again for using our repo, and for asking us about this.

Thanks,

Michael
