### ISSUE TITLE
Distorted Objects in the Synthesized Frames 

### ISSUE THREAD

**Issue by sakatoable** [nianticlabs/monodepth2#318]
![image](https://user-images.githubusercontent.com/74879471/110100363-9bfaa200-7da2-11eb-96ee-557213b9e417.png)

Why are poles, trees and other vertical objects distorted in the synthesized images? At least this is the case in foreground/nearby vertical objects  but seems to be find for far away ones. (Zoom in the image to see more)

Thanks!

**Comment by mrharicot** [comment]
Hi,
The depth predicted in the occluded regions will fetch pixels from the foreground creating these double images.
I hope this helps!
