### ISSUE TITLE
Cityscapes DataLoader

### ISSUE THREAD

**Issue by sakatoable** [nianticlabs/monodepth2#319]
Hi,

Is it possible to provide the cityscapes dataloder that you used to pretrain the networks for CS+K rows in your results? Or could you point out any implementations you are aware of that are publicly available?

Thanks!

**Comment by mrharicot** [comment]
Hi,
We unfortunately do not have the dataloader for the release version of monodepth2.
However it should be fairly easy to inherit from the MonoDataset class to create one.
Here's the intrinsics matrix for it:
```
self.K = np.array([[1.1,   0, 0.5,   0],
                   [0,   2.2, 0.5,   0],
                   [0,     0,   1,   0],
                   [0,     0,   0,   1]], dtype=np.float32)
```
