### ISSUE TITLE
advice for choosing min_depth and max_depth

### ISSUE THREAD

**Issue by jjinCode** [nianticlabs/monodepth2#320]
Hi~

I training monodepth2 with my custom dataset.
Unlike kitti dataset, on custom dataset, train/val a1 acc are not converge to some constant value (fluctuating around 0.84)
And I suspect that the cause of this are min_depth / max_depth because custom dataset's baseline(about mono image sequence)
is not the same as kitti's.

So I have a question.
1) Is it good idea to find optimal min/max_depth both for custom dataset?
2) Do you have any idea for choosing min/max_depth for mono image sequence with very short baseline?

**Comment by mrharicot** [comment]
Hi,
The min/max depth were chosen such that the actual min/max of kitti was in the same range (up to scale) and such that it was stable for training with both mono and stereo modes.
Typically unless you are training with a stereo dataset for which the ratio between the baseline and the min/max depth is incompatible with the default values, it should probably work without modifications.
