### ISSUE TITLE
Can you share your Make3D test file (make3d_test_files.txt)?

### ISSUE THREAD

**Issue by youzunzhi** [nianticlabs/monodepth2#321]
In issue #89 you mentioned your Make3D test files are from a txt file named "make3d_test_files.txt". I wonder if you can share this file so it would be easier for me to replicate your results on this dataset. Thank you so much!

**Comment by mrharicot** [comment]
Hi,
We tested on all 134 test images you can find here:
http://make3d.cs.cornell.edu/data.html

I hope this helps!

**Comment by Asherchi** [comment]
hello, I am also meet this problem, have you solve it? plese share your experience, thank you so much!
