### ISSUE TITLE
Trained model checkpoints for zero padding

### ISSUE THREAD

**Issue by chrschinab** [nianticlabs/monodepth2#327]
I want to compile the monodepth2 model with TensorRT. As TensorRT does currently not support reflection padding, I have replaced it by zero padding.
Do you have any checkpoints for trained models with zero padding which you could provide?
Otherwise, I will have to retrain the model.

**Comment by mrharicot** [comment]
Hi,
We do not have models trained with zero padding, but you don't have to retrain, you could simply fine tune a model after replacing the padding.
