### ISSUE TITLE
how to draw a trajectory picture using the pose result

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#33]
Sorry to bother you again~
How can I transform the pose evaluation result to the same format as the gt file provided by KITTI. I mean when I want to draw the pose trajectory, I found the output pose result's format is N * 4 *4 , but the groundtruth file's format is N*12.
![image](https://user-images.githubusercontent.com/28101548/60649779-09478880-9e86-11e9-9697-79cd2af1cb18.png)
Actually I just want to draw a trajectory picture like this to see the pose result.
![image](https://user-images.githubusercontent.com/28101548/60650005-95f24680-9e86-11e9-95d8-ecf851732a3a.png)
Thank you very much for your help.

**Comment by sunnyHelen** [comment]
N X 4 X 4 and N X 12

**Comment by FangGet** [comment]
just save and draw translation vector (3 * 1)

**Comment by mdfirman** [comment]
Yes the N x 12 vector is just the 4x4 with the bottom row removed and reshaped into a flat vector.

In terms of plotting the trajectory: Yes, as @FangGet you can take the translation component. To chain together all your predictions together into the full sequence you might need to accumulate all rotation and translation poses in the sequence. We never did these visualisations for the paper – if you need code for this you might be best looking at a repo by people who have made these pose diagrams.

**Comment by kwea123** [comment]
maybe my repo can help you. https://github.com/kwea123/monodepth2/blob/master/depth_prediction_example.ipynb

**Comment by sunnyHelen** [comment]
Wow, it's very helpful. Thank you very much :)

**Comment by sunnyHelen** [comment]
@kwea123 
How do you get the scale value?
![image](https://user-images.githubusercontent.com/28101548/60690486-02168e00-9f0b-11e9-9918-a825d7e7a7f4.png)
And I got a picture like this:
![image](https://user-images.githubusercontent.com/28101548/60690554-836e2080-9f0b-11e9-95ec-ab7f8348fa7c.png)
I don't know why I always get two pred lines.

**Comment by kwea123** [comment]
@sunnyHelen Hi I think it's better to discuss in my repo since it's no longer an issue for this repo.
Can you open an issue in my repo?
Thanks.

**Comment by sunnyHelen** [comment]
Oh, sure. Thanks for your kind reply

**Comment by FangGet** [comment]
try this：https://svncvpr.in.tum.de/cvpr-ros-pkg/trunk/rgbd_benchmark/rgbd_benchmark_tools/src/rgbd_benchmark_tools/evaluate_ate.py

**Comment by kwea123** [comment]
@sunnyHelen I just opened the issue tab.

**Comment by luyao777** [comment]
@sunnyHelen Hi, could u share your visualization code? I got some chaotic figures. thx.

**Comment by emad555** [comment]
Try EVO toolkit:
https://github.com/MichaelGrupp/evo
