### ISSUE TITLE
PoseDecoder parameter when using "separate_resnet"

### ISSUE THREAD

**Issue by wut128** [nianticlabs/monodepth2#331]
If "separate_resnet" is used as Pose_Encoder, parameter "num_frames_to_predict_for" in Pose_Decoder is set to be 2. However, if "pose_model_input" is set to be "pairs", there should be only one transformation between frame 0 and frame -1 or between frame 0 and frame 1. In my opinion, "num_frames_to_predict_for" should depend on the type of pose model input. I wonder if I make a mistake. Thanks.

**Comment by mrharicot** [comment]
Hi,
Yes this is a known bug which has no impact on performance.
