### ISSUE TITLE
Why is training data shuffled, since the supervision is based on temporal order?

### ISSUE THREAD

**Issue by dexter2406** [nianticlabs/monodepth2#333]
Hello,

I notice that there's no temporal order in the *Odometry* training data (but for testing data it's in order). I understand that the depth network alone can be trained with the Velodyne depth map, but how would the pose network be trained using these shuffled data? In my opinion, at least it's supposed to be a triplet (one target + two source imgaes) to make the self-supervision works, right?

Thanks for your time.

**Comment by mrharicot** [comment]
Hi,

The data is indeed shuffled, but at the triplet level so for each sample we have temporal order preserved.

I hope this helps!
