### ISSUE TITLE
Why use identity loss and not zero loss?

### ISSUE THREAD

**Issue by boeboska** [nianticlabs/monodepth2#335]
Hi,

You use the identity loss for those pixels where the reprojection loss is higher then the identity loss. This is for masking out stationary pixels.  I understand this idea.

But in my opinion you use this approach to lower the loss for those pixels because this is noise for the model because in those frames these is no camera movement or objects moving in simiar speed.

But why don't you set the loss to 0? Or can the model still benefit from the identity loss?

Would like to hear your opinion.
Thanks!

**Comment by mdfirman** [comment]
Thanks for your interest here.

The identity loss is just something to compare against. If the identity loss is lower than the 
standard reprojection loss, then we use the identity loss in the final loss computation.

However: the identity loss is constructed from non-trainable components. That is, all the variables used to create the identity loss are outputted from images and calculations which can't be trained – they are fixed. So when the identity loss is chosen for a pixel, *it is equivalent to setting the loss for that pixel to zero*.

More mathematically: I think that that for a pixel which has the identity loss, the gradient of the loss with respect to the parameters of the network is zero.  

Does this make some sense?
