### ISSUE TITLE
Why does the inverse-warped image look more like the source than the target image? (see image example)

### ISSUE THREAD

**Issue by dexter2406** [nianticlabs/monodepth2#336]
To my understanding, *inverse warping* (`back_project` and `project_3d` in the code) takes
- the image of the source view (see image below, 1st raw)
- the depth map of the target view (2nd raw)
- the estimated pose, from source to target view

and produces the reconstructed target view (last raw). So the reconstructed view should look like the target more than the source image, right?

But I found that the reconstructed view looks almost identical to the source (i.e. no visible transformation) instead of transforming toward the target view. So I'm confused now... Btw, I used the provided code and models without any modification.

![comparison](https://user-images.githubusercontent.com/46349448/114414269-f3b0d800-9bae-11eb-870e-1a957621fd26.png)

**Comment by dexter2406** [comment]
It's my wrong implementation. Sorry.

**Comment by koutilya-pnvr** [comment]
@dexter2406 I am facing the same issue. Any idea what I might be doing wrong?
