### ISSUE TITLE
Empty Epoch Problem

### ISSUE THREAD

**Issue by HarderThenHarder** [nianticlabs/monodepth2#34]
Hi, sorry to trouble you. 
I'm trying to use monodepth2 to train my own dataset, and I met some problem when I was training. There were some `epochs` seem to be `empty`, because there are `no outputs`(no loss, no time elapsed, no time left, seems to be skipped).<br>
I wonder the reason of this situation.<br>
Very hope you could see this issue, appreciate a lot!
<br>
![image](https://user-images.githubusercontent.com/36854507/60694089-781cf400-9f0f-11e9-8b77-fcf261543994.png)

**Comment by mdfirman** [comment]
Hi, thanks for your interest in this repo!

Are you certain that no training is happening for these epochs? Or could it just be that no logging is happening?

The [logic for when to log](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L211) (including writing a line to terminal) is worth having a look at. After the first 2000 steps, the logging happens far less frequently, and in fact (if your dataset is small) whole epochs may pass without any logging.

You could consider changing line 214 to

                if batch_idx % self.opt.log_frequency == 0

which would ensure that at the very least logging happens on the first batch of each epoch.

Thanks

**Comment by HarderThenHarder** [comment]
Thanks a lot for your answer, I'm going to follow your advice to learn about the log logic.
Best wishes!
