### ISSUE TITLE
The program stops and outputs "Terminated" with no error output

### ISSUE THREAD

**Issue by WrongMalik** [nianticlabs/monodepth2#340]
Hello, thanks for the great work. I use the code to train on the KITTI raw data, but my program always stops and outputs "Terminated" with no error output in a random batch during the first epoch. I add the "try-except" but still get nothing output.

I use "python train.py --model_name mono_model --png" to run.

I want to know the possible reasons, thanks a lot.

**Comment by mrharicot** [comment]
Hi,
For us to be able to help you, could you please post the full stacktrace as well as your system details (OS, GPU, python version, etc.) ?

**Comment by WrongMalik** [comment]
Hi,
I'm sorry I didn't provide the details.

I submit code to run on my school's HPC. The GPU is NVIDIA Tesla P100 PCIe 16GB. 
CUDA=10.1, python=3.6.6, torch=0.4.1, torchvision=0.2.1

This is the output of one of the runs
> Training model named:
   mono_model
Models and tensorboard events files are saved to:
   ./logs
Training is using:
   cuda
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items
Training
epoch   0 | batch      0 | examples/s:   1.2 | loss: 0.16949 | time elapsed: 00h00m33s | time left: 00h00m00s
epoch   0 | batch    250 | examples/s:  16.2 | loss: 0.12577 | time elapsed: 00h07m38s | time left: 33h40m33s
Terminated

And there is other details
> Resource usage summary:
    CPU time :                                   11033.00 sec.
    Max Memory :                                 6824 MB
    Average Memory :                             4937.52 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              28
    Max Threads :                                760
    Run time :                                   822 sec.
    Turnaround time :                            835 sec.

**Comment by mdfirman** [comment]
Thanks for the extra details.

"Terminated" isn't something outputted by our code.

My guess would be that this job is being terminated by the HPC itself. Perhaps it is using too much memory, or you haven't set a high enough job time limit? It might be worth getting in touch with the people running the HPC to help to diagnose this

**Comment by WrongMalik** [comment]
Thanks for the answer. Recently I will try to ask the manager and run the code on other machines.
I think it is very likely to be my own problem, I am sorry to take up your time.

**Comment by mrharicot** [comment]
No problem at all @WrongMalik, we're happy to help. Good luck!

**Comment by WrongMalik** [comment]
Hi,
I asked the Cluster Administrator to check the system log yesterday. The number of cores used by my program exceeded the assigned number, which caused overload during operation. So it was killed by the cluster.

It seems that my GPU experience is not rich enough.   : )
