### ISSUE TITLE
[Feature requested] Support for depth-separable(depth-wise) backbones such as MobileNetV2, EfficientNet...

### ISSUE THREAD

**Issue by CaptainEven** [nianticlabs/monodepth2#341]
Thank you for your excellent work! I want to deploy MonoDepthV2 to an embedding chip(Horizon X3) which is computational efficient on backbones for depth-separable structure. I will appreciate if such a backbone network is provided!

**Comment by mrharicot** [comment]
Hi,
Adding new backbones is outside the scope of this repo, which is meant to provide code to reproduce results from the paper and be a baseline other work can be based on.
However it shouldn't be too difficult to add different backbones by following the example from `ResnetEncoder`:
https://github.com/nianticlabs/monodepth2/blob/master/networks/resnet_encoder.py#L62
