### ISSUE TITLE
a question about intrinsic for KITTI raw dataset

### ISSUE THREAD

**Issue by C-Anonymity** [nianticlabs/monodepth2#342]
Thank you for your wonderful work and careful maintenance :)
I have a question about the intrinsic for KITTI raw dataset. The  **P_rect_03**** in the calib_cam_to_cam.txt** file for KITTI raw file  is [[707.0, 0, 601.8, -333.4], [0, 707.0, 183.1, 1.9],  [0, 0, 1, 0.003]]. I know that the nine numbers in the first 3 columns are intrinsic. However, what do the three numbers in the last column mean? I guess the first number is the baseline(-(0.54-0.06)*707), Is this correct? 
Thanks!

![AGHMESNULU OA)((R`A}G}H](https://user-images.githubusercontent.com/32475718/117767432-818dea80-b263-11eb-8237-c4aac6817df6.png)

**Comment by mrharicot** [comment]
Hi,
`P_rect` corresponds to the final projection matrix after rectification as stated in the [devkit](https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_raw_data.zip) readme:
```
P_rect_xx: 3x4 projection matrix after rectification

...

example transformations
-----------------------

As the transformations sometimes confuse people, here we give a short
example how points in the velodyne coordinate system can be transformed
into the camera left coordinate system.

In order to transform a homogeneous point X = [x y z 1]' from the velodyne
coordinate system to a homogeneous point Y = [u v 1]' on image plane of
camera xx, the following transformation has to be applied:

Y = P_rect_xx * R_rect_00 * (R|T)_velo_to_cam * X

To transform a point X from GPS/IMU coordinates to the image plane:

Y = P_rect_xx * R_rect_00 * (R|T)_velo_to_cam * (R|T)_imu_to_velo * X

The matrices are:

- P_rect_xx (3x4):         rectfied cam 0 coordinates -> image plane
- R_rect_00 (4x4):         cam 0 coordinates -> rectified cam 0 coord.
- (R|T)_velo_to_cam (4x4): velodyne coordinates -> cam 0 coordinates
- (R|T)_imu_to_velo (4x4): imu coordinates -> velodyne coordinates

Note that the (4x4) matrices above are padded with zeros and:
R_rect_00(4,4) = (R|T)_velo_to_cam(4,4) = (R|T)_imu_to_velo(4,4) = 1.
```

I hope this helps!

**Comment by C-Anonymity** [comment]
Thank you so much!
