### ISSUE TITLE
Why scale camera pose translation with mean inverse depth during training but not evaluation?

### ISSUE THREAD

**Issue by kkoledic1212** [nianticlabs/monodepth2#348]
I am curious why is this done because I feel like it leads to incorrect pose estimation during evaluation. 

During training translation is scaled here:
https://github.com/nianticlabs/monodepth2/blob/93b9ebb4c8bdc71a07e18bee64d76ec21bc3e8fc/trainer.py#L374-L375

However, during evaluation translation is not scaled:
https://github.com/nianticlabs/monodepth2/blob/93b9ebb4c8bdc71a07e18bee64d76ec21bc3e8fc/evaluate_pose.py#L99-L100

Doesn't this lead to incorrect pose evaluation? Also, what is the benefit of using it during training?

**Comment by mdfirman** [comment]
Hi – thanks for your interest!

We used it during training following another paper which used it (I think we link to that paper in the code or at least in our publication)

We don't need it at testing time as the test-time predicted poses are only up-to-scale anyway, and are rescaled to match the ground truth poses [here](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_pose.py#L44). So multplying `translation` by a scalar would have no effect.

Does this make sense to you?
