### ISSUE TITLE
disparity to depth

### ISSUE THREAD

**Issue by KunikaValecha** [nianticlabs/monodepth2#349]
In file layers.py is a function disp_to_depth, which takes disparity numpy array along with min and max disp values. Later it converts disparity to depth by reciprocating the disparity values. For saving depth vals, it is suggested to multiply depth values with a constant 0.54 which is baseline. However, to restore the depth formula is 

depth = (baseline * focal len)/( img_width * disparity)

Then why are other parameters ignored in the calculation?

**Comment by mdfirman** [comment]
Thanks for the interest here!

I think the main issue here is that we have used misleading variable names. The `disp` which we predict isn't true disparity, as is usually used in e.g. stereo matching. What we in fact predict should be called `scaled_inverse_depth`. 

So mathematically we don't need the focal length and image width to convert our scaled inverse depth prediction into depth, as we have already taken care of those during training. 

Does this help to clear things up a little?
