### ISSUE TITLE
Why do you not use the augmented images for computing loss?

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#35]
I noticed that you are only using the augmented images for passing through the depth net. But when you do the inverse warping and compute the losses, you always use the original color image. Why is that?

**Comment by mdfirman** [comment]
Thanks, this is an interesting question. 

We augment for the forward pass as we want the network to learn to be invariant to image changes which do not change the desired output. In our case we use colours and flips. The flip-augmented images *are* used in the loss, so it is only colour augmentation which differs.

When computing the loss, we have always used the original images as these are the closest to what the scene actually looks like. There are probably many arguments for and against using the colour-augmented images for matching, but one argument against is: Augmentation is likely to cause information loss, e.g. by saturating colours. The un-augmented images therefore contain the greatest amount of colour and texture information.

We never tried matching on the colour-augmented images. If you do this experiment please do report your findings here!

Thanks

**Comment by Beniko95J** [comment]
Hi, I tried the experiment which computes the re-projection errors on color-augmented images, while I get awful results. The abs_rel error turns to be 0.369 using the evaluate_depth.py script in my case.

I am still wondering why this change can bring such a large difference. I think the network should also have learnt some more environments with different lighting conditions or something by computing re-projection errors on color-augmented image pairs. Anybody has some ideas about this?
