### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by CodeKingWang** [nianticlabs/monodepth2#350]
Firstly, thank you for your work. I'm encountering some problems when I run this code. I put it on the next line.
![image](https://user-images.githubusercontent.com/38208467/119324730-bdd53800-bcb2-11eb-8ee2-048d2106ef65.png)
I find the code about this error, but I have no idea how to correct it.
![image](https://user-images.githubusercontent.com/38208467/119324923-ee1cd680-bcb2-11eb-9d86-e3f3bd33aab9.png)

**Comment by WrongMalik** [comment]
https://github.com/nianticlabs/monodepth2/issues/323
This issue solved the problem.

Or maybe your pytorch vision is too new. You can try pytorch=0.4.1 as mentioned in the Setup.
