### ISSUE TITLE
How can I get the calibration.txt

### ISSUE THREAD

**Issue by CodeKingWang** [nianticlabs/monodepth2#351]
Ｉ tried to download these text files from the official website. But it only shows documents trees

**Comment by mdfirman** [comment]
Hi, thanks for your interest – could you please expand a little on what you are trying to download and what you ended up downloading?

You don't need to download `calibration.txt` to train the monodepth2 repo.

Thanks

**Comment by mdfirman** [comment]
Also – what official website are you referring to? The 'official website' of monodepth2 is this github repo.

Thanks,

Michael

**Comment by mdfirman** [comment]
Closing this – feel free to reopen if needed
