### ISSUE TITLE
How to chose the pose_model_type

### ISSUE THREAD

**Issue by wxlwhu** [nianticlabs/monodepth2#352]
Hi,
  I am trainning on the custom-dataset these days using monodepth2 (data from a monocular camera), and I wander how to chose the pose_model_type (shared or separate_resnet). Would you please tell me the difference or the corresponding effect between the above two options. I am expecting for your reply.

**Comment by mdfirman** [comment]
I would definitely choose `separate_resnet`. We included `shared` as a legacy option just to allow some ablation comparisons.

In general, the defaults in `options.py` are the best we could find, at least for the KITTI dataset.
