### ISSUE TITLE
Using the pretrained model with a monocular camera to obtain depth map

### ISSUE THREAD

**Issue by LulaSan** [nianticlabs/monodepth2#353]
Hi, I have read the previous issues but I was not able to figured out a thing. Your way to get depth from disparity is now largly used and different works refers to yours.

If I use your pretrained model, is it possible to get real-time distance in meters, using as input a single, RGB, image ( I mean frames from a video) ?  I am confused about the conversion from disparity to depth, since I am using a monocular camera that does not have the parameters to apply the conversion formula...

**Comment by mdfirman** [comment]
Thanks for your interest here!

I would say: Be careful, as the models we provide will only *estimate* distance, and in many circumstances will not be able to do well. In general we can do a reasonable job given images which look similar to the KITTI dataset (in terms of objects, scene structure, camera intrinsics, image aspect ratio etc).

If you do still want to estimate depth on your own images:

* Use one of our models which has been trained with stereo training
* Use `test_simple.py` with the `--pred_metric_depth` flag set.

Then the saved npy files will contain an estimate of metric depth.
