### ISSUE TITLE
Using flyout mask leads to weird border affects

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#36]
I know this was mentioned in this issue: https://github.com/nianticlabs/monodepth2/issues/20
However, it was said that this was only an issue for the stereo case.

I tried manually computing the fly-out mask and replacing the invalid region of the warped image with the actual pixels from the target image. And in some cases, this led to the depth net predicting inf depth at the edges. I realize that this is different from using zero padding when performing the grid sampling. But I would think this would lead to better results, not worse, because by using the fly-out mask, you are not allowing the fly-out pixels to contaminate the loss.

<img width="335" alt="flyout_mask_leads_to_weird_results" src="https://user-images.githubusercontent.com/19962279/60748033-c3023000-9f3e-11e9-91c7-4977de9838c3.png">

**Comment by mdfirman** [comment]
Hi @aj96,

Yes, we believe that using border edge padding produces better results than masking, and your experiment lends some evidence to this. The exact reasons for this, though, are not well studied. If you do more work to understand the benefits and weaknesses of different ways of dealing with 'fly-out' regions I'm sure the wider community would like to hear about it!

Thanks

**Comment by Shaw-Way** [comment]
> I know this was mentioned in this issue: #20 However, it was said that this was only an issue for the stereo case.
> 
> I tried manually computing the fly-out mask and replacing the invalid region of the warped image with the actual pixels from the target image. And in some cases, this led to the depth net predicting inf depth at the edges. I realize that this is different from using zero padding when performing the grid sampling. But I would think this would lead to better results, not worse, because by using the fly-out mask, you are not allowing the fly-out pixels to contaminate the loss.
> 
> <img alt="flyout_mask_leads_to_weird_results" width="335" src="https://user-images.githubusercontent.com/19962279/60748033-c3023000-9f3e-11e9-91c7-4977de9838c3.png">

Hello, I have been experimenting with this question recently, but I encountered some problems when computing the mask. Can I ask how you compute the mask?
