### ISSUE TITLE
Question about loss

### ISSUE THREAD

**Issue by dmariaa** [nianticlabs/monodepth2#360]
Hi! First of all thanks for your superb work and publishing it in this repository, and for your help and time...

As part of my degree final work, I have generated a custom dataset by driving a virtual vehicle in a videogame called "Euro Turck Simulator 2" (have extracted the frames, ground-truth depth and ground-truth telemetry at 10 fps -could get up to 30fps if needed-) to train monodepth2 and validate this kind of synthetic datasets for training tasks...

My first attempt with about 8k images in the train dataset have given very promising results, of course I understand it's not enough data but it gives good results and even generalise well when tested with real images, my only concern is that training starts at a some low loss, about 0.07 where I expeced to start about 1.2 or 1.3 as when I tried with kitty dataset...

epoch   0 | batch      0 | examples/s:  32.4 | loss: 0.07159 | time elapsed: 00h00m12s | time left: 00h00m00s

then it converges down to below 0.03 ... 

Is normal this low starting loss? Maybe it can be something related to my dataset?

I know my question is probably too vague but any indication will be welcome...

Kind regards and thanks again!!!!

**Comment by mdfirman** [comment]
Thanks for your interest.

The scale of the numbers on the loss are pretty meaningless, I would have thought. 

More importantly – do your reprojected images and depths in tensorboard look ok?

**Comment by mdfirman** [comment]
Take a look at this thread for some useful tips and hints on using custom datasets:
https://github.com/nianticlabs/monodepth2/issues/343

**Comment by dmariaa** [comment]
Thank you!!!

I've found it very usefull, the reprojected images and disparities in tensorboard look very promising, considering training was done with only 8k images... now I'm training with more than 31k and check results, as soon as it finishes I will share results here...

**Comment by dmariaa** [comment]
Hi!!!! 

I have training with 31k images, and got some results. If someone is interested, here [TensorBoard](http://dmariaa.es:6006) is the tensorboard obtained, and here [ETS2 Dataset](https://www.dmariaa.es:8101/files) the dataset can be reviewed and downloaded. It has motion/odometry ground truth data and depth ground truth too, not used here... 

Here is the evaluation after the training. Evaluation is done in the KITTY dataset, training is fully done in the synthetic one.

| abs_rel | sq_rel | rmse | rmse_log | a1 | a2 | a3 |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 0.321 | 6.186 | 10.721 | 0.374 | 0.609 | 0.827 | 0.912 |

The results are not bad I think. I'm doing some more research to improve them, but I think network trained with this dataset generalizes fairly well to predict in real images. 

In tensorboard I have realized a couple things I don't understand, I would appreciate any help about them.

This is a sample extracted from the Tensorboard.

automask_0
![black_mask](https://user-images.githubusercontent.com/5584976/122354434-49a85000-cf51-11eb-8647-c98780c806fd.png)
color_0
![black_mask_color](https://user-images.githubusercontent.com/5584976/122356256-e6b7b880-cf52-11eb-92b2-e2f3c89efd2a.png)
disp_0
![black_mask_disp](https://user-images.githubusercontent.com/5584976/122356255-e6b7b880-cf52-11eb-8360-cd8b4c1ef3ad.png)
color_pred-1_0
![black_mask_pred_-1](https://user-images.githubusercontent.com/5584976/122356284-ed463000-cf52-11eb-939d-f66c7dd01742.png)
color_pred_1_0
![black_mask_pred_1](https://user-images.githubusercontent.com/5584976/122356292-f1724d80-cf52-11eb-8c28-0dda1ac14b51.png)

The first issue I see is a complete black mask. This happens only in a few images, and doesn't seem to affect the overall training. Also, the predicted right image has some glitches in the short distance pixels (bottom), they don't appear in the left predictions. These happens independent of the black mask issu happens or not.

The images have been pretty downsized, from 1440x816 to 320x128 as I am using a shared machine and a bit short on resources (GPU and disk space).

Thanks again for your work, and for the comments and help.

**Comment by biggiantpigeon** [comment]
@dmariaa I think I can have a guess about your second question, this is because in the code, the flying out area of image is padded by 'border', see #20 
I guess your camera is moving forward, and the edge areas in your 0 frame will not appear in +1 frame, so you can see the glitches. But the -1 frame see more things close to camera than 0 frame, so this will not happen.

**Comment by ChauChorHim** [comment]
@dmariaa I know it's been late to response, but your idea of using Euro Track Simulator to generate dataset is quite interesting.
For the first issue, complete black mask means the reprojection loss is larger than identiy_reprojection_loss for all pixel. Normally it's because the camera is static. But I guess here is because you use the wrong previous frame and wrong future frame to compute the reprojection loss.

**Comment by dmariaa** [comment]
> @dmariaa I know it's been late to response, but your idea of using Euro Track Simulator to generate dataset is quite interesting.
> For the first issue, complete black mask means the reprojection loss is larger than identiy_reprojection_loss for all pixel. Normally it's because the camera is static. But I guess here is because you use the wrong previous frame and wrong future frame to compute the reprojection loss.

Thank you for your comment... If you want to know more about the idea, or just have any question about it my email address is visible in my profile, just don't hesitate to write...

**Comment by daniyar-niantic** [comment]
Thanks for reporting back. I think it is ok to close this issue?
