### ISSUE TITLE
question about the paper: why use multi-scale?

### ISSUE THREAD

**Issue by biggiantpigeon** [nianticlabs/monodepth2#361]
In the paper **Multi-scale Estimation** part, it is said: Due to the gradient locality of the bilinear sampler [21], and to prevent the training objective getting stuck in local minima.

I don't think this through, nor did I find an answer in ref[21]. So what is the reason for gradient locality? Or where is the discussion about this in ref[21]?

Thanks a lot!

**Comment by mdfirman** [comment]
Thanks – the paper is mildly unclear here, and really the references which do this multi-scale estimation in the past are [12, 15] (the reference to [21] is just a reference to the bilinear sampler):

![image](https://user-images.githubusercontent.com/6114258/121316966-be500e80-c901-11eb-9661-8e817cd2233f.png)

This is the text about it in Monodepth1:

![image](https://user-images.githubusercontent.com/6114258/121316821-9d87b900-c901-11eb-8126-03cbca7a7a7f.png)

In practice using multi-scale helps ensure that the whole of the network, including the very deep layers, are forced to learn about depth. Without it, the skip connections tend get stuck in a local minimum, and the middle layers of the network don't learn very much. 

It's not a particularly scientifically studied part of the system though, and I'm sure it could do with more investigation!

Thanks

**Comment by biggiantpigeon** [comment]
Thanks for reply, I understand a little bit from the answer why we use multiscale, but I still don't understand this: is bilinear interpolation the reason of 'gradient getting stuck'? Why? The paper seems to mean so and so does Zhou's paper.
