### ISSUE TITLE
Scaling Factor of the Predicted Depth Map

### ISSUE THREAD

**Issue by cyuanqi920** [nianticlabs/monodepth2#362]
Hi, it was indicated in the README.md that the scaling factor for stereo model was a 5.4. I am currently using the "mono" model and was wondering is there any generalised ways for me to calculate the scaling factor?

**Comment by mdfirman** [comment]
Not really. But you could compare the depths with the 'stereo' model, and find the average scaling difference in depths between the stereo model and the mono model. Then you could scale all the mono predictions by this factor, to bring them roughly into line with the stereo predictions.

Alternatively you could use estimates of the size of known objects in the scene (e.g. people, cars, storeys of buildings) to more manually form and estimate of the true real-world scale.

Would either of these approaches work for you?

**Comment by mdfirman** [comment]
I'm going to close but please let me know if you make any progress.
