### ISSUE TITLE
training

### ISSUE THREAD

**Issue by wrg-python** [nianticlabs/monodepth2#363]
I'm going to train this model, but there is often a problem that a picture in the data set is not loaded. So can you give me a complete data set? Including all the raw data sets of kittit required by the interview training.I'd appreciate it if you could.Baidu network disk can also be used.

**Comment by mdfirman** [comment]
Hi thanks for your interest.  Did you follow our instructions in the README for downloading the KITTI training data?

That is the method we provide to get the complete dataset. I'm afraid we can't provide you with a network disk with the data on.

Thanks

Michael
