### ISSUE TITLE
Training data or no need?

### ISSUE THREAD

**Issue by abdurrahman98ee** [nianticlabs/monodepth2#365]
First of all, thank you very much for this wonderful research. Hope you got the most out of it.

I am currently working on project where we want to find depth map from single RGB camera. I went through your paper and code and it is understandable. 

So, is it important to retrain the models you provided in the list of models (mono_640x192, stereo_640x192 and .. etc.) or it is fine to download the one of the model and run it with the code you provided under "depth_prediction_example.ipynb"

**Comment by mdfirman** [comment]
Great, thanks

You are welcome to try out the pretrained models we provide, to see if they are suitable for your purpose. 

If the prediction results are bad, though, you could consider retraining on your own data.

Does this make sense?

**Comment by abdurrahman98ee** [comment]
The pretrained models were for indoors or outdoors environment?

**Comment by mdfirman** [comment]
They were trained on KITTI driving footage, outdoors.

If you want to predict indoors I would recommend using a supervised network, .e.g DenseDepth:
https://github.com/ialhashim/DenseDepth

**Comment by mdfirman** [comment]
If you could show some images of the type of images you want to predict depth for I might be able to help to direct you to a model which is most suitable

**Comment by biggiantpigeon** [comment]
If I have two image set taken by the same camera, one is from outdoor driving footage, similar to KITTI, the other is driving footage in a underground garage in a mall. Can I mix them together to train one network? Thanks a lot.

**Comment by mdfirman** [comment]
Yes you should be able to train one network. But it would work best if the two datasets have similar intrinsics and aspect ratios and are captured at a similar number of frames-per-second.
