### ISSUE TITLE
odometry split test file list

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#37]
Hi,
I'm wandering how do you generate these files for different sequences. I want to evaluate model on  
other sequences. How can I get those?
![image](https://user-images.githubusercontent.com/28101548/60860225-fe5f7000-a258-11e9-91fa-c7440b3ae918.png)

**Comment by mdfirman** [comment]
Hi @sunnyHelen ,

Are the other sequences kitti odometry sequences or your own sequences?

The format of these files is so simple that any script we wrote to create them we certainly didn't keep. Each line has three items, comprising `integer integer string`, corresponding to `folder frame_index side`.

This is then read and extracted [here](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py#L144) , and used to load in a frame from the odometry dataset [here](https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L89).

You are welcome to create new files in the same format, or to write your own dataloader which processes your own split files. 

Thanks

**Comment by sunnyHelen** [comment]
Got it. Thanks a lot~
