### ISSUE TITLE
webcam

### ISSUE THREAD

**Issue by emad555** [nianticlabs/monodepth2#370]
I am trying to run the model using my webcam with test_simply.py file.

What things should I consider?

**Comment by mdfirman** [comment]
Thanks for trying this out in this new setting.

I think the main thing to consider is: Unless your webcam is mounted on the front of a car facing the road, you are unlikely to get good depth predictions. If you want to get good depth estimation indoors you might want to try a depth estimation network trained supervised on indoors data (e.g. ScanNet or NYU) instead.

Thanks
