### ISSUE TITLE
Leaking Caffe2 thread-pool after fork.

### ISSUE THREAD

**Issue by onionysy** [nianticlabs/monodepth2#371]
I try to use monodepth to train my dataset, but it has warning in my training process. Sometimes, it can cause a computer to crash.I had this warning the first time I trained, but I can still train. The second training directly led to the computer stuck. I know there's a thread problem, but I can't pinpoint it. I wonder if you have any good suggestions.
`[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)`
thanks for your reply.

**Comment by mdfirman** [comment]
Thanks for trying out the repo. When the program crashes, are any additional errors or messages printed to screen?

It looks like the message you are getting might be normal behaviour:
https://github.com/pytorch/pytorch/issues/57273

One suggestion from that thread which might help would be to try setting `pin_memory=False` on lines 132 and 138 of trainer.py.

Please do let us know if this fixes it. Thanks
