### ISSUE TITLE
Failure cases

### ISSUE THREAD

**Issue by C-Anonymity** [nianticlabs/monodepth2#377]
During testing, I found that the Monodepth2-M cannot accurately estimate the depth of the man in white. The depth of his upper body is consistent with the background. What is the reason? Thanks in advance.
![22_disp](https://user-images.githubusercontent.com/32475718/124476183-21d03d80-ddd5-11eb-9d71-1b4a83d3e1b2.jpeg)
![20_disp](https://user-images.githubusercontent.com/32475718/124476203-2563c480-ddd5-11eb-8204-128e73a20a36.jpeg)
![20_disp](https://user-images.githubusercontent.com/32475718/124476239-2c8ad280-ddd5-11eb-860a-0910135156fd.jpeg)
![22_disp](https://user-images.githubusercontent.com/32475718/124476274-3280b380-ddd5-11eb-8054-54f2b086f1fb.jpeg)

**Comment by mrharicot** [comment]
Hi,
Moving objects have always been challenging for the M model which will typically get the depth correct close to the ground and the accuracy will worsen as it goes up. 
Typically the head is the part that rarely gets reconstructed accurately.

I hope this helps!

**Comment by C-Anonymity** [comment]
Thank you for your careful answer :) I have a question: will the moving objects also be a problem during testing? Because the  M model only obtains the current image, it is unable to determine whether the object is moving or not, only that there is a object there. As a result, i think the moving objects only affects the training process and not the testing. Is it right?

**Comment by C-Anonymity** [comment]
@mrharicot

**Comment by mrharicot** [comment]
Since moving objects are an issue while training the M model, they typically have worse depth accuracy during testing as well as you can see here with the bike, but generally cars pose issues to the M model.
I hope this helps!

**Comment by C-Anonymity** [comment]
Thank you for your patient answer!
