### ISSUE TITLE
Left and right disparity

### ISSUE THREAD

**Issue by GabrielaM1** [nianticlabs/monodepth2#378]
At what point in code it happens and how the right disparity is predicted from the left image of the scene? I see in the code that the disparity has two dimensions, 0 and 1, for left and right, but in which part of the network is it set to be two dimensions?

Thank you in advance.

**Comment by daniyar-niantic** [comment]
Hi. The depth network only predicts disparity for the input image. This disparity is used to warp other images (stereo image or two frames in mono case).

Besides this, I don't know how to answer your question without further details. Could you please point to the snippets of code that you have questions about?
