### ISSUE TITLE
Confusion in evaluating pose

### ISSUE THREAD

**Issue by CodeKingWang** [nianticlabs/monodepth2#382]
` for i in range(0, num_frames - 1):
        local_xyzs = np.array(dump_xyz(pred_poses[i:i + track_length - 1]))
        gt_local_xyzs = np.array(dump_xyz(gt_local_poses[i:i + track_length - 1]))

        ates.append(compute_ate(gt_local_xyzs, local_xyzs))`
maybe some methods are applied in this syntax, can you give me some details about it? Thank you

**Comment by daniyar-niantic** [comment]
I don't think there are enough details in your question. I'm not even sure what are you asking exactly.
