### ISSUE TITLE
Copy rights

### ISSUE THREAD

**Issue by YJonmo** [nianticlabs/monodepth2#384]
Hi there,

Thanks for this great work.

Last year I was working on a depth+pose estimation framework for medical endoscopy and I used Monodepth2 as the main template. In brief, the unsupervised approach was not enough to have a decent result so I added extra functions so that the user can provide groundtruth camera poses to partially supervise the training. I could send the manuscript privately if you wanted. It is accepted for MICCAI 2021 but has not been published yet. 

The overall source code is about 90% or even more a copy from this repository.
I would like put the resulting source code for my work on github. 
How should I do it given the fact that it is 90% a copy from your work?
Can I upload it as it is or do I need to change the name of every variable and function?

Regards,
Yaqub

**Comment by hedoluna** [comment]
Hi Yaqub,
I'm very interested to see your code.

**Comment by YJonmo** [comment]
Thanks Orlando. I have to wait for the authors of Monodepth2 to reply first.

**Comment by daniyar-niantic** [comment]
Please read through the [License file](https://github.com/nianticlabs/monodepth2/blob/master/LICENSE)
especially clauses 2.2 and 3.

**Comment by YJonmo** [comment]
https://github.com/YJonmo/EndoMapNet
Is a variant of monodepth2 which can use the groundtruth poses if available for the training. 
The license file of the repository contains:

_Copyright © Niantic, Inc. 2018.

All rights reserved._

**Comment by daniyar-niantic** [comment]
Hi. Please update the license in your repository with an unmodified copy of this License as per clause 3.1
