### ISSUE TITLE
Obtain disparity in range (0,255)

### ISSUE THREAD

**Issue by LulaSan** [nianticlabs/monodepth2#385]
Hi,
 I am using your code to obtain disparity , in order to compute v-disparity. For this purpose I need that disparity ranges from 0 to 255 and this is what I did: 
```
 scaled_disp, depth = disp_to_depth(disp_resized, 0.1, 20)
 scaled_disp_resized_np = scaled_disp.squeeze().cpu().numpy()
disp255=(scaled_disp_resized_np*255).astype('uint8')

```

Do you think it is the correct way to do that? 
Thank you in advance
Luisa

**Comment by daniyar-niantic** [comment]
Hi. Yes, this will produce a uint8 visualization of the disparity.
