### ISSUE TITLE
Question on evaluate_depth.py

### ISSUE THREAD

**Issue by benhgm** [nianticlabs/monodepth2#386]
Hello, I am studying your code and I don't quite understand the cropping factors used in the following code block. Could you explain why these values are selected? Thank you so much

```

crop = np.array([0.40810811 * gt_height, 0.99189189 * gt_height,
                             0.03594771 * gt_width,  0.96405229 * gt_width]).astype(np.int32)

```

**Comment by daniyar-niantic** [comment]
@mrharicot might have more details, but I think these are chose to remove black pixels of rectified stereo images and to not have the hood of the car.

**Comment by daniyar-niantic** [comment]
See this repo: https://github.com/mrharicot/monodepth/blob/b76bee4bd12610b482163871b7ff93e931cb5331/utils/evaluate_kitti.py#L74

And this issue: https://github.com/shariqfarooq123/AdaBins/issues/10

This may be know as "Garg crop" in the literature.
