### ISSUE TITLE
why  I got better result than 0.130? abs_rel 0.111

### ISSUE THREAD

**Issue by alexanderuo** [nianticlabs/monodepth2#390]
I didn't use the pre-trained network, but I got better results than 0.130, why is that

train code:
`python train.py --model_name stereo_model/  --use_stereo --split eigen_full  --data_path /users/dataset/kitti_data`
result:
![image](https://user-images.githubusercontent.com/36657510/137302687-c34052b2-a81a-4e99-a3a0-f1fd5f37424e.png)

**Comment by mrharicot** [comment]
Hi,
what did you run for the evaluation? When evaluating a stereo model you should disable median scaling:
https://github.com/nianticlabs/monodepth2#-kitti-evaluation
