### ISSUE TITLE
Quertion about ‘’transformation_from_parameters‘’？

### ISSUE THREAD

**Issue by wqx854987945** [nianticlabs/monodepth2#391]
Hi!
As I know, the pose network only has to learn to predict transformations in one direction and get T-1→0 and T0→1, when inverting the camera-to-camera transformation matrix, your code is
'if invert: R=R.transpose(1,2) t*=-1'.
Question 1) : whether the code in the transformation should be 'if invert: R=R.transpose(1,2)，t=-np.dot(R, t)'? 
As I have just started to study this field, I look forward to your reply and correction！

**Comment by daniyar-niantic** [comment]
@mrharicot

**Comment by mrharicot** [comment]
Hi,
We actually handle this a couple lines after by flipping the order of the matrix multiplication.

https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/layers.py#L40-L43

I hope this helps!
