### ISSUE TITLE
evaluation on make3D

### ISSUE THREAD

**Issue by jsczzzk** [nianticlabs/monodepth2#392]
Hello:
I am going to evaluate the M model on Make3D dateset. Following these related issues: [A](https://github.com/nianticlabs/monodepth2/issues/89) and [B](https://github.com/mrharicot/monodepth/issues/154#issuecomment-393865771),  I wrote the following code：

```py
from layers import disp_to_depth
import networks
import cv2
import os 
import torch
import scipy.misc
from scipy import io
import numpy as np
load_weights_folder = '/home/monodepth2-master_test/mono_640x192'
main_path = '/media/make3D'
encoder_path = os.path.join(load_weights_folder, "encoder.pth")
decoder_path = os.path.join(load_weights_folder, "depth.pth")
encoder_dict = torch.load(encoder_path)
encoder = networks.ResnetEncoder(18, False)
depth_decoder = networks.DepthDecoder(encoder.num_ch_enc)

model_dict = encoder.state_dict()
encoder.load_state_dict({k: v for k, v in encoder_dict.items() if k in model_dict})
depth_decoder.load_state_dict(torch.load(decoder_path))

encoder.cuda()
encoder.eval()
depth_decoder.cuda()
depth_decoder.eval()
def compute_errors(gt, pred):
    rmse = (gt - pred) ** 2
    rmse = np.sqrt(rmse.mean())

    rmse_log = (np.log10(gt) - np.log10(pred)) ** 2
    rmse_log = np.sqrt(rmse_log.mean())

    abs_rel = np.mean(np.abs(gt - pred) / gt)

    sq_rel = np.mean(((gt - pred)**2) / gt)

    return abs_rel, sq_rel, rmse, rmse_log


with open(os.path.join(main_path, "make3d_test_files.txt")) as f:
    test_filenames = f.read().splitlines()
test_filenames = map(lambda x: x[4:], test_filenames)


depths_gt = []
images = []
ratio = 2
h_ratio = 1 / (1.33333 * ratio)
color_new_height = int(1704 / 2)
depth_new_height = 21
for filename in test_filenames:
    mat = io.loadmat(os.path.join(main_path, "Gridlaserdata", "depth_sph_corr-{}.mat".format(filename)))
    depths_gt.append(mat["Position3DGrid"][:,:,3])
    
    image = cv2.imread(os.path.join(main_path, "Test134", "img-{}.jpg".format(filename)))
    image = image[ int((2272 - color_new_height)/2):int((2272 + color_new_height)/2),:,:]
    images.append(image[:,:,::-1])
depths_gt_resized = map(lambda x: cv2.resize(x, (305, 407), interpolation=cv2.INTER_NEAREST), depths_gt)
depths_gt_cropped = map(lambda x: x[int((55 - 21)/2):int((55 + 21)/2),:], depths_gt)

depths_gt_cropped = list(depths_gt_cropped)
errors = []
with torch.no_grad():
    for i in range(len( images)):
        input_color = images[i]
        input_color = cv2.resize(input_color/255.0, (512, 256), interpolation=cv2.INTER_NEAREST)
        
        input_color = torch.tensor(input_color, dtype = torch.float).cuda().permute(2,0,1)[None,:,:,:]

                         
        output = depth_decoder(encoder(input_color))
        pred_disp, _ = disp_to_depth(output[("disp", 0)], 1e-3, 70)
        pred_disp = pred_disp.squeeze().cpu().numpy()
        depth_gt = depths_gt_cropped[i]
        depth_pred = 1 / pred_disp
        depth_pred = cv2.resize(depth_pred, depth_gt.shape[::-1], interpolation=cv2.INTER_NEAREST)
        mask = np.logical_and(depth_gt > 0, depth_gt < 70)
        depth_gt = depth_gt[mask]
        depth_pred = depth_pred[mask]
        depth_pred *= np.median(depth_gt) / np.median(depth_pred)
        depth_pred[depth_pred > 70] = 70
        errors.append(compute_errors(depth_gt, depth_pred))
    mean_errors = np.mean(errors, 0)

print(("{:>8} | " * 4).format( "abs_rel", "sq_rel", "rmse", "rmse_log"))
print(("{: 8.3f} , " * 4).format(*mean_errors.tolist()))
``` 
and i got the results as below:
![无标题](https://user-images.githubusercontent.com/32475718/137839869-71bbad40-48c0-4429-8041-e01518222957.png)
This results are a bit different from the data in the paper
![image](https://user-images.githubusercontent.com/32475718/137840030-e2ec5e7e-0ffe-4f32-ae17-8fc5991ddc75.png)
Is there a problem with my code?

**Comment by daniyar-niantic** [comment]
@JamieWatson683 @mrharicot any hints?

**Comment by bizheyandebing** [comment]
> Hello: I am going to evaluate the M model on Make3D dateset. Following these related issues: [A](https://github.com/nianticlabs/monodepth2/issues/89) and [B](https://github.com/mrharicot/monodepth/issues/154#issuecomment-393865771), I wrote the following code：
> 
> ```python
> from layers import disp_to_depth
> import networks
> import cv2
> import os 
> import torch
> import scipy.misc
> from scipy import io
> import numpy as np
> load_weights_folder = '/home/monodepth2-master_test/mono_640x192'
> main_path = '/media/make3D'
> encoder_path = os.path.join(load_weights_folder, "encoder.pth")
> decoder_path = os.path.join(load_weights_folder, "depth.pth")
> encoder_dict = torch.load(encoder_path)
> encoder = networks.ResnetEncoder(18, False)
> depth_decoder = networks.DepthDecoder(encoder.num_ch_enc)
> 
> model_dict = encoder.state_dict()
> encoder.load_state_dict({k: v for k, v in encoder_dict.items() if k in model_dict})
> depth_decoder.load_state_dict(torch.load(decoder_path))
> 
> encoder.cuda()
> encoder.eval()
> depth_decoder.cuda()
> depth_decoder.eval()
> def compute_errors(gt, pred):
>     rmse = (gt - pred) ** 2
>     rmse = np.sqrt(rmse.mean())
> 
>     rmse_log = (np.log10(gt) - np.log10(pred)) ** 2
>     rmse_log = np.sqrt(rmse_log.mean())
> 
>     abs_rel = np.mean(np.abs(gt - pred) / gt)
> 
>     sq_rel = np.mean(((gt - pred)**2) / gt)
> 
>     return abs_rel, sq_rel, rmse, rmse_log
> 
> 
> with open(os.path.join(main_path, "make3d_test_files.txt")) as f:
>     test_filenames = f.read().splitlines()
> test_filenames = map(lambda x: x[4:], test_filenames)
> 
> 
> depths_gt = []
> images = []
> ratio = 2
> h_ratio = 1 / (1.33333 * ratio)
> color_new_height = int(1704 / 2)
> depth_new_height = 21
> for filename in test_filenames:
>     mat = io.loadmat(os.path.join(main_path, "Gridlaserdata", "depth_sph_corr-{}.mat".format(filename)))
>     depths_gt.append(mat["Position3DGrid"][:,:,3])
>     
>     image = cv2.imread(os.path.join(main_path, "Test134", "img-{}.jpg".format(filename)))
>     image = image[ int((2272 - color_new_height)/2):int((2272 + color_new_height)/2),:,:]
>     images.append(image[:,:,::-1])
> depths_gt_resized = map(lambda x: cv2.resize(x, (305, 407), interpolation=cv2.INTER_NEAREST), depths_gt)
> depths_gt_cropped = map(lambda x: x[int((55 - 21)/2):int((55 + 21)/2),:], depths_gt)
> 
> depths_gt_cropped = list(depths_gt_cropped)
> errors = []
> with torch.no_grad():
>     for i in range(len( images)):
>         input_color = images[i]
>         input_color = cv2.resize(input_color/255.0, (512, 256), interpolation=cv2.INTER_NEAREST)
>         
>         input_color = torch.tensor(input_color, dtype = torch.float).cuda().permute(2,0,1)[None,:,:,:]
> 
>                          
>         output = depth_decoder(encoder(input_color))
>         pred_disp, _ = disp_to_depth(output[("disp", 0)], 1e-3, 70)
>         pred_disp = pred_disp.squeeze().cpu().numpy()
>         depth_gt = depths_gt_cropped[i]
>         depth_pred = 1 / pred_disp
>         depth_pred = cv2.resize(depth_pred, depth_gt.shape[::-1], interpolation=cv2.INTER_NEAREST)
>         mask = np.logical_and(depth_gt > 0, depth_gt < 70)
>         depth_gt = depth_gt[mask]
>         depth_pred = depth_pred[mask]
>         depth_pred *= np.median(depth_gt) / np.median(depth_pred)
>         depth_pred[depth_pred > 70] = 70
>         errors.append(compute_errors(depth_gt, depth_pred))
>     mean_errors = np.mean(errors, 0)
> 
> print(("{:>8} | " * 4).format( "abs_rel", "sq_rel", "rmse", "rmse_log"))
> print(("{: 8.3f} , " * 4).format(*mean_errors.tolist()))
> ```
> 
> and i got the results as below: ![无标题](https://user-images.githubusercontent.com/32475718/137839869-71bbad40-48c0-4429-8041-e01518222957.png) This results are a bit different from the data in the paper ![image](https://user-images.githubusercontent.com/32475718/137840030-e2ec5e7e-0ffe-4f32-ae17-8fc5991ddc75.png) Is there a problem with my code?

Hello, can you share this file("make3d_test_files.txt") with me? I downloaded the data set, but I didn't find this file. Thank you very much

**Comment by IkeFwd** [comment]
I also encountered the same problem, did you solve it?

**Comment by daniyar-niantic** [comment]
I'm not familiar with this evaluation, but I'm concerned about this line:
```pred_disp, _ = disp_to_depth(output[("disp", 0)], 1e-3, 70)```
The min-max depth range should be the same as used for training this model.

**Comment by IkeFwd** [comment]
> I'm not familiar with this evaluation, but I'm concerned about this line: `pred_disp, _ = disp_to_depth(output[("disp", 0)], 1e-3, 70)` The min-max depth range should be the same as used for training this model.


I tried changing the max depth to 80 (which was used to train this model), but the results didn't get any better.

![image](https://user-images.githubusercontent.com/29300743/165877465-4a3362df-0cc6-42f8-9790-35c6e6a4abc8.png)

**Comment by daniyar-niantic** [comment]
Ok. Another thing to check is image downsampling interpolation method:
```
input_color = cv2.resize(input_color/255.0, (512, 256), interpolation=cv2.INTER_NEAREST)
```
to 
```
input_color = cv2.resize(input_color/255.0, (512, 256), interpolation=cv2.INTER_AREA)
```

**Comment by jsczzzk** [comment]
Thank you for your patient answers!

**Comment by daniyar-niantic** [comment]
@jsczzzk So, have you replicated the results?

**Comment by zxcqlf** [comment]
I think his image resolution is wrong

> @jsczzzk So, have you replicated the results?
I think his input image resolution is wrong?

**Comment by daniyar-niantic** [comment]
> I think his image resolution is wrong
> 
> > @jsczzzk So, have you replicated the results?
> > I think his input image resolution is wrong?

What should the resolution be?

**Comment by jsczzzk** [comment]
I got the close results, thank you so much!

**Comment by daniyar-niantic** [comment]
@jsczzzk Thank you for confirming!

**Comment by zxcqlf** [comment]
> > I think his image resolution is wrong
> > > @jsczzzk So, have you replicated the results?
> > > I think his input image resolution is wrong?
> 
> What should the resolution be?

640*192, not 512*256, Ithink.

**Comment by IkeFwd** [comment]
@jsczzzk ，Could you please give the complete code? thank you very much

**Comment by daniyar-niantic** [comment]
@jsczzzk For posterity, could you share what changes were needed to replicate the result? Was it downsampling interpolation that made a difference?

**Comment by zxcqlf** [comment]
@jsczzzk what's your results? my result is :
   0.321 ,    3.378 ,    7.252 ,    0.163 ,

**Comment by jsczzzk** [comment]
I think the quantitative evaluation on Make3D is related to many aspects, such as the downsampling interpolation, input resolution, and environment. Each aspect may greatly affect the results. So, i just get the close results. @zxcqlf

**Comment by jsczzzk** [comment]
I think the main is that the  resolution of ground truth is too small.

**Comment by jsczzzk** [comment]
I think the main reason is that the resolution of ground truth is too small.

**Comment by zxcqlf** [comment]
@jsczzzk Agree, and since the model is trained by 640x192, so I think the test image should be resized to the same resolution, and it may help to get a better result.

**Comment by daniyar-niantic** [comment]
Right, so the code should look something like this:
```
with torch.no_grad():
    for i in range(len( images)):
        input_color = images[i]
        input_color = cv2.resize(input_color/255.0, (640, 192), interpolation=cv2.INTER_AREA)
        input_color = torch.tensor(input_color, dtype = torch.float).cuda().permute(2,0,1)[None,:,:,:]                         
        output = depth_decoder(encoder(input_color))
        pred_disp, _ = disp_to_depth(output[("disp", 0)], 0.1, 100)
        pred_disp = pred_disp.squeeze().cpu().numpy()
        depth_gt = depths_gt_cropped[i]
        depth_pred = 1 / pred_disp
        depth_pred = cv2.resize(depth_pred, depth_gt.shape[::-1], interpolation=cv2.INTER_NEAREST)
```
i.e. the network sees input images at training resolution and the predicted depth is downsampled to benchmark resolution.

**Comment by daniyar-niantic** [comment]
And @mrharicot's answer [here](https://github.com/mrharicot/monodepth/issues/154#issuecomment-393865771) which says that Make3D images were resized to 512x256, is actually referring procedure in the first Monodepth, rather than Monodepth2.

@mrharicot would still need to confirm if procedure changed between two papers.

**Comment by jsczzzk** [comment]
@daniyar-niantic  Thank you for your patient answer! You are so kindly with the help to me!

**Comment by zxcqlf** [comment]
@daniyar-niantic Yeah, for Monodepth, the model seems be trained with a resolution of 512x256

**Comment by IkeFwd** [comment]
@zxcqlf  Does the size of ground truth also need to be resized to 640*192?  thank you very much

**Comment by zxcqlf** [comment]
@bizheyandebing No for mine. Just follow the previous evaluation methods, resize the predicted disp/depth to the same resolution as the GT.

**Comment by IkeFwd** [comment]
@bizheyandebing 
“depths_gt_resized = map(lambda x: cv2.resize(x, (305, 407), interpolation=cv2.INTER_NEAREST), depths_gt)
depths_gt_cropped = map(lambda x: x[int((55 - 21) / 2):int((55 + 21) / 2), :], depths_gt)”

I re-checked the code and depths_gt_resized doesn't seem to be used, so I'm not sure if there is something wrong with this code, can you share your evaluation code if you can? Greatful

**Comment by zxcqlf** [comment]
@bizheyandebing  all is the scame with @jsczzzk except:



```
with torch.no_grad():
    for i in range(len( images)):
        input_color = images[i]
        input_color =  cv2.resize(input_color/255.0, (640, 192), interpolation=cv2.INTER_NEAREST)#<----1
        input_color = torch.tensor(input_color, dtype = torch.float).permute(2,0,1)[None,:,:,:]
        output = depth_decoder(encoder(input_color))
        pred_disp,_ = disp_to_depth(output[("disp", 0)], 0.1, 100) #<---2
        pred_disp = pred_disp.squeeze().cpu().numpy()
        depth_gt = depths_gt_cropped[i]
        depth_pred = 1 / pred_disp
        depth_pred = cv2.resize(depth_pred, depth_gt.shape[::-1], interpolation=cv2.INTER_NEAREST)
        mask = np.logical_and(depth_gt > 0, depth_gt < 70)
        depth_gt = depth_gt[mask]
        depth_pred = depth_pred[mask]
        depth_pred *= np.median(depth_gt) / np.median(depth_pred)
        depth_pred[depth_pred > 70] = 70
        errors.append(compute_errors(depth_gt, depth_pred))
    mean_errors = np.mean(errors, 0)
    ```

**Comment by IkeFwd** [comment]
@zxcqlf  thank you very much,

and attach the test results after my revised code

![image](https://user-images.githubusercontent.com/29300743/168846119-06dcebb2-74e9-4c59-b424-2b7a6666f6f3.png)

**Comment by daniyar-niantic** [comment]
Does it matter if images are resized with `cv2.INTER_NEAREST` or `cv2.INTER_AREA`? Depending on the original resolution of images it could be significant difference.

**Comment by zxcqlf** [comment]
@daniyar-niantic  Yeah, they result in significant different results, and the results of cv2.INTER_NEAREST seem be better than that of cv2.INTER_AREA

**Comment by IkeFwd** [comment]
@daniyar-niantic  Below is the result after using cv2.INTER_AREA。

![image](https://user-images.githubusercontent.com/29300743/168850441-c0faceb9-2869-4891-825e-4f0319a13303.png)

**Comment by daniyar-niantic** [comment]
Great, thank you @bizheyandebing !

I think this issue is now truly resolved. Thanks everyone!
