### ISSUE TITLE
problem on the depth map of road

### ISSUE THREAD

**Issue by xsu-yy** [nianticlabs/monodepth2#393]
Dear author:
        Thank you for the excellent work.
        I am trainning the net on my own dataset. my data are some infrared images in the driving scenarios and the fps is 12（oringin fps is 24,i have downsampled it to 12）. i have changed the camera intrinsic, and removed images containing dynamic objects. 
        I trained my model with the pretrained model (mono_1024x320) and employed the train results on my data.however , the depth map on the road is incorrect and not consistency.i do not know why,what can i do for this problem?
![image](https://user-images.githubusercontent.com/75834235/137885998-c536914b-aed0-48c8-aee2-bd7f2e42d800.png)
![image](https://user-images.githubusercontent.com/75834235/137886066-b8aa0031-c6c5-443e-9eb5-61390ba75dfd.png)

**Comment by libetter0913** [comment]
I have the same problem as you, have you solved it?

**Comment by daniyar-niantic** [comment]
Hi. In your infrared images the road has uniform color, so the network has problems estimating correct depth for these regions. You could try training with a smaller resolution images.
