### ISSUE TITLE
The way to get the real depth 

### ISSUE THREAD

**Issue by hcv1027** [nianticlabs/monodepth2#394]
I modified the `test_simple.py` to verify the average depth at interesting region.
Here is what I modify the code.

```python
if args.pred_metric_depth:
    name_dest_npy = os.path.join(output_directory, "{}_depth.npy".format(output_name))
    metric_depth = STEREO_SCALE_FACTOR * depth.cpu().numpy()
    np.save(name_dest_npy, metric_depth)
    
    # Modify start
    top = args.depth_pos[0]
    left = args.depth_pos[1]
    w = args.depth_pos[2]
    h = args.depth_pos[3]
    print("{}, {}, {}, {}".format(top, left, w, h))
    
    disp_resized = torch.nn.functional.interpolate(
        disp, (original_height, original_width), mode="bilinear", align_corners=False)
    _, depth_resized = disp_to_depth(disp_resized, 0.1, 100)
    metric_depth_resized = STEREO_SCALE_FACTOR * depth_resized.cpu().numpy()
    sub_metric_depth_resized = metric_depth_resized[:, :, top:top+h, left:left+w]
    print("target depth: {}".format(np.mean(sub_metric_depth_resized)))
    # Modify end
```

Here is my sample image
![temp](https://user-images.githubusercontent.com/12728923/138071130-f24c473f-6c68-4b6f-ba29-d707eac57225.jpg)

I use the laser distance sensor to measure the real depth  in the region of blue rectangle. It should be 4.0 meters.
![PXL_20211020_081156966](https://user-images.githubusercontent.com/12728923/138071827-6c36bff5-69b8-48be-b547-fd85de32249d.jpg)

But I use the pre-trained model to predict, the output is about 13.45 meters
```bash
python test_simple.py --image_path assets/PXL_20211020_081241033.jpg --model_name stereo_1024x320 --pred_metric_depth --depth_pos 1320 2096 10 10
```

Is the way I use to get the depth of interesting region correct?

**Comment by giangdao1402** [comment]
> I modified the `test_simple.py` to verify the average depth at interesting region. Here is what I modify the code.
> 
> ```python
> if args.pred_metric_depth:
>     name_dest_npy = os.path.join(output_directory, "{}_depth.npy".format(output_name))
>     metric_depth = STEREO_SCALE_FACTOR * depth.cpu().numpy()
>     np.save(name_dest_npy, metric_depth)
>     
>     # Modify start
>     top = args.depth_pos[0]
>     left = args.depth_pos[1]
>     w = args.depth_pos[2]
>     h = args.depth_pos[3]
>     print("{}, {}, {}, {}".format(top, left, w, h))
>     
>     disp_resized = torch.nn.functional.interpolate(
>         disp, (original_height, original_width), mode="bilinear", align_corners=False)
>     _, depth_resized = disp_to_depth(disp_resized, 0.1, 100)
>     metric_depth_resized = STEREO_SCALE_FACTOR * depth_resized.cpu().numpy()
>     sub_metric_depth_resized = metric_depth_resized[:, :, top:top+h, left:left+w]
>     print("target depth: {}".format(np.mean(sub_metric_depth_resized)))
>     # Modify end
> ```
> 
> Here is my sample image ![temp](https://user-images.githubusercontent.com/12728923/138071130-f24c473f-6c68-4b6f-ba29-d707eac57225.jpg)
> 
> I use the laser distance sensor to measure the real depth in the region of blue rectangle. It should be 4.0 meters. ![PXL_20211020_081156966](https://user-images.githubusercontent.com/12728923/138071827-6c36bff5-69b8-48be-b547-fd85de32249d.jpg)
> 
> But I use the pre-trained model to predict, the output is about 13.45 meters
> 
> ```shell
> python test_simple.py --image_path assets/PXL_20211020_081241033.jpg --model_name stereo_1024x320 --pred_metric_depth --depth_pos 1320 2096 10 10
> ```
> 
> Is the way I use to get the depth of interesting region correct?

can you give me the code that return depth_pos
