### ISSUE TITLE
Stereo Vision vs Monocular Depth Estimation

### ISSUE THREAD

**Issue by songshan0321** [nianticlabs/monodepth2#395]
Such a great and impactful work. I have some questions here.
1. Is it possible for a CNN based monocular depth estimation method to surpass the traditional stereo matching method? 
2. If not, is there any advantage of CNN based monocular depth estimation over the traditional stereo matching method?

Thanks in advanced!

**Comment by daniyar-niantic** [comment]
1. Probably no.
2. Yes, you can use monocular depth network when you only have 1 image. Stereo matching method can only be used when you have stereo images.
