### ISSUE TITLE
A question about generalization ability using self-supervised algorithm like monodepth2

### ISSUE THREAD

**Issue by hcv1027** [nianticlabs/monodepth2#396]
Hi, thanks for the amazing work @mrharicot  and team!

I'm a beginner of depth estimation research areas. I have a question about the generalization part. I am not very sure about does self-supervised algorithm like monodepth2 or [packnet-sfm](https://github.com/TRI-ML/packnet-sfm) generalize well to different camera. I mean that if I train the model using  monocular camera video dataset captured from camera_1, is it possible to adopt this trained model to work with another camera _2 which may has different intrinsic? Since according to the source code, monodepth2 will use camera's intrinsic parameters to transform a depth image into a point-cloud in the training phase. Will the trained model have a dependency on camera's intrinsic parameters?

**Comment by daniyar-niantic** [comment]
Hi.

Good question and good insight. Indeed, generalization across cameras is likely to be limited if only few intrinsics were used during training. If estimated depth is relative, and there is sufficient number of training examples with varying intrinsics, like https://github.com/isl-org/MiDaS , then generalization is more likely.

Please check CAM-Convs paper as it address the issue that you raised: https://github.com/jmfacil/camconvs
