### ISSUE TITLE
Input size, proportions  similar to the original of KITTI Vs Monodepth1

### ISSUE THREAD

**Issue by LulaSan** [nianticlabs/monodepth2#398]
Hi,
I was wondering why do you fed your network with an input 192x640 with a proportion of 3.33 , really similar to the KITTI one, while in monodepth 1 you used to feed the network with 256x512 ( proportion=2). The results are in both cases evaluated resizing the disparities back to the original shape.
 I was wondering if this affects the performance on monodepth 1 and if it would be better to fed the network with image with these proportions.
( Obviously, it would have been a big constraint for who wants to train the network is a custom dataset in an indoor environment... )
Anyway, do you think that it would have be better to preserve the same proportions with training input and test input? In order to reduce distorsion

**Comment by daniyar-niantic** [comment]
Hi.

The image size is chosen to have minimal distortion in aspect ratio, have a large batch size on GPU and have the image resolution suitable for network architecture.

Yes, the image resolution has impact on performance, e.g. in the paper there is a difference in performance between 192x640 and 320x1024. The resolution of 192x640 is probably more suitable for Kitti, but 256x512 was also used in some prior works before monodepth1.
