### ISSUE TITLE
Project3D error

### ISSUE THREAD

**Issue by chapa17** [nianticlabs/monodepth2#399]
Hello,

I am trying to test an image from own dataset using test_simple.py. I want to generate 3D point cloud using the depth map and color pixel. I am trying to use points generated from `backProject3D` and pixel co-ordinates from `project3D` classes respectively to get the RGB color pixel. The issue I am facing is the result of `project3D` class is in floating values which is a concern for me. 

Anyone having any idea if it is correct ?

Thank you!

**Comment by daniyar-niantic** [comment]
Hi. project3D is used to project 3D points into image space. The projected coordinates would be floating point, not integer.

I think what you want to use are coordinates and colors of pixels that is fed to depth network. So, you won't need project3D for that use case.
