### ISSUE TITLE
Will adam.pth and batch_size affect my model training？

### ISSUE THREAD

**Issue by jzwqaq** [nianticlabs/monodepth2#401]
Hi, I have two questions. Why only depth.pth, encoder.pth, pose.pth and pose_encoder.pth, but not adam.pth are provided in the pre-training model, which makes me report "Cannot find Adam weights so Adam is randomly initialized" message. Does the lack of adam.pth affect my training?  Because I have slightly tweaked the code and further trained my model with the pre-trained model, but the results did not improve. It makes me wonder if the lack of adam.pth in the pretrained model will have a bad effect on my model training
Also, limited by my computing device, my batch_size can only be given to 1. Will this have an impact on my training. Previously I trained the original code with no pre-trained model using batch_size=1 and the results were poor. Is this right?
thank u ！！！

**Comment by daniyar-niantic** [comment]
Hi. Yes, batch size has a big impact on final model quality. Adam.pth is needed for continuing to train from a certain checkpoint, but it is not needed to train from scratch.
