### ISSUE TITLE
Performance of pose estimation

### ISSUE THREAD

**Issue by YagumaLi** [nianticlabs/monodepth2#404]
Hi! 
I've read your paper recently, and thanks a lot for your excellent contributions.
Monodepth2 impressed me with the depth estimation performance, and I also noticed that the pose estimation might not get the results as good as depth estimation. 
So, I wonder why it can perform so well on depth estimation without the accurate relative pose of the camera.
I hope it won't bother you and look forward to your reply.

**Comment by daniyar-niantic** [comment]
Hi. The models are trained with 2 reference frames for each target frame, so if only one of the frames has bad relative pose it should not affect the photometric loss and depth module. Thus, depth network does not suffer from problematic poses.
