### ISSUE TITLE
improvement: learn intrinsics jointly with training

### ISSUE THREAD

**Issue by d4l3k** [nianticlabs/monodepth2#408]
Hi, I made a small improvement to this which seems to work reasonably well if the camera intrinsics aren't well known or you only have a rough estimate of the fov/focal lengths. 

You can add a new learned parameter for the focal lengths (horizontal / vertical) and the center.

in init:
```py
# initial focal length to use
focal_len = 807.1375
self.K = torch.tensor([focal_len/640, focal_len/416, 0.5, 0.5],
        dtype=torch.float32).to(self.device).requires_grad_()

self.parameters_to_train = [self.K]
```

in generate_images_pred

```py
K = torch.eye(4, device=self.device, dtype=torch.float32)
K[0, 0] = self.K[0]
K[1, 1] = self.K[1]
K[0, 2] = self.K[2]
K[1, 2] = self.K[3]
K[0, :] *= 640 // (2 ** source_scale)
K[1, :] *= 416 // (2 ** source_scale)
inv_K = torch.linalg.pinv(K)


cam_points = self.backproject_depth[source_scale](depth, inv_K.unsqueeze(0))
pix_coords = self.project_3d[source_scale](cam_points, K.unsqueeze(0), T)
```

I haven't fully tested how a very incorrect the initial intrinsics can affect the convergence but this seems to work reasonably well.

Inspired from https://arxiv.org/abs/1904.04998 which does this on a per video basis

**Comment by AllenMao** [comment]
Feel that the initial value is more important.  e.g. estimated by FOV ...

**Comment by daniyar-niantic** [comment]
Hi.
I'm not sure if this should be merged into this repository as the code in this repo is shared for reproduction purposes.
