### ISSUE TITLE
Absolute depth or relative depth?

### ISSUE THREAD

**Issue by Richard-wang85** [nianticlabs/monodepth2#411]
Hello! Thank you for your splendid work! But I have some questions about what we get is absolute depth or relative depth by using your model? If we could get absolute depth, could you tell me how can I get these data? Thank you for your reply!

**Comment by dantkz** [comment]
Hi. Outputs of models trained with stereo data should have absolute depth. Mono-only trained models would not have absolute depth and depth values would be in a scaleless space.

**Comment by kzamzam** [comment]
If what we get is the absolute depth, then why is scaling needed when using --eval_stereo. In the read me it says you multiple by a factor of 5.4, to scale the depth to a 54cm baseline.

**Comment by daniyar-niantic** [comment]
The multiple of 5.4 is a fixed constant that was applied during training and needs to be applied during testing for consistency. It is independent of the scene scale. It is mainly there for better output range for training.

**Comment by daniyar-niantic** [comment]
See https://github.com/nianticlabs/monodepth2/issues/30 and https://github.com/nianticlabs/monodepth2/issues/314

**Comment by kzamzam** [comment]
Ok so this means in case I am retraining on my own dataset with a different baseline, I have to change this factor in the training code? Thanks for including the issues, I understand that now. In my case, I am retraining the network to reuse it in the DF-VO system, I am not sure wether they multiply by a scaling factor in their implementation. So in that case, I will change the 0.1, to 0.12, as 12 cm is my baseline.

**Comment by daniyar-niantic** [comment]
Yes, you should set baseline variable to your dataset baseline. However, the scale factor is a separate variable that can be tuned if the model is not converging.
