### ISSUE TITLE
Nonconvergence / texture-copy on custom dataset with only stereo training data

### ISSUE THREAD

**Issue by kebijuelun** [nianticlabs/monodepth2#417]
Hello, thanks for your wonderful work.

【problem】
- I met a nonconvergence and texture-copy problem when training on custom stereo training data (only stereo pairs have been used).
![image](https://user-images.githubusercontent.com/29164878/155686382-b240a3b2-1b46-4f4b-9449-ee3d1dcddb66.png)
![image](https://user-images.githubusercontent.com/29164878/155686398-d992d363-0c21-4c54-ab0a-77076db3358b.png)
- I found some similar issues, but there are no solutions:
  - https://github.com/nianticlabs/monodepth2/issues/325
  - https://github.com/nianticlabs/monodepth2/issues/346
 - when use same training processure on KITTI, the output looks reasonable
![image](https://user-images.githubusercontent.com/29164878/155687799-e4be0241-ca24-4220-9317-224fc728fc39.png)
![image](https://user-images.githubusercontent.com/29164878/155687817-357c1849-2f86-4f39-ab25-ecb0734e7bed.png)

【experiments】
- when disable automask，the texture-copy (from rgb) phenomenon will be more obvious.

![image](https://user-images.githubusercontent.com/29164878/155686682-30aee91d-0623-4d16-bb13-0f29d77177f4.png)
![image](https://user-images.githubusercontent.com/29164878/155686702-a05e7967-7d8e-4488-97ad-76731817f587.png)

- when use smaller smooth coefficient, the texture-copy (from rgb) phenomenon will be more obvious.
  - smooth coefficient: 1e-5
![image](https://user-images.githubusercontent.com/29164878/155687166-391f48c6-9119-45d6-8009-1c67292c1889.png)
  - smooth coefficient: 1e-1
![image](https://user-images.githubusercontent.com/29164878/155687213-a365d51d-0cc9-4970-a531-b3a90dc22c15.png)
- I also found that [baseline value will influence the training stability](https://github.com/nianticlabs/monodepth2/issues/325#issuecomment-814370844), but I have no idea about how to choose a suitable baseline for our own dataset.

----
So does anyone have a solution on the texture-copy problem？ or anyone have some suggestions when training with only stereo data？
Thanks for any help!

**Comment by dantkz** [comment]
Hi. The texture-copy artifacts may appear due to a number of issues: high resolution of images, bad calibration quality, etc. 

If your task is to compute depth for your stereo images, maybe you could check deep stereo matching approaches?
