### ISSUE TITLE
cloudy depth prediction in stereo mode [custom data]

### ISSUE THREAD

**Issue by sabir-1010** [nianticlabs/monodepth2#420]
Trying to train with custom data set(1280x960) for stereo mode. 

1. Normalized the Intrinsic value self.K as mentioned.
2. used 640x480 for training parameter.
3. Below is a sample dataset
![individualImage](https://user-images.githubusercontent.com/90294351/157162611-9f092702-ad35-425a-a01d-179c918af0f0.png)
4. predicted depths in the tensorboard output look like the following
![individualImage](https://user-images.githubusercontent.com/90294351/157162734-3a03964e-8ea7-4ee6-8202-42af7f2e7e3a.png)
5. tried with different resolution. but same depth prediction. Wondering what might cause this problem? 

N.B. training with Kitti data set work.

**Comment by libetter0913** [comment]
I have the same problem as you, have you solved it?

**Comment by dantkz** [comment]
Hi. Are your stereo pairs calibrated? Are your images correctly loaded as left and right images?

**Comment by sabir-1010** [comment]
1. **Are your stereo pairs calibrated? :** Yes. My stereo pairs calibrated is calibrated. However, Left and right have slightly different intrinsic value. Which Intrinsic value self.K should I load?
2. **Are your images correctly loaded as left and right images?:** Yes. I am certain that they are loaded properly.

**Comment by daniyar-niantic** [comment]
1. Once stereo camera is calibrated, it needs to be rectified so that intrinsics of two images are the same, and the pixels are scanline aligned. More details could be found here: https://python.plainenglish.io/the-depth-i-stereo-calibration-and-rectification-24da7b0fb1e0
