### ISSUE TITLE
training with the visual odometry pose

### ISSUE THREAD

**Issue by chlien** [nianticlabs/monodepth2#422]
Hello, I try to use the visual odometry ground truth to replace the "T" of the generate_images_pred method.
I use the np.dot(np.linalg.inv()) and np.linalg.inv(np.dot(np.linalg.inv())) to convert the absolute pose to the relative pose
t->t'. 
And then I disable the use_pose_net and random flip to train on the kitti_odom dataset. but the result is very bad like the below figure.

![image](https://user-images.githubusercontent.com/69669658/163496774-d6c82e9d-e0c6-4534-b1f7-da74680d33b3.png)

Could you tell me which step I was wrong?

**Comment by daniyar-niantic** [comment]
Hi. Please check related issues like https://github.com/nianticlabs/monodepth2/issues/237
