### ISSUE TITLE
why my disparity of image  is vey high? for small far away object

### ISSUE THREAD

**Issue by akashAD98** [nianticlabs/monodepth2#424]
i build model which can predict whether object is close,moderate or far away..
im getting good results, but in few cases its not performing well, can you please explain why the disparity of small (far away ) object is high?

my object detection model detecting person & car (they are very small)

![image](https://user-images.githubusercontent.com/62583018/164427827-9a259de4-c63b-47b8-b4a4-bf56a574002a.png)

![image](https://user-images.githubusercontent.com/62583018/164428277-77d050c3-ce43-48a7-895d-d97750096010.png)

object which is very far away having very less mean disparity, but for this image im getting high values

   ```
 disp_resized = torch.nn.functional.interpolate(disp,
    (original_height, original_width), mode="bilinear", align_corners=False)
    mean_disparity=disp_resized
    vmax = np.percentile(disp_resized_np, 95)
    mean_disp_glo = disp_resized_np.mean()
    std_disp_glo = disp_resized_np.std()
```

help is really appreciated @daniyar-niantic  . Thanks

**Comment by yeqianchen** [comment]
Hi, how did you get the absolute depth based on the relative depth? I'm currently working on converting a relative depth map to an absolute depth map. thanks！

**Comment by daniyar-niantic** [comment]
Did you train this model on your training data? The KITTI model is far from perfect, so some error is expected. You also would probably get better predictions from stereo-trained model than video-only model.

**Comment by akashAD98** [comment]
i haven't trained any model, I just tried pretrained mono_640x192 model which is availble,
my goal is to get the depth of each object which is presemnt in the image, so first I have tried yolo for object detection & pass bbox to monodepth to get disparityof object, based on that I have created the rule-based system, if the disparity is very less than mean & standard disparity my object is far away like this.

**Comment by daniyar-niantic** [comment]
Do you mean that you pass crops of the input image to monodepth model? If so, then it is not likely to work well. Monodepth network tries to understand the depth of objects based on visual cues like pixel size of objects and vanishing points. If you crop individual objects from the image, all those cues are not available to the network. You should pass the whole image to network and then crop from estimated depthmap.

**Comment by akashAD98** [comment]
yes im doing same,still getting issues ,I'm passing whole image to monodepth ,& im getting disparity of the whole image, but my goal is to calculate depth of each object,so after that, i cropped my image using object detection.
do you have any sample code,so i can understand better .thanks @daniyar-niantic

**Comment by daniyar-niantic** [comment]
`so after that, i cropped my image using object detection.`
Are you cropping disparity map or the color image?

**Comment by akashAD98** [comment]
yes, can you review my code? I'm sharing google colab here, let me know what mistakes I have done @daniyar-niantic

**Comment by eugeneYz** [comment]
> yes, can you review my code? I'm sharing google colab here, let me know what mistakes I have done @daniyar-niantic

Have you figured out this problem? I am doing the same work, thank u!

**Comment by akashAD98** [comment]
@eugeneYz not yet

**Comment by Ravenclaw-Hcmut** [comment]
> @eugeneYz not yet

Hello, 

I found that Google Colab doesn't have python 3.6 anymore, and I get error when training on colab.

Can you share details about your environment (version of python, pytorch, torchvision, opencv, CUDA, using cudnn or not, ...) and the commands that you used to install some packets to train monodepth2 when using Google Colab? 

Thank you.

**Comment by daniyar-niantic** [comment]
Hi @akashAD98 ,

You should check if you are cropping a depth map or disparity map. The disparity is `1/depth`, so for far away objects the disparity value will be high.
