### ISSUE TITLE
Is this method applicable to panoramic photos？

### ISSUE THREAD

**Issue by 375000384** [nianticlabs/monodepth2#425]
I gets some panoramic photos with Insta360 one, and want to compute the position(x,y,z) and pose(k,p,r) of the panoramic photos.  Is this method applicable to panoramic photos?
Thank you!

**Comment by daniyar-niantic** [comment]
I doubt you will have usable depthmaps from this method unless you train from panoramic images.

I suggest to check https://manurare.github.io/360monodepth/ or related projects.
