### ISSUE TITLE
Is there a problem with the description of Figure 6?

### ISSUE THREAD

**Issue by IkeFwd** [nianticlabs/monodepth2#428]
![image](https://user-images.githubusercontent.com/29300743/165732572-3c6deefe-54a5-4cf4-b2b8-242ae1bddc28.png)
Should the text section marked in yellow be unsupervision?

**Comment by daniyar-niantic** [comment]
Methods trained from data supervision without ground truth labels are called unsupervised. In this case the supervision is coming from a single camera video data, there is no stereo or lidar data available. So, this caption is correct.

**Comment by IkeFwd** [comment]
> 
Oh, I see what you mean, so the method used here is the same as before, self-supervised method. thanks a lot for your answer
