### ISSUE TITLE
Inference on custom training set fails

### ISSUE THREAD

**Issue by joyqoo** [nianticlabs/monodepth2#429]
Hi, I used your architecture to train my own dataset, but the results are not as expected, the evaluation results and images are quite poor.

Illogical oddities occur when inferring images.

Could you please give me some advice? Thank you!

<img width="592" alt="image" src="https://user-images.githubusercontent.com/30586145/166509320-e34d449b-b34a-4b7b-984d-aa5c4cf23210.png">
<img width="638" alt="image" src="https://user-images.githubusercontent.com/30586145/166509721-86023852-608a-45e8-97b0-667fdd45d27e.png">

**Comment by daniyar-niantic** [comment]
Hi. There are not enough details to know how to help. Are you training from video only? What is the resolution of your images? Have you changed intrinsics in the dataloader? etc.
