### ISSUE TITLE
Question about the fixed intrinsic you used in the KITTIDataset class

### ISSUE THREAD

**Issue by wuyujack** [nianticlabs/monodepth2#43]
Hi,

I notice that someone has asked about the [intrinsic matrix when we change to a new dataset](https://github.com/nianticlabs/monodepth2/issues/6) and I am now trying to modify the code to train on my own dataset. I notice that in Monocular setting, in the class `KITTIDataset(MonoDataset)` you fixed the intrinsic matrix K as:

> self.K = np.array([[0.58, 0, 0.5, 0],
                           [0, 1.92, 0.5, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)
self.full_res_shape = (1242, 375)

Then I look at the `devkit_kitti_rawdata` folder provided from the [official website of Kitti dataset ](http://www.cvlibs.net/datasets/kitti/raw_data.php?type=city) and inside there is a readme about the camera parameter related to four cameras. Since in the paper you use color input, therefore, I supposed that in the monocular training the image should come from camera 2 or 3 which obtain left and right color image sequence. Then the K_02 and K_03 provided in the readme which is the calibration matrix of camera 2 or 3 before rectification is:

> K_02: 9.597910e+02 0.000000e+00 6.960217e+02 0.000000e+00 9.569251e+02 2.241806e+02 0.000000e+00 0.000000e+00 1.000000e+00

> K_03: 9.037596e+02 0.000000e+00 6.957519e+02 0.000000e+00 9.019653e+02 2.242509e+02 0.000000e+00 0.000000e+00 1.000000e+00

And I try to recover these matrices from the K you fixed in the code by rescaling them using the image_height = 1242 and image_width=375 and perform the multiplication 

> K[0,:] *= image_width
K[1,:] *= image_height

 but they seem not to match with the raw data K matrix.

Did I do something wrong or misunderstand something?

**Comment by mdfirman** [comment]
@mrharicot will be able to correct me if I'm wrong here, but I think the KITTI intrinsics you should be looking at are the *post*-rectification matrices. These are `P_rect_02` and `P_rect_03` in `calib_cam_to_cam.txt`. The maths using these matricies should work out:

```
P_rect_03: 7.215377e+02 0.000000e+00 6.095593e+02 -3.395242e+02 0.000000e+00 7.215377e+02 1.728540e+02 2.199936e+00 0.000000e+00 0.000000e+00 1.000000e+00 2.729905e-03
```

Then for example looking at `f_x`:

`7.215377e+02 / 1242 = 0.58094....`

...which is approximately what we have in `self.K`.

**Comment by wuyujack** [comment]
This makes me confusing. Based on what I know, the projection matrix should be composited by the camera intrinsic matrix and extrinsic matrix, but based on your reply it seems like you are using the projection matrix directly as the intrinsic matrix? Is it a default usage for the Kitti dataset? I am also verifying this since now I only obtain the camera intrinsic matrix based on the focal length and central points and I wonder whether I still need to get the extrinsic matrix which is composited by the translation vector and the rotation matrix.

**Comment by daniyar-niantic** [comment]
@wuyujack the post-rectification projection matrix has identity rotation matrix. So, projection matrix can be decomposed into intrinsics and extrinsics matrix, where the rotation component of the extrinsics matrix is identity.

In general, you need to do calibration to estimate intrinsics and extrinsics. Then you can rectify these matrices for the two views and compute projection matrices in a new space where the optical axes of the two cameras are parallel to each other (i.e. the rotation matrix is identity). This OpenCV function does the rectification:
https://docs.opencv.org/3.3.1/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6

**Comment by wuyujack** [comment]
> @wuyujack the post-rectification projection matrix has identity rotation matrix. So, projection matrix can be decomposed into intrinsics and extrinsics matrix, where the rotation component of the extrinsics matrix is identity.
> 
> In general, you need to do calibration to estimate intrinsics and extrinsics. Then you can rectify these matrices for the two views and compute projection matrices in a new space where the optical axes of the two cameras are parallel to each other (i.e. the rotation matrix is identity). This OpenCV function does the rectification:
> https://docs.opencv.org/3.3.1/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6

Thank you for your detailed reply and if the post-rectification projection matrix has identity rotation matrix then it makes sense to me right now. 

By the way, I only use **a single camera** to obtain own color image sequence, so it is no need to do rectify and I can just use my camera intrinsic matrix to replace the one in your code (`self.K`), is it correct?

**Comment by mrharicot** [comment]
All our code actually assumes a single intrinsics so you just need to change `self.K`
Just beware that the flip augmentation assumes the principal point to be in the centre of the image.
