### ISSUE TITLE
How to prepare custom dataset?

### ISSUE THREAD

**Issue by LiYanan2004** [nianticlabs/monodepth2#433]
I mean what should I do before the training process if I want to use my own dataset. How can I pair the original image to the depth map of it. 

For example, in the case like image classifier, we often use the folder name to pair with the images and send them to the networks. 

In this case, I want to use the camera and LiDAR sensor on my iphone to capture real-world images and real depth dot. But I have no idea how to pair these data. Any idea?

**Comment by LiYanan2004** [comment]
您的邮件我已收到，谢谢！QQ：1474700628

**Comment by daniyar-niantic** [comment]
Hi. This model is for self-supervised training of depth estimation networks. Since you plan to use lidar sensor, I suggest you to look into supervised depth prediction models.

The license of this repository does not allow commercial use.
