### ISSUE TITLE
Error in predicting background regions

### ISSUE THREAD

**Issue by hdacnw** [nianticlabs/monodepth2#436]
Thanks for the awesome work! I am trying to train the network using a custom dataset of monocular images with no GT. While the foreground regions are relatively accurately predicted, the textureless region at the back is predicted to be much closer than actual. Do you have any idea what might be the problem? 

Example training images, basically the camera is moving forward along a straight path:

![honoliishelf_p_35_img](https://user-images.githubusercontent.com/41716246/170900780-4cf69701-44ad-4834-a3ac-a1964a3d05bc.png)
![honoliishelf_p_38_img](https://user-images.githubusercontent.com/41716246/170900793-c4962120-0e02-4068-a171-2d3d57e3e088.png)

Example result:
![Screenshot 2022-05-08 185846](https://user-images.githubusercontent.com/41716246/170900923-6b8cdf3b-8562-412c-93c8-d7012a56afed.png)

Also I noticed that the initial loss is really small, similar to https://github.com/nianticlabs/monodepth2/issues/369
![image](https://user-images.githubusercontent.com/41716246/170901073-3b2fde19-7607-449f-ad79-a3f3ae19d744.png)

Help is really appreciated. Thank you so much!

**Comment by daniyar-niantic** [comment]
Hi.
Cool dataset. The depth of textureless is a difficult problem to resolve, as there is no way to triangulate any of the background pixels. You can see the same effect on sky pixels when training on KITTI dataset.

I'm afraid there is no way to deal with this problem, unless you can train a segmentation network to detect "background" and set its depth to infinity.
