### ISSUE TITLE
monodepth2 to onnx and TensorRT deployment

### ISSUE THREAD

**Issue by FangJingYunner** [nianticlabs/monodepth2#437]
l want to deployment monodepth2 on embedded system and got some problem .l want to transport model into onnx but it has mentioned that 
`Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.`
when opset_version is 11,12.
and the onnx infer result is very bad. so how to deploy it ?

**Comment by daniyar-niantic** [comment]
This repo is public mainly for reproducibility purposes. Making this network runnable on embedded devices is outside the scope of this repo.

Furthermore, the license does not permit usage of this codebase for commercial purposes.
