### ISSUE TITLE
From depth data prediction to distance data solution

### ISSUE THREAD

**Issue by juhonkang** [nianticlabs/monodepth2#438]
Hi,
I will detect objects with YOLO and after that, I will have a position of the object + depth data.
After that, how to turn it from depth data prediction to distance data? Do you have any solution?

Many thanks!

**Comment by daniyar-niantic** [comment]
Please see Readme: https://github.com/nianticlabs/monodepth2#%EF%B8%8F-prediction-for-a-single-image
