### ISSUE TITLE
Wondering if this is expected behavior

### ISSUE THREAD

**Issue by arminbazza** [nianticlabs/monodepth2#440]
Hey guys thanks for the excellent code!

While training on my own dataset (for monocular depth estimation) I ran into an issue where many of my training images would get removed during the training process, eventually resulting in a FileNotFoundError.

Originally I wrote my train_files.txt splits file like this:

```
path_to_seq1 1
path_to_seq1 2
path_to_seq1 3
path_to_seq1 4
path_to_seq1 5
path_to_seq1 6
path_to_seq1 7
...
path_to_seq2 1
path_to_seq2 2
path_to_seq2 3
...
```

However, when I changed it to this structure, it resolved the error:
```
path_to_seq1 1
path_to_seq1 4
path_to_seq1 7
...
path_to_seq2 1
path_to_seq2 4
...
```

So it seems that having overlap between the middle photos is not okay? Again, it would be great if somebody could comment on this.

Also, here is how I implemented some parts of my dataset class if it might help:
```python
def get_image_path(self, folder, frame_index, side):
    f_str = f"{frame_index}{self.image_ext}"
    image_path = os.path.join(self.data_path, folder, f_str)

   return image_path

def get_color(self, folder, frame_index, side, do_flip):
    image = self.loader(self.get_image_path(folder, frame_index, side))

    if do_flip:
        image = image.transpose(pil.FLIP_LEFT_RIGHT)

    return image

def get_depth(self, folder, frame_index, side, do_flip):
    return False

def check_depth(self):
    return False
```

**Comment by daniyar-niantic** [comment]
Hi @ArminBaz ,

The training code should not be deleting any files, so I'm not sure what your comment means.

**Comment by daniyar-niantic** [comment]
My guess is that `train_files.txt` contains a file that does not exist in your folder.
