### ISSUE TITLE
evaluation indicator

### ISSUE THREAD

**Issue by ysuwl** [nianticlabs/monodepth2#441]
Through the code of test_sample.py, we got the prediction is relative depth, but the labels in the KITTI dataset are the absolute depth, so how is the Abs Rel in the evaluation indicator obtained in the experiment calculated? Thank you for helping me with this question.

**Comment by daniyar-niantic** [comment]
Hi @ysuwl 
Your question is lacking details, are you talking about mono-trained model? stereo-trained model? KITTI lidar depths are not used during training. There is median scaling protocol for mono-trained models, see the paper for details.
