### ISSUE TITLE
Consistent scale uncertainty of mono-trained models

### ISSUE THREAD

**Issue by F-Pizo** [nianticlabs/monodepth2#444]
Hi and thanks for sharing your work in such a well-organized repository!

Out of curiosity, I ran evaluate_depth.py on several mono-trained models with median scaling disabled. As expected, the results are horrible. But interestingly, the metrics are all very similar in several models, so it seems that all models misestimated the scene scale by roughly the same amount.
I also observed this when evaluating with median scaling: the median scale factors for my three mono-trained models are 29.666, 30.908, 32.178 - very close to each other.

Could you explain to me why this may be? I somehow expected each mono-trained model to misestimate the scene scale by some more or less random amount and then stick to it - but not that several models do this by the same factor.

**Comment by daniyar-niantic** [comment]
Hey @F-Pizo 

Good question. I don't have definitive answer, but just a few hypothesis. The initialization of models is similar, so the "scale of depth" between scenes might be seeded at initialization time. The car speed is similar between sequences, so the translation amount between frames is similar causing the scaling factors to be similar.

I can recommend this paper that explores scale of mono-trained models: https://openaccess.thecvf.com/content/ICCV2021/html/Wang_Can_Scale-Consistent_Monocular_Depth_Be_Learned_in_a_Self-Supervised_Scale-Invariant_ICCV_2021_paper.html
