### ISSUE TITLE
How to test my .pth file

### ISSUE THREAD

**Issue by Shawn9257** [nianticlabs/monodepth2#445]
Thanks for your great work.
I am trying to train the model in a mono indoor video and I got my .pth file after training. But what should I do to test my training result? 
I got only one .pth file and I found that in the pre train model there are 4 .pth file. Should I run some file to get other .pth file? And When I try to run evaluate_depth.py, it can find a folder.

**Comment by daniyar-niantic** [comment]
There are not enough details in your question.

**Comment by Shawn9257** [comment]
Sorry. When I run the training :python ./monodepth2/train.py --model_name finetuned_mono --load_weights_folder ./monodepth2/models/mono_1024x320 --num_epochs 5 --num_workers 4 --batch_size 4

and I got a file： mono.pth and I change the name to depth.py.
but when I try to test my training result, with test_simple.py or evaluate_deth.py. When it loads the model it needs an encoder.pth file but I don't know how to get this file(encoder.pth)?. or can I load the model without this file?

**Comment by Shawn9257** [comment]
I found that that is because I change some of code and lead it only output one .pth file
