### ISSUE TITLE
How to use depth maps instead of point clouds

### ISSUE THREAD

**Issue by Shawn9257** [nianticlabs/monodepth2#446]
Thanks for your work. I am trying to use a dataset called MKV dataset(KinectDatasets) to train mono depth prediction. I am now trying to make the custom dataset as same as Kitti. I only have color images and depth images, not point clouds. Should I use some way to change depth images to point clouds?
![0_00000000](https://user-images.githubusercontent.com/34149594/181019181-7b6933da-f393-470f-b26c-4ab47da1fc06.png)

**Comment by daniyar-niantic** [comment]
Hi @Shawn9257 

From what I understand, you want to use Kinect depth data to train a network. I don't think this is the right repository for this task, as monodepth2 uses self-supervision (no depth data) and you need supervised monocular depth estimation.

I suggest to look into methods that train on NYU v2 Depth dataset.

**Comment by Shawn9257** [comment]
Thanks for your reply! That really helped me a lot. The reason why I try to do this is that when I try to use the pre-train model to fine-tune with the Kinect depth dataset(without depth maps). It gets a bad result. The model does not seem to converge, and the depth prediction, which could be partially effective, is worse after training. Do you have any suggestions?
