### ISSUE TITLE
How to train on custom dataset

### ISSUE THREAD

**Issue by mengpengfei** [nianticlabs/monodepth2#448]
I had read your paper about “monodepth2”. I also had read your code about “monodepth2”. I wondered about how to train on custom dataset.
 I have obtained the pose relative to the horizontal plane of each frame. These frames are all continuous. If I train monodepth2 on my dataset, How should I modify the open source code.

I had implements the dataloader for my custom data. It works well. But I would like to use  my custom pose data. Can you tell me how to use it.

**Comment by cswwp** [comment]
> I had read your paper about “monodepth2”. I also had read your code about “monodepth2”. I wondered about how to train on custom dataset. I have obtained the pose relative to the horizontal plane of each frame. These frames are all continuous. If I train monodepth2 on my dataset, How should I modify the open source code.
> 
> I had implements the dataloader for my custom data. It works well. But I would like to use my custom pose data. Can you tell me how to use it.

Hi, i'm trying to retrain monodepth2 with kitty dataset, but i can't download kitty dataset with " wget -i splits/kitti_archives_to_download.txt -P kitti_data/", it seems net issue in china, how you solve this problem? thank you

**Comment by 9796l** [comment]
> 

you can use other method.

**Comment by 9796l** [comment]
> 

Hello,i am the same with you .Did you solve you problem?

**Comment by ckj-handsome** [comment]
> I had read your paper about “monodepth2”. I also had read your code about “monodepth2”. I wondered about how to train on custom dataset. I have obtained the pose relative to the horizontal plane of each frame. These frames are all continuous. If I train monodepth2 on my dataset, How should I modify the open source code.
> 
> I had implements the dataloader for my custom data. It works well. But I would like to use my custom pose data. Can you tell me how to use it.

**Comment by daniyar-niantic** [comment]
Hi @mengpengfei ,

Sorry, helping with your custom dataset is outside the scope of this repo. You should be able to work out the format for camera poses if you check kitti dataset and kitti dataloder.
