### ISSUE TITLE
Why have the model learn disparity instead of depth directly?

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#45]
I noticed that during evaluation, you have to compute a ratio to correct for a scaling factor when computing the errors. Specifically in evaluate_depth.py,

```
if not opt.disable_median_scaling:
            ratio = np.median(gt_depth) / np.median(pred_depth)
            ratios.append(ratio)
            pred_depth *= ratio
```

If you need the ground truth to properly inference, then what is the point of this model? What's the point of inferencing if you need ground truth? Why not just have the depth net predict depth directly instead of predict disparity?

I would expect the depth to be off by a scaling factor and maybe even an offset if you tried inferencing with a camera with different intrinsics than the camera the model was trained with, but if the model was properly learning the depth, and you are evaluating on kitti, the same dataset you trained with, why would you need to adjust by this scaling factor? 

From what I can tell, this is due to how you are converting between disparity and depth. depth = 1 / disp. You don't know the scaling factor, so you just hand-wave it away and call it one. 

Normally, to convert between depth and disparity, you need the focal length and the baseline distance between the two cameras as explained by opencv here: https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_calib3d/py_depthmap/py_depthmap.html

But this model assumes the two cameras are in a binocular setting. This is a monocular setting, and the pose between two frames almost never represents a binocular setting with identity rotation matrix and zero translation in y and z directions. So what does disparity even mean in this model??? Is it still just the difference in pixels of two correspondence points, except now the distance can be in both x and y? 

I've been trying to think of how to properly compute depth from disparity in this model. But it's not as simple as computing the distance between the two cameras because they are not binocular. I suppose you'd have to apply rectification so they are co-planar? But even then, that approach requires two images to properly compute disparity/depth. And the depth net always only takes in one image.

The conclusion I've arrived to is that it'd be better to have the depth net directly predict depth instead of predicting disparity. And then the model would properly learn scale? To me, it doesn't even make sense to talk about disparity in a monocular setting anyways. What is the disparity even relative to? 

But something tells me that there is a reason why everyone who is doing this unsupervised approach is directly predicting disparity instead of depth. I am worried that if the model tries to learn depth directly, then it may focus too much on points that are far away during the loss optimization because it will be more likely to get larger errors for points that are far away than points that are close up, and then it won't really learn proper depth for objects that are up close, which are the points we actually care about. How far away the sky is normally isn't very important.

Sorry that this is so long. I wanted to make it very clear where I am coming from. Thank you.

**Comment by mrharicot** [comment]
Hi,

> From what I can tell, this is due to how you are converting between disparity and depth.

Predicting inverse depth (essentially scaled disparity) or depth is irrelevant here.
We predict inverse depth, which is not _metric inverse depth_, meaning we have an unknown scaling factor between the units predicted by the network and meters.
The reason stems from the fundamental ambiguity when doing multiview stereo without a known reference.
In the stereo case the reference is the baseline between the two cameras, without a known baseline we cannot make any assumptions on the units and the reconstruction is "up to scale".
You can find more information about multiview geometry in the following books:
https://www.robots.ox.ac.uk/~vgg/hzbook/
http://szeliski.org/Book/
http://www.computervisionmodels.com/

**Comment by mdfirman** [comment]
> If you need the ground truth to properly inference, then what is the point of this model? 

We use a single scaling factor from the ground truth because of scale ambiguity – see @mrharicot 's response. This way of evaluating was not invented by us, see Zhou et al. for the reasoning behind this evaluation method:

![image](https://user-images.githubusercontent.com/6114258/61461995-c7304380-a969-11e9-95f1-ce446d57423f.png)

>  I am worried that if the model tries to learn depth directly, then it may focus too much on points that are far away during the loss optimization

This would be my assumption too.

**Comment by aj96** [comment]
@mdfirman @mrharicot Thank you for your response. I still don't quite understand what disparity means in the monocular context, but I suppose that doesn't matter. So there is no clear way to get this scaling factor? I tried plotting the ratios, but they were not very consistent.

Also, in evaluate_depth.py, you pass the predicted disparity through your `disp_to_depth` function, and then do 1 / disp, and use that as your predicted depth. Why do you take the inverse twice? Doesn't that result in disparity, not depth? I suppose it doesn't matter because your result is still off by a scaling factor? Just that your scaling factor is different now?
