### ISSUE TITLE
The result is very bad on lane line

### ISSUE THREAD

**Issue by mengpengfei** [nianticlabs/monodepth2#451]
When I use depth to convert the pixel coordinates of the lane line into three-dimensional coordinates, the result is very bad.
Can you tell me what the problem is

**Comment by mengpengfei** [comment]
![abcd](https://user-images.githubusercontent.com/13211758/183880716-14358171-4e24-4693-9d43-d74b2984e611.png)
This is the result.

**Comment by mengpengfei** [comment]
![abcd1](https://user-images.githubusercontent.com/13211758/183880847-5d0a2e89-3079-4065-b2a9-eb1bfe16d56d.png)
This is the depth.

**Comment by mengpengfei** [comment]
![0000000000](https://user-images.githubusercontent.com/13211758/183880963-c1bd0bff-fb3a-4d9b-b703-9ca9680276aa.png)
This is the origin picture.

**Comment by mengpengfei** [comment]
![QQ截图20220810182048](https://user-images.githubusercontent.com/13211758/183881121-2011d8e0-cc44-4945-84d7-14863b019cab.png)
This is the result of superposition of the depth map and the identified lane line

**Comment by daniyar-niantic** [comment]
Are you sure you are using depth values and not disparity values?

Your 3D plot does not have labels, I don't know what different axis mean.

**Comment by mengpengfei** [comment]
Thanks very much for your reply. I am sure I am using depth values.
![image](https://user-images.githubusercontent.com/13211758/183885481-ac241ec6-d5ee-4140-8883-f0c5d2b0729a.png)
![image](https://user-images.githubusercontent.com/13211758/183885528-40fdaa48-a8b3-4c4e-a191-cbbbd3e07482.png)

**Comment by mengpengfei** [comment]
> 

Can you give me your email. I can give you the test code.

**Comment by daniyar-niantic** [comment]
Hi @mengpengfei ,

This seems like masking issue. Sorry, I can't really help you debug your code.
