### ISSUE TITLE
Huge depth difference between lane line and road

### ISSUE THREAD

**Issue by lmomoy** [nianticlabs/monodepth2#453]
Thanks for your wonderful job. When I trained my custom data, I found that there was a huge depth difference between lane line and road due to their texture difference. However, it seems that the trained model on KITTI does not show such result. Do you have some insights about this problem?

**Comment by daniyar-niantic** [comment]
Hi @lmomoy 

Are you training using mono video or stereo pairs? If It is mono video, then the data does not show lane lines from different perspectives. If it is stereo, then the calibration may be imperfect which can cause depth edges .
