### ISSUE TITLE
Pose Network 0.01 scale factor

### ISSUE THREAD

**Issue by nfrankisrg** [nianticlabs/monodepth2#455]
Hi,

I'm trying to understand the scale factor at the end of the pose network, but wasn't able to find any explanations in yours or  previous papers.

could you please elaborate on the impact of this scale factor and is it domain specific, if there is any paper/appendix that tested the results with/out or with any other factor or normalization method?

thanks!

**Comment by shan18** [comment]
Hi, I was also having this question. I recently saw this issue #260 where the authors have answered this question already.

**Comment by nfrankisrg** [comment]
> Hi, I was also having this question. I recently saw this issue #260 where the authors have answered this question already.

thanks! that really helped
