### ISSUE TITLE
ONNX model converter

### ISSUE THREAD

**Issue by GinkgoX** [nianticlabs/monodepth2#458]
Dear Author:
   Great work for mono depth estimation ! I have sucessfully convert your monodepth2 to onnx model, Can I share the blog without any commercial purposes ?

**Comment by 9796l** [comment]
Hello,i am confused about K intrinsic matrix,i need to use my dataset,so i want to change K.Would you like to talk with me ?Thank you very much.

**Comment by daniyar-niantic** [comment]
Hi, if you are sharing code from monodepth2, please see the LICENSE:
https://github.com/nianticlabs/monodepth2/blob/master/LICENSE

**Comment by Jaisme** [comment]
@GinkgoX 
Hi, could you please share the link to your blog? I'm also quite interested in model conversion!
