### ISSUE TITLE
2 questions about stereo training and monocular training.

### ISSUE THREAD

**Issue by dicaleon** [nianticlabs/monodepth2#461]
Thank you for your job! 
I have 2 questions.
1. About stereo training.
    I want to use a stereo camera to get my own training dataset for stereo image pairs.
    However, I want to predict evaluation images taken from other monocular camera.
    The metric depth will be incorrect? Is that possible?
3. About monocular training 
   I have known that it is difficult to train a monodepth2 model by using images with moving objects taken by a static monocular camera.
    But I think maybe I can train a monodepth2 model by using images with static objects taken by a moving monocular camera. It is a normal way. 
    After training, I use this model to predict the images with moving objects taken by a static monocular camera. I know it sounds ridiculous. But because during predict, we don't need to input some continuous frame images for prediction. So maybe this idea is possible?

**Comment by daniyar-niantic** [comment]
Hi
1. Yes, the depth might not be metric if intrinsics and FoV of the monocular camera does not match the intrinsics and FoV of the stereo cameras.
2. This is possible, and the results demonstrate how a network can predict depth of moving cars.
