### ISSUE TITLE
how to calculate the real world distance value from the camera to object

### ISSUE THREAD

**Issue by vigneshgig** [nianticlabs/monodepth2#47]
Hi , I want to know how to calculate the real world distance value from the camera to object. And I am using my own image so which mean pretrained model trained on different camera config. So how can I calibrate this pretrained model to my own camera input image.
Thanks for advance

**Comment by mrharicot** [comment]
Hi,
There isn't a good answer for this I am afraid.
The network was trained for a specific focal and image ratio. If we evaluate on a different ratio and focal we can't really predict what the network will do.
You can start by assuming that the network will predict the same scale as on KITTI which for our models trained with stereo supervision is 5.4

**Comment by vigneshgig** [comment]
Thanks for reply Can you tell what  do mean that stereo supervision is 5.4 and also can you provide the camera configuration

**Comment by mdfirman** [comment]
Hi,

You can take a look here for how depth is computed from our predicted scaled disparity:
https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py

Roughly speaking, to compute real-world depth from the network prediction:

    output = depth_decoder(encoder(input_color))
    pred_disp, _ = disp_to_depth(output[("disp", 0)], opt.min_depth, opt.max_depth)
    pred_depth = 5.4 / pred_disp

**Comment by vigneshgig** [comment]
Thanks
