### ISSUE TITLE
While reading groundtruth depth-map, why is it required to divide by 256 after converting PIL.Image to np.array ?

### ISSUE THREAD

**Issue by compvision-developer** [nianticlabs/monodepth2#473]
I don't know if I'm stupid in asking this question. 

But, I'm unable to reason why in the [*** CODE ***](https://github.com/nianticlabs/monodepth2/issues/101#issuecomment-550055146)  written by [VictorCVision](https://github.com/VictorCVision), the np.array is divided by 256 to get the `depth_map`. 

Also, what is the unit of depth (is it meter ?) in case of these projected groundtruth PNG files. 
(Ex: KITTI_dataset/2011_09_26/2011_09_26_drive_0001_sync/proj_depth/groundtruth/image_02/0000000005.png)

@VictorCVision @mrharicot

**Comment by daniyar-niantic** [comment]
As mentioned in https://github.com/nianticlabs/monodepth2/issues/101#issuecomment-549660792 I suspect the depth map is saved as 16-bit grayscale "image". So, dividing by 256 would not rescale it to [0, 1] range. However, I'm not completely sure why the loaded values are divided by 256. I would suggest to check KITTI website.

**Comment by daniyar-niantic** [comment]
Hi @compvision-developer

The format used for projected groundtruth PNG files follows KITTI dataset documentation:
https://github.com/joseph-zhong/KITTI-devkit#dataset-description
