### ISSUE TITLE
How to get the Three-dimensional coordinates 

### ISSUE THREAD

**Issue by loneclown** [nianticlabs/monodepth2#48]
hello，
 how to get the Three-dimensional coordinates from the image_disp and image,because i want to know the distance between the object and the land

**Comment by mdfirman** [comment]
Hi, did you have a look at the BackprojectDepth class? This does exactly what you describe.
https://github.com/nianticlabs/monodepth2/issues/46

**Comment by loneclown** [comment]
Thanks a  lot, i find the BackprojectDepth class,but i can not compute the  diatance between the object(such as one point)  and ground ，can you give me more help,thank you.
