### ISSUE TITLE
BackprojectDepth

### ISSUE THREAD

**Issue by loneclown** [nianticlabs/monodepth2#49]
Thanks a lot, i find the BackprojectDepth class,but i still can not compute the diatance between the object(such as one point) and ground ，can you give me more help,thank you.

**Comment by mdfirman** [comment]
Computing the distance you describe is well outside the scope of the monodepth project, so we can't help you with this.

(As an aside: in general it is easiest for everyone if you respond to the original issue, rather than creating a new issue for each comment you make 😄 )

**Comment by loneclown** [comment]
Copy that,Thank you😄
