### ISSUE TITLE
Regarding the patent and license

### ISSUE THREAD

**Issue by anthonygofin** [nianticlabs/monodepth2#498]
Hi ! 

Does any implementation of the Monodepth2 method violate your license and patent?

I am asking because I've noticed a TensorFlow implementation of Monodepth2 is available on @FangGet 's GitHub (here : https://github.com/FangGet/tf-monodepth2). The implementation starts from an existing monocular depth model (https://github.com/tinghuiz/SfMLearner), with all the changes from Monodepth2 (losses, auto-masking strategy, model architecture) added. Note that only monocular training was implemented in this version; there is no implementation of stereo/stereo+mono training.

My questions are:

- Does your license and patent refer solely to the software on your GitHub, or do they also cover the entire method described in your paper (https://arxiv.org/abs/1806.01260)?
- This TensorFlow implementation is under an MIT license (which allows commercial use). Can it be sold regardless of your patent (patent number: 11991342)? 
- Suppose I implement Monodepth2 using TensorFlow and train it on a custom dataset I have recorded. Would I be violating your patent?

Thank you for your clarification.

**Comment by daniyar-niantic** [comment]
Hi @anthonygofin 

I'm not a lawyer, so my understanding maybe incorrect. However,
- The license is for the software and models in this github repo.
- The patent refers to the entire method (idea/invention). The implementation of the method (i.e. code) is separate from the method (i.e. patent). So, a reimplementation TF does NOT make the patent go away.

The code in this repo is shared for research purposes only. Reimplementing and training on custom dataset for research purposes would be "similar in spirit" to the current license. However, these clauses still need to apply:
https://github.com/nianticlabs/monodepth2/blob/master/LICENSE#L78-L85
