### ISSUE TITLE
small object depth estimation

### ISSUE THREAD

**Issue by swrdZWJ** [nianticlabs/monodepth2#50]
Hi, thanks a lot for this project and your help.And I am new to this stuff. I want to use the project   to get the depth estimation in my own picture. and my attention is to get small object depth estimation compared with the rest component in the picture.

here is an example and I want to get the taxi depth

the orginal picture is:
![img0000080](https://user-images.githubusercontent.com/35293184/61586647-1c5b9780-abac-11e9-8e2e-d742e01e5919.jpg)

the depth estimation picture after I use mono+stereo_640x192 model:
![img0000080_disp](https://user-images.githubusercontent.com/35293184/61586665-a9065580-abac-11e9-8253-be15e05470f0.jpeg)

how can I achieve it. If I train in my own picture dataset, can I get a better result?
Thanks you very much!

**Comment by daniyar-niantic** [comment]
The image that you showed is a bit different from KITTI dataset, so the metric depth for the objects in your image might not be as accurate as for test images in KITTI. Training from your own dataset will always produce better results. Lastly, keep in mind that this codebase license does not permit commercial use.
