### ISSUE TITLE
Endoscope 384*384 iamge size

### ISSUE THREAD

**Issue by YJonmo** [nianticlabs/monodepth2#53]
Hi there,

I am using the stereo endoscope with the resolution of 384* 384. 

I can see your models come with predefined resolution such as stereo_no_pt_640x192 for a 640*192 image size.

So how could I use this repo to train on my images? 

Thanks
Jacob

**Comment by mrharicot** [comment]
Hi,
You can still use pretrained models as an initialization but change the image size.
If this doesn't work well you can start from the imagenet pretraining.

**Comment by daniyar-niantic** [comment]
Hi @YJonmo ,

To train with your own dataset please check these closed issues: https://github.com/nianticlabs/monodepth2/issues/26
https://github.com/nianticlabs/monodepth2/issues/15
https://github.com/nianticlabs/monodepth2/issues/43
https://github.com/nianticlabs/monodepth2/issues/6

Thanks!
