### ISSUE TITLE
divergence in mono+stereo training

### ISSUE THREAD

**Issue by sconlyshootery** [nianticlabs/monodepth2#54]
Hi，
When I trained from scratches and used mono+stereo setting， I found the network divergence after 5 epoches, the accuracy dropped dramatically and unable to return to normal. Any clue with that? Do any settings I need to change?

**Comment by mdfirman** [comment]
Hello! Thanks for the report. 

Is this training on KITTI using the default settings? And is this problem repeatable, i.e. does it happen every time you try to train?

In general we found this system to be stable when training. I would recommend lowering the learning rate a little as a first try, but I suspect it might just be a case of a bad initialisation – try again and it might go away.

Thanks.
