### ISSUE TITLE
Disparity smoothness loss scaling

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#55]
According to [monodepthv1](https://arxiv.org/pdf/1609.03677.pdf)

![monodepth](https://user-images.githubusercontent.com/26373373/62387840-60ba4080-b579-11e9-8be6-76cc11ae9be9.png)

In monodepthv2 all disparities are upsampled to original resolution, thus we doesn't need to scale disparity smoothness in each scale like this:

https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L486

Is this a bug?

**Comment by mrharicot** [comment]
Hi,
This isn't a bug, the disparities are upsampled only in the `generate_images_pred` function:
https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L338
The smoothness is still computed on the multiscale disparity maps similarly to monodepth1
