### ISSUE TITLE
Left-right consistency

### ISSUE THREAD

**Issue by Yelen719** [nianticlabs/monodepth2#56]
Thanks a lot for the contribution!

The left-right consistency term proposed in monodepth1 is a very nice idea. Why didn't you use it in monodepth2?

**Comment by mrharicot** [comment]
Hi,
The monodepth1 LR consistency only works for the stereo case.
monodepth2 would require a more general cycle consistency (temporal + stereo).
However any kind of consistency tends to produce issues at depth boundaries if they are not handled appropriately and given that monodepth2 produces sharp boundaries the overall gain was not significant so we did not use it.
I hope this helps!

**Comment by Yelen719** [comment]
Thanks a lot. That was really helpful.
