### ISSUE TITLE
intrinsic parameter matrix usage throws an error

### ISSUE THREAD

**Issue by ixtiyoruz** [nianticlabs/monodepth2#57]
in layers.py #139
```

class BackprojectDepth(nn.Module):
    """Layer to transform a depth image into a point cloud
    """
    def __init__(self, batch_size, height, width):
        super(BackprojectDepth, self).__init__()

        self.batch_size = batch_size
        self.height = height
        self.width = width

        meshgrid = np.meshgrid(range(self.width), range(self.height), indexing='xy')
        self.id_coords = np.stack(meshgrid, axis=0).astype(np.float32)
        self.id_coords = nn.Parameter(torch.from_numpy(self.id_coords))

        self.ones = nn.Parameter(torch.ones(self.batch_size, 1, self.height * self.width))

        self.pix_coords = torch.unsqueeze(torch.stack(
            [self.id_coords[0].view(-1), self.id_coords[1].view(-1)], 0), 0)
        self.pix_coords = self.pix_coords.repeat(batch_size, 1, 1)
        self.pix_coords = nn.Parameter(torch.cat([self.pix_coords, self.ones], 1))

    def forward(self, depth, inv_K):
        **cam_points = torch.matmul(inv_K[:, :3, :3], self.pix_coords)**
        cam_points = depth.view(self.batch_size, 1, -1) * cam_points.cuda()
        cam_points = torch.cat([cam_points, self.ones.cuda()], 1)

        return cam_points
```

when i run the code it throws an error : 
```
    cam_points = torch.matmul(inv_K[:, :3, :3], self.pix_coords)
IndexError: too many indices for tensor of dimension 2

```

if i run like `cam_points = torch.matmul(inv_K[:3, :3], self.pix_coords)` ,  it is working and returning 4 x w *h format matrix, can you please help me how to use it to calculate distance ?

**Comment by ixtiyoruz** [comment]
for depth calculation i used this : 
`_, depth = disp_to_depth(disp, 0.1, 100.0)`
is this ok ?

**Comment by daniyar-niantic** [comment]
I think your data pre-processing is wrong, your `inv_K` should be (batch_size, N, N) where N is 3 or 4. Instead, you have a two-dimensional tensor of (N, N).

The depth calculation depends on `min_depth` and `max_depth` [options](https://github.com/nianticlabs/monodepth2/blob/master/options.py#L69) used during training. For pre-trained models it should be `min_depth=0.1` and `max_depth=100`, as in the snippet you posted.

**Comment by ixtiyoruz** [comment]
Thank you for the reply, I am still a little confused:
**first of all i did this as the sample:** 
```
input_image =cv2.resize(frame, (feed_width,feed_height))
input_image = transforms.ToTensor()(input_image).unsqueeze(0)

# PREDICTION
input_image = input_image.to(device)
features = encoder(input_image)
outputs = depth_decoder(features)
#print(feed_width, feed_height)
disp = outputs[("disp", 0)]
```
**here disp matrix shape is torch.Size([1, 1, 192, 640])**
`_, depth = disp_to_depth(disp, 0.1, 100.0)`


**This is the initialization  of class:**


projecting = BackprojectDepth(1, feed_width, feed_height)`
`
**let's say we have a camera intrinsics as:** 
```
K = np.array([[0.58,    0, 0.5,],
                          [   0, 1.92, 0.5,],
                          [   0,    0,   1,],], dtype=np.float32)
```
**then i did this :** 
```
K[0, :] *= feed_width
K[1, :] *= feed_height
inv_K = np.expand_dims(np.linalg.pinv(K),0)
```
depth = projecting(disp, torch.from_numpy(inv_K))
print('------------------',np.shape(depth))

**this is returning an array with size of :** 
------------------ torch.Size([1, 4, 122880])

**which is not possible to resize to the size of  192, 640.**

Can you please help me to understand this ?

**Comment by ixtiyoruz** [comment]
Thank you for the reply, unfortunately, it is still confusing .
my code is follows: 
```

ret, frame = cap.read()
detections = darknet_video.detect_from_image(frame)
input_image =cv2.resize(frame, (feed_width,feed_height))
input_image = transforms.ToTensor()(input_image).unsqueeze(0)

# PREDICTION
input_image = input_image.to(device)
features = encoder(input_image)
outputs = depth_decoder(features)

disp = outputs[("disp", 0)]
source_scale = 0
_, depth = disp_to_depth(disp, 0.1, 100.0)
projecting = BackprojectDepth(1, feed_width, feed_height)

# taking sample camera intrinsics 
K = np.array([[0.58,    0, 0.5,  0],
                [   0, 1.92, 0.5,  0],
                [   0,    0,   1,  1],
                [   0,    0,   0,  1]], dtype=np.float32)
K[0, :] *= feed_width
K[1, :] *= feed_height
inv_K = np.expand_dims(np.linalg.pinv(K), 0) # to make it like batch_size x 4 x 4
cam_points = projecting(depth, torch.from_numpy(inv_K)) # taking cam points 
T= [6.030222e-02, -1.293125e-03, 5.900421e-03, 1] # i am taking it as an example
project_3d = Project3D(1, feed_width, feed_height) # taking 3d points 
K = np.expand_dims(K,0)
T = np.expand_dims(np.array(T, np.float32), 0)
pix_coords = project_3d(cam_points, torch.from_numpy(K), torch.from_numpy(np.transpose(T)))

```
and it throws an error : 
```
 cam_points = torch.matmul(P, points.to(torch.device("cpu")))
RuntimeError: invalid argument 2: wrong matrix size, batch1: 3x1, batch2: 4x122880 at c:\programdata\miniconda3\conda-bld\pytorch_1533094653504\work\aten\src\th\generic/THTensorMath.cpp:2312
```

**Comment by daniyar-niantic** [comment]
First of all, you are getting a different error now, the code now fails in `Project3D`. And the reason again, is the wrong size for matrices, in this case your `T` matrix is wrong. It needs to be batch_size x 4 x 4 matrix, and not an arbitrary matrix, but the relative pose between your stereo pairs. You can learn more about the 3D geometry by reading [OpenCV tutorial](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_table_of_contents_calib3d/py_table_of_contents_calib3d.html) and `Models for geometry` part of [Computer Vision Models book](http://web4.cs.ucl.ac.uk/staff/s.prince/book/book.pdf) or [Multiple-view Geometry in Computer Vision textbook](https://www.robots.ox.ac.uk/~vgg/hzbook/).

**Comment by daniyar-niantic** [comment]
Overall, I'm not sure what are you trying to do with your snippet? Do you just want to get a depth map? If so, you should check the [readme](https://github.com/nianticlabs/monodepth2#%EF%B8%8F-prediction-for-a-single-image).

**Comment by ixtiyoruz** [comment]
Thank you for the reply, here I just wanted to estimate the distance between the given object and camera. 

![image](https://user-images.githubusercontent.com/24115387/62841558-9e8b3780-bce4-11e9-99ad-bcaa07800551.png)

        ```
    last_time = time.time()
            ret, frame = cap.read()
            detections = darknet_video.detect_from_image(frame)
            
            original_height, original_width , _ = np.shape(frame)
            detections = darknet_video.resize_detections(detections, original_height, original_width)
            input_image =cv2.resize(frame, (feed_width,feed_height))
            input_image = transforms.ToTensor()(input_image).unsqueeze(0)

            # PREDICTION
            input_image = input_image.to(device)
            features = encoder(input_image)
            outputs = depth_decoder(features)
            
            disp = outputs[("disp", 0)]
            pred_disp, _ = disp_to_depth(disp, 0.1, 100.0)
            pred_disp = torch.nn.functional.interpolate(
                pred_disp, [original_height, original_width], mode="bilinear", align_corners=False)
            #print(np.shape(pred_disp))
            pred_disp = pred_disp.cpu().numpy()
            #print(np.shape(disp_resized))
            depth = STEREO_SCALE_FACTOR / pred_disp[0][0]
            MIN_DEPTH = 1e-3
            MAX_DEPTH = 80
            depth[depth < MIN_DEPTH] = MIN_DEPTH
            depth[depth > MAX_DEPTH] = MAX_DEPTH
```
![image](https://user-images.githubusercontent.com/24115387/62842070-085a1000-bcea-11e9-8909-198c6fe9ca02.png)

As you can see, the results are wrong. Any help would be appreciated?

**Comment by daniyar-niantic** [comment]
After you do prediction you just need to convert the network output to depth like this:
```
disp = outputs[("disp", 0)]
_, depth = disp_to_depth(disp, 0.1, 100.0)
```
