### ISSUE TITLE
Question about unit of training dense map

### ISSUE THREAD

**Issue by 111772** [nianticlabs/monodepth2#59]
Hello! Cause i don't know the work of generate_dense_map function, so i have no idea what is the unit of training dense map function , and if i want to convert the output picture's unit to meter , how can i do?
Thanks you very much!!!!!

**Comment by mrharicot** [comment]
Hi,
In the monocular-trained models, the unit is unknown and the standard evaluation (introduced by Zhou CVPR17) is to scale each depthmap independently at test time using the ground truth, which isn't ideal.
If stereo data is used a training time we know the unit and we can scale the depthmaps:
https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L24

I hope this helps!
