### ISSUE TITLE
Question about eval,train MAX_DEPTH,MIN_DEPTH

### ISSUE THREAD

**Issue by Songminkee** [nianticlabs/monodepth2#60]
in options, min_depth and max_depth are set to 0.1 and 100 by default.

but in evaluate_depth.py, min_depth and max_depth are set to 1 e-3 and 80.

Why did this happen?

Are these models(mono_no_pt_640x192, stereo_no_pt_640x192, mono+stereo_no_pt_640x192) trained 0.1 to 100? or 1 e-1 to 80?

**Comment by daniyar-niantic** [comment]
The min and max depths specified during training are used to limit the range of network predictions. Regardless of what your predictions are, you can specify the minimum and maximum clipping depths for evaluation. Notice, that in `evaluate_depth.py` you have [`opt.min_depth`](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L116) and [`MIN_DEPTH`](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L211). The `min_depth` in options needs to be the same as during training, so it is 0.1. However, when you evaluate, the predicted depth values below `MIN_DEPTH=1e-1` are set to `MIN_DEPTH`. Similarly for `MAX_DEPTH`.

Hope this helps.
