### ISSUE TITLE
From disparities to depth

### ISSUE THREAD

**Issue by hzhen95** [nianticlabs/monodepth2#61]
Thanks for your impressive work,but there's some about the project that i cant understand.

What is the difference between the method to calculate the depth from disparity 
I found that at the monodepth github in the issue part, it is mentioned that the depth from disparitiy is computed by depth = 0.54 * 721 / (1242 * pred_disp) which 0.54 is the baseline 721 is the focal length and 1241 is the width of kitti dataset

But for monodepth2 the depth is calculated with the function in disp_to_depth function in layer.py. Which for my understanding its map the result which is 0-1 from sigmoid into min-depth to max_depth then inverse it because of inverse depth.

Why is the method so much different?

**Comment by mrharicot** [comment]
Hi,
monodepth2 uses inverse depth, which in the stereo case is proportional to disparity.
Disparity is essentially a horizontal displacement, but in the monocular case the pixels move not only horizontally but also vertically, which is why we use inverse depth.

I hope this helps!

**Comment by yizhou-wang** [comment]
Hi,
I inferred some depthmaps for some images using mono+stereo model but it seems that the results are not absolute depth. How can I get absolute depth from the resulting disparity maps? If we are training monodepth2 on our own dataset, how can we get the scale after training? 
Thank you!

**Comment by poornimajd** [comment]
Hey @yizhou-wang , were you able to get the absolute depth?

**Comment by rishith2** [comment]
Did anyone get how to calculate the absolute depth from the depth tensor values? I do not think the depth tensor has the absolute values. Does it need any calibration to get the absolute value? How is it done?
