### ISSUE TITLE
Do this operation make image coordinates learnable?

### ISSUE THREAD

**Issue by sconlyshootery** [nianticlabs/monodepth2#62]
https://github.com/nianticlabs/monodepth2/blob/1cc8b81b6ca46fc6878de92ff126c7d2d94f5f89/layers.py#L153
In my opinion, image coordinates for each pixel have to be fixed, so network only focuses on optimizing depth and ego-motion.
And I am not sure whether 'torch.nn.Parameter()' will turn a fixed tensor to be learnable.
Could help me in understanding this operation?

**Comment by mrharicot** [comment]
Hi,
Indeed this tensor doesn't need (and probably shouldn't) be learnable.
I can only assume that it was a typo.
A parameter will only be optimized (and thus modified) if it is added to the optimizer like here:
https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/trainer.py#L88
https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/trainer.py#L99

**Comment by daniyar-niantic** [comment]
Indeed, it should not be optimized. And since it is not in `self.parameters_to_train`, it is not being optimized during training. Thanks for flagging this!
