### ISSUE TITLE
Smoothness with depth

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#63]
Out of curiosity, why do you calculate smoothness loss with disparity rather than with depth? 

https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/trainer.py#L484

Can we use depth for smoothness loss?

**Comment by mrharicot** [comment]
Hi,
The depth difference between two adjacent pixels can be very large (sky vs foreground) which would give a lot of weight to far away pixels.
You can use depth for the smoothness loss, but we never tried.
Let us know if you find it to help!
