### ISSUE TITLE
Depth Estimation using monodepth2

### ISSUE THREAD

**Issue by danish87** [nianticlabs/monodepth2#66]
Thank you Daniyar, Clément for providing wonderfull resource and help. I have multiple questions. I am trying to find some answers. 

This method provides good disparity (inverse disparity). I want to estimate the depth of objects in indoor settings for estimating the Collision-time. 
I have trained the model on the indoor dataset. The problem appears when the camera pose is changed. Seems like the network is unable to predict the depth when the camera and scene both get changed. 

While I am trying to find the scale factor for distance estimation in every frame (in meters). How this method can help me in finding the metric distance to an object?

Even if I try to find the scale, will that scale be fixed for conversion from disparity to metric depth in every frame?

Disparity should be fixed when we change the pose/position of the camera or should change?

The relative disparity outputted by the model has to be scaled by the original image size, which means the rectified image size?

What is the difference between scaled_disp and output disparity? It seems both are the same.

Thanks

**Comment by cab1211** [comment]
Dose the network work on the scene of static camera but moving object?

**Comment by mrharicot** [comment]
No, this is actually the worst case scenario for all single frame depth methods trained on monocular sequences.

**Comment by cab1211** [comment]
thanks.
our scenario is stereo, but our camera is static and there are motion object in the scenario. dose this work?

**Comment by mrharicot** [comment]
As long as the stereo pair is synchronized then it should work without problem.

**Comment by cab1211** [comment]
OK, thanks.

**Comment by fire17** [comment]
Hey can @danish87 or anyone send link of an indoor pretrained model please?
thanks

**Comment by Tonsty** [comment]
> No, this is actually the worst case scenario for all single frame depth methods trained on monocular sequences.

Does this network work on a moving camera when objects moves with different velocities?
