### ISSUE TITLE
identity_selection mask is not correctly computed?

### ISSUE THREAD

**Issue by HalleyJiang** [nianticlabs/monodepth2#68]
In trainer.py, line 478
outputs["identity_selection/{}".format(scale)] = (idxs > 1).float()
should be
outputs["identity_selection/{}".format(scale)] = (idxs > identity_reprojection_loss.shape[1]-1).float()

**Comment by daniyar-niantic** [comment]
I have a feeling that you are right, we will need @mdfirman 's comments here.

**Comment by mdfirman** [comment]
Thanks @HalleyJiang , yes I think you are right here. The `idxs > 1` works for the mono-training case only, but doesn't work correctly for stereo or mixed training. 

Fortunately this output is only used for visualisation. 

I will push a fix now.

**Comment by mdfirman** [comment]
Fixed with https://github.com/nianticlabs/monodepth2/commit/3e263c00c02cbdf918c21a8a56e22af24c16b07a

Thanks again
