### ISSUE TITLE
Disparity to depth / Height and pitch angle change 

### ISSUE THREAD

**Issue by mastermischa** [nianticlabs/monodepth2#69]
Hello UCL team, first of all I have to say this is a great job you've done. I have a question about testing: 

Is there any influence on the disparity when changing the height or pitch angle of the camera? I see a difference in the depth that doesn't correspond to the real depth when these parameters change. If yes, can this be compensated by training data with different heights and pitch angles or can I also change the scaling factor between disparity and depth for known parameters?

**Comment by daniyar-niantic** [comment]
Hey @mastermischa 

What you described seems like a training and test domain shift. It is always beneficial to have training data match the test data. In case they don't match, you might have some benefit of changing the scaling factor, but it is becomes just a heuristic without any guarantees.
