### ISSUE TITLE
in convert_to_HWC "size of input tensor and input format are different

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#7]
![image](https://user-images.githubusercontent.com/28101548/58532216-2904e480-8228-11e9-9ed3-e4777cf99c23.png)
Thanks for your great work.
But I get this error when I run train.py. It seems there's something wrong when write output log. Could you please help me fix it ?

**Comment by mrharicot** [comment]
Hi,
What command did you run, and did you modify the code in any way?

**Comment by sunnyHelen** [comment]
this is the command I run: python train.py --model_name mono_model --png
I didn't change the code

**Comment by mrharicot** [comment]
Which version of tensorboardX do you have installed?
We have only tested this code with v1.4

**Comment by sunnyHelen** [comment]
I found tensorboardX summary.py require the tensor to be CHW format.
![image](https://user-images.githubusercontent.com/28101548/58542061-2adaa200-8240-11e9-83e8-d4e1405675f1.png)
so I change the tensor format before logging. Seems it works.
![image](https://user-images.githubusercontent.com/28101548/58542120-4f367e80-8240-11e9-8c6b-dab9cb7b0ac5.png)

**Comment by mdfirman** [comment]
Thanks for the update! It looks like our code is not compatible with tensorboardX 1.7+ (and maybe has problems with some earlier versions too). As @mrharicot says, the code _does_ work with tensorboardX 1.4 (and 1.2).

I'm working on a fix now to see if we can easily support more versions of tensorboardX.

**Comment by mdfirman** [comment]
I've pushed [this fix](https://github.com/nianticlabs/monodepth2/commit/43e0575bc029f15723fb67bb0ed12be64ca1fcc7) so that the logging should now be compatible with tensorboardX 1.2, 1.4 and 1.7. (The commit also fixes a problem which existed with logging predictive masks).

**Comment by sunnyHelen** [comment]
Sure, thank you for your comprehensive work.
