### ISSUE TITLE
Can I finetune the model with my own dataset without .bin?

### ISSUE THREAD

**Issue by CassieMai** [nianticlabs/monodepth2#71]
I just have color images in my dataset. Can I train the monodepth2 model on my dataset? Is it necessary to prepare .bin files to generate the ground truth density maps? Thank you!!

**Comment by mrharicot** [comment]
Yes you just need to create a new dataset inheriting from [MonoDataset](https://github.com/nianticlabs/monodepth2/blob/master/datasets/mono_dataset.py) and have the function `check_depth` return False

**Comment by CassieMai** [comment]
How can I train the monodepth2 using color images without stereo pairs?

**Comment by mrharicot** [comment]
What does your dataset look like? Is there sufficient motion between frames?
Did you set the intrinsic matrix correctly in the dataset?
It is difficult to help without more details I am afraid.

**Comment by CassieMai** [comment]
Thank you @mrharicot. My dataset is a sequence of images of trees, showing the scene from the left side of a tree row to the right side of that. The camera moves almost along a horizontal line. A small part of frames doesn't have sufficient motion. I haven't set the intrinsic matrix yet. I wonder what kind of dataset is suitable for training the monodepth2?

**Comment by mrharicot** [comment]
Could you share a few consecutive frames from your dataset so we can get a better sense if the data is suitable for monocular training?

**Comment by CassieMai** [comment]
Yes, thank you @mrharicot . The link is [https://drive.google.com/open?id=1PHsZXF9qKsLSvlbAKAHlLkk4gA47yVpO](url)

**Comment by mdfirman** [comment]
Hi @CassieMai, thanks for sharing some images!

Your dataset looks difficult to learn from, as the camera seems to move quite far between frames, the objects are quite close to the camera, and the camera motion is much less smooth and has less 'forward linear motion' than the KITTI training images our code is designed for. (On the plus side, the scene seems to be well textured!)

If you are able to capture your own dataset, I would recommend investing in a stereo camera to capture stereo pairs; this should make learning depth much easier.

If you want to use the monocular sequences you already have, you might be able to get _something_ to work with this code, but it feels like it would be a research project in itself.

**Comment by CassieMai** [comment]
Hi, @mdfirman, thank you. Yeah, my dataset is hard for training the monodepth2. But it doesn't matter. I am just curious about the performance of the monodepth2 on my dataset. Thank you for your answers. @mrharicot @mdfirman

**Comment by dongfangliu66** [comment]
@CassieMai I want to work on my own dataset too but I'm struggling to implement mine. Do you mind share your modification of the original code with me to help my case. Thank you in advance.

**Comment by CassieMai** [comment]
@dongfangliu66 

`class ORANGEDataset(MonoDataset):
    def __init__(self, *args, **kwargs):
        super(ORANGEDataset, self).__init__(*args, **kwargs)

        self.K = np.array([[0.58, 0, 0.5, 0],
                           [0, 1.92, 0.5, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]], dtype=np.float32)

        self.full_res_shape = (1242, 375)
        self.side_map = {"2": 2, "3": 3, "l": 2, "r": 3}

    def check_depth(self):
        line = self.filenames[0].split()
        scene_name = line[0]
        frame_index = line[1]

        velo_filename = os.path.join(
            self.data_path,
            scene_name,
            "velodyne_points/data/{}.bin".format(frame_index))
        return False

    def get_image_path(self, folder, frame_index, side):
        print('frame_index: ', frame_index)
        f_str = "{}{}".format(frame_index, self.img_ext)
        image_path = os.path.join(
            self.data_path, folder, f_str)
        return image_path

    def get_color(self, folder, frame_index, side, do_flip):
        color = self.loader(self.get_image_path(folder, frame_index, side))
        if do_flip:
            color = color.transpose(pil.FLIP_LEFT_RIGHT)

        return color`

**Comment by dongfangliu66** [comment]
@CassieMai Thanks for your help. Then how do you change the lines in trainer.py as the follows? 
        # data
        datasets_dict = {"kitti": datasets.KITTIRAWDataset,
                         "kitti_odom": datasets.KITTIOdomDataset}

**Comment by mdfirman** [comment]
Thank you both for your updates and interest. I'm going to close this issue now, but please feel free to continue the conversation here.

**Comment by manuelcasal** [comment]
Hello. How do you create the dataset and how dou you train the model? I am no able to do it. Thanks in advance.
