### ISSUE TITLE
why invert transformation matrix if frame id is negative

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#72]
I was wondering why you are inverting the camera-to-camera transformation matrix when the frame_id is negative. Isn't the output of the PoseCNN always predicting the euler angles and translation components relative to time step t, meaning it tells you how to transform camera points from time step t to some adjacent time step? If you invert it, aren't you then using the transformation matrix for going from t-1 -> t instead of going from t -> t-1?

I only ask because I am trying to replace the PoseCNN with the actual Pose from imu, and I believe I must be missing something.

Thank you.

**Comment by mrharicot** [comment]
Because the pose network only takes two frames we make its life easier and get it to only predict motion forward in time.
Which is why we need to invert the transform.
The network seems to struggle predicting one of the two modes otherwise.
