### ISSUE TITLE
Why fixed the intrinsic parameters? 

### ISSUE THREAD

**Issue by hualie** [nianticlabs/monodepth2#73]
Dear Monodepth2 authors,

It can be found that the KITTI images from different dates have different intrinsic parameters. Why you approximately fix them as 
[[0.58, 0, 0.5, 0],
[0, 1.92, 0.5, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]

Will the results be better if we use the exact intrinsic parameters？

**Comment by WANG-KX** [comment]
Actually I have tried using the intrinsic parameters from the KITTI dataset but did not observe any improvement in the accuracy. Confused about the result. Any different result is welcomed to be posted here.

**Comment by hualie** [comment]
I have also used the corresponding intrinsic parameters for the KITTI from different days. I also observed no significant improvement. Maybe there is no big difference between the exact intrinsic parameters and the approximated ones for the monocular unsupervised training.
