### ISSUE TITLE
How to get the gray depth map?

### ISSUE THREAD

**Issue by nowburn** [nianticlabs/monodepth2#76]
Hi, this is an impressive work, the result is so cool.
the result in your code is the colored depth map. 
When I use the script evaluate_depth.cpp of KITTI devkit to evaluate the metrices like 'rmse' and so on. the result is a little big, maybe wrong.
[1] If I want to use 'devkit' to evaluate,  how can I get the right gray map? should I convert the colored depth map to gray img directly and then evaluate ?

Thanks!

**Comment by barloccia** [comment]
I'm in! I have the same problem, my system requires .png 16-bit monochrome depth images. I'm not sure how convert the images.

**Comment by mdfirman** [comment]
Hi @nowburn , @barloccia , and thanks for your interest in this repo.

I have never created these png depth maps myself, but I presume you are referring to the format described at the bottom of [this readme](https://github.com/joseph-zhong/KITTI-devkit)? If so, then converting our colourised depth maps is definitely not going to work; ours encode disparity not depth, and we use a colourmap designed for visualisation not assesment.

We have [some code](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L154) which is designed to create `.pngs` for kitti evaluation. Currently this section of code is only run when the benchmark split is used. You will need to modify `evaluate_depth.py` if you want to save `.png`s for other splits.

Let us know how you get on!

**Comment by nowburn** [comment]
@mdfirman , Thanks for your information.
[1] I update the code in 'test_simple.py' by referring the 'evaluate_depth.py '
![图片](https://user-images.githubusercontent.com/19162375/65372720-27af6a00-dca6-11e9-9be7-e7fd0ea1c62c.png)

[2] get the depth map:
![图片](https://user-images.githubusercontent.com/19162375/65372736-604f4380-dca6-11e9-830b-2e3669879b3f.png)

[3]the corresponding 'depth_annotated'
![图片](https://user-images.githubusercontent.com/19162375/65372765-bc19cc80-dca6-11e9-912b-01ced6d2447f.png)

[4] Is the generated depth right? and what's the meanning of colorbar number like 20000?
does it mean the corresponding point depth is 20000 mm ?
Thanks!

**Comment by mdfirman** [comment]
You should divide the number in the colourbar by 256 to get the depth in metres.

So 20000 / 256 = 78.125m

(See [this code snippet](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L154) – depths are multiplied by 256 before being saved)
