### ISSUE TITLE
Abount transformation_from_parameters function

### ISSUE THREAD

**Issue by hyBlue** [nianticlabs/monodepth2#79]
Hi, I want to ask the reason about multiplying R with T in transformation_from_parameter function. As I know, we just need to 'concat' those two matrix rather than multiplication, isn't it? Or in this case, did we assume the transformation output from pose network was before being applied by rotation?

**Comment by mdfirman** [comment]
[This](https://github.com/nianticlabs/monodepth2/blob/master/layers.py#L28) is the relevant function 

I beleive, you are correct in your second interpretation – the translation is assumed to be relative to the rotated camera frame, so needs the rotation to be applied to be relative to the origin.

@mrharicot  can you advise further?

**Comment by FangGet** [comment]
btw, your seems to predict two poses for two image input(current frame and next frame, seperate pose_encoder), and then abadon the second pose.

**Comment by daniyar-niantic** [comment]
The concatenation is valid for 3x3 rotation matrix and 1x3 translation vector. The `transformation_from_parameters ` function is multiplying 4x4 rotation matrix with 4x4 translation matrix.
