### ISSUE TITLE
Pre-trained models on Odom split?

### ISSUE THREAD

**Issue by Yuliang-Zou** [nianticlabs/monodepth2#8]
Seems that the released pre-trained models are trained on Eign split (for depth), I wonder if the Odom split models (for pose) are also available. Thanks!

**Comment by mdfirman** [comment]
Hi, thanks for asking for these. Here is the MS model:
https://storage.googleapis.com/niantic-lon-static/research/monodepth2/mono%2Bstereo_odom_640x192.zip

And this is the mono model:
https://storage.googleapis.com/niantic-lon-static/research/monodepth2/mono_odom_640x192.zip

I'll update the README soon too to add these links.

Thanks,
Michael

**Comment by mdfirman** [comment]
Updated README:
https://github.com/nianticlabs/monodepth2/commit/65eac3c04b26913fe9ee21b2b857f62b05502d3f

**Comment by dexter2406** [comment]
> Seems that the released pre-trained models are trained on Eign split (for depth), I wonder if the Odom split models (for pose) are also available. Thanks!

@Yuliang-Zou Hello, I have a silly question: why is all training data index is totally randomized (has no temporal order)? In my opinion, the self-supervision is based on temporal order (with inverse warping) right? I understand the depth network can be trained independently with Velodyne depth data. However, for the complete training pipeline, I think there's supposed to have at least a triplet, i.e. one target & two source images...

Thanks for your time, look forward to your opinion!
