### ISSUE TITLE
can't  finetuning a pretrained stereo model

### ISSUE THREAD

**Issue by kou5321** [nianticlabs/monodepth2#84]
hello, this is really a nice work! And I have completed on stereo training, it offers me weights.

The problem is that when I want to finetuning it on stereo model, which the instruction is 
python train.py --model_name finetuned_stereo --load_weights_folder ./stereo_model/models/weights_19

it tells me that
" FileNotFoundError: [Errno 2] No such file or directory: './stereo_model/models/weights_19/pose_encoder.pth'"

but there are no pose_encoder.pth exsiting.. 
is my instruction wrong?

**Comment by aj96** [comment]
For whatever reason, the models saved at that directory is missing the pose_encoder model. Maybe you should try re-training the model and checking to make sure the pose_encoder is being saved. It should be if you are running the code out-of-the-box.

**Comment by kou5321** [comment]
Thanks for answering. 
The fact is that when I finetuing monocular one, it works well cause it has the pose_encoder.pth. And all I get in weights_19 is adam.pth, depth.pth and encoder.pth. (you can also see it when you run "Prediction for a single image", it will download the pretrained model)

**Comment by aj96** [comment]
So you downloaded a pre-trained model from the authors? And it didn't include the pose_encder.pth? My point is that if you trained the model yourself, it should have the pose_encoder.pth saved. Is it saved in any of the previous epochs, like weights_1, weights_2, etc?

**Comment by kou5321** [comment]
well, that's exactly what I mean. and I have confirmed that the same thing happened in the former weights. Maybe I got something wrong..

**Comment by mdfirman** [comment]
@kou5321 , thanks for your interest in this project! If you are

**Comment by kou5321** [comment]
@mdfirman thanks a lot, it does work！
python train.py --model_name finetuned_stereo --load_weights_folder ./stereo_model/models/weights_19 --use_stereo --frame_ids 0 --models_to_load encoder depth
loading model from folder ./stereo_model/models/weights_19
Loading encoder weights...
Loading depth weights...
Loading Adam weights
Training model named:
   finetuned_stereo
Models and tensorboard events files are saved to:
   /home/kou/tmp
Training is using:
   cuda
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items

Training
epoch   0 | batch      0 | examples/s:  14.1 | loss: 0.10500 | time elapsed: 00h02m03s | time left: 00h00m00s

**Comment by mdfirman** [comment]
Great, thanks for getting back!
