### ISSUE TITLE
Why use axis-angle representation? 

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#85]
Why are you treating the three angles outputted by the PoseNet as axis angle representation? Can't you just treat the three angles as standard euler angles and compose them into RzRyRx for a standard rotation matrix?

**Comment by mrharicot** [comment]
There is no standard representation for 3d rotations.
Euler angles also suffer from the gimbal lock which is a degenerate case where one rotation has no effect anymore.
As we state in the paper we used the axis angle parametrization following the DDVO paper.

**Comment by manymuch** [comment]
I've tested the euler angle version of Monodepth2, the whole training and depth estimation are almost the same with original one. However, the trajectory from euler angle of PoseNet totally messed out. If anyone wants to have more conversation about this issue, please let me know.
