### ISSUE TITLE
Training on wild videos

### ISSUE THREAD

**Issue by WANG-KX** [nianticlabs/monodepth2#9]
Dear authors,

In your paper, you also showed training on videos from Youtube 'Wind Walk Travel Videos’, I am wondering how you deal with the intrinsic parameters (camera focal length, distortion, etc.).

Regards,

Kaixuan

**Comment by mdfirman** [comment]
Thanks for the question! @mrharicot is probably best placed to answer this.

**Comment by mrharicot** [comment]
Hi,
We were originally doing experiments with COLMAP, which gave us a focal length for some of the sequences. I then used an average of these and set the principal point to the center of the image.
For reference here is the intrinsics we used:
```python
self.K = np.array([[0.6,     0,     0.5,       0],
                   [0,   1.066,     0.5,       0],
                   [0,       0,       1,       0],
                   [0,       0,       0,       1]], dtype=np.float32)
```
I hope this helps!

**Comment by WANG-KX** [comment]
Thanks for your kind replay!

Actually, I have tested some method to find the intrinsic parameters of a wild monocular video. Basically, I followed a bundle adjustment method to solve the parameters by optimizing the reprojection of feature points. However, it can be proved that when the camera is moving without rotation (which is a common case in tour videos) the focal length is not observable. With small rotations, it also cannot be solved very well. 

On the other hand, since the rotation of adjacent frames is small, the focal length actually does not matter too much in the error term.

I do not know how to better solve the intrinsic parameters when trained on wild videos. If you have any other thoughts, please let me know.

Thanks again
Kaixuan

**Comment by mrharicot** [comment]
I would look at Google's recent paper where they also learn the camera calibration parameters
https://arxiv.org/abs/1904.04998

**Comment by WANG-KX** [comment]
Yes... Thanks for the sharing.
If we can solve it using multiview geometry, maybe it is better to solve it explicitly than learning. Thanks, maybe the community needs more research on this topic.

**Comment by kwea123** [comment]
@mrharicot Since you mention that paper, I would also like to ask you some questions.
They claim that K can be uniquely determined, but theoretically it isn't (and I found an counterexample..)! Basically their proof A2 is totally wrong. However they show that they can correctly learn the K, is it just a coincidence??

Next, I wonder your method (and theirs) can work also on distorted camera images without undistortion? Since for unknown camera parameters we cannot know the distortion either.

**Comment by hemangchawla** [comment]
Can the calibration parameters be set somehow during inference? For example, if the correct params for the sequence are computed using Colmap and then set during inference to improve the estimation?
