### ISSUE TITLE
where to find the improved ground truth

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#90]
Sorry to bother you~
I notice you also evaluate your models using the improved ground truth. Could you please tell me where to find it?
<img width="891" alt="image" src="https://user-images.githubusercontent.com/28101548/66908512-f0d73480-f056-11e9-8aed-b7eb15ba3d1d.png">

**Comment by mdfirman** [comment]
Hi @sunnyHelen ,

Maybe try the `Download annotated depth maps data set (14 GB)` link from this page:
http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction

Let us know how you get on.

**Comment by sunnyHelen** [comment]
Thank you for your help. I know how to use it now. Thanks a lot~
