### ISSUE TITLE
How important is image resolution? (Does everything really have to be multiple of 32?)

### ISSUE THREAD

**Issue by aj96** [nianticlabs/monodepth2#95]
I know that for the UNet skip connections to work properly, the input image resolution must be a multiple of 32, otherwise you'll have to do some resizing to get the concatenations to work properly, and doing this will lead to artifacts in the depth map. Because of this, we generally have to resize the images so that the resolutions are multiples of 32. Does this have a negative affect on the depth estimation results if the aspect ratio is changed too much from the original aspect ratio? Or does it not matter so long as we scale the intrinsics appropriately? I am just wondering if it is better to resize or center crop or maybe do a combination of both.

**Comment by mrharicot** [comment]
Hi,
As you stated, as long as the intrinsics are scaled appropriately it shouldn't matter.
If the input sizes aren't too small it is unlikely that resizing to a multiple of 32 would significantly affect the aspect ratio.
In the future, please use the github issues only for code-related problems.
