### ISSUE TITLE
Training monodepth2 on costume data

### ISSUE THREAD

**Issue by tammam1998** [nianticlabs/monodepth2#98]
Hello,

First, thanks for the great code. I was trying to train the model using a custom dataset of 2000 stereo images but got very unexpected results. For example, I got the following disparity
![1_disp](https://user-images.githubusercontent.com/33046178/68100239-f75a0e80-fe94-11e9-9235-93a5c90f2546.jpeg) 
for this image.
![1](https://user-images.githubusercontent.com/33046178/68100233-ee693d00-fe94-11e9-97e9-556814d305b2.jpg)
Is this expected to happen with this size of a dataset or am I doing something wrong? I would really appreciate any guidance on what might be going wrong in training.

Thanks,

**Comment by mdfirman** [comment]
Hi @tammam1998 ,

Thanks for your interest here. Assuming there are no bugs in your dataset loading, the things I would take a look at are the `min_depth`, `max_depth` parameters. Depending on your camera baseline you might benefit from adjusting these to enable the model to be able to learn. 

What is the baseline of your dataset? As a first port of call I might consider making `min_depth` higher than the default e.g. 1 or so.

Thanks
