### ISSUE TITLE
training on my dataset is trouble

### ISSUE THREAD

**Issue by yuliang1995** [nianticlabs/monodepth2#99]
Hi!I want training indoor dataset for monocular,but I have encountered some problems.

I tried this order：

python train.py --dataset indoor --data_path indoor_data --split indoor --model_name mdp --height 1280 --width 704

Training model named:
   mdp
Models and tensorboard events files are saved to:
   /home/cvr-lab/indoor
Training is using:
   cuda
frame_index:  7
frame_index:  50
frame_index:  18
frame_index:  24
frame_index:  176
.
.
.
frame_index:  175
frame_index:  25
frame_index:  177
frame_index:  42
frame_index:  207
Using split:
   indoor_txt
There are 467 training items and 361 validation items

frame_index:  206
frame_index:  208
Training
frame_index:  404
frame_index:  336
frame_index:  420
frame_index:  289
frame_index:  291
frame_index:  264
frame_index:  422
.
.
.
frame_index:  243
frame_index:  145
frame_index:  140
frame_index:  83
frame_index:  231
frame_index:  142
frame_index:  85
frame_index:  147
frame_index:  245
Traceback (most recent call last):
  File "train.py", line 18, in <module>
frame_index:  61
frame_index:  29
    trainer.train()
  File "/home/cvr-lab/monodepth2-master/trainer.py", line 191, in train
frame_index:  60
    self.run_epoch()
frame_index:  62
  File "/home/cvr-lab/monodepth2-master/trainer.py", line 203, in run_epoch
    for batch_idx, inputs in enumerate(self.train_loader):
  File "/home/cvr-lab/anaconda3/envs/yu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
frame_index:  28
frame_index:  30
    idx, batch = self._get_batch()
  File "/home/cvr-lab/anaconda3/envs/yu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/home/cvr-lab/anaconda3/envs/yu/lib/python3.6/queue.py", line 164, in get
frame_index:  111
frame_index:  220
frame_index:  342
frame_index:  350
frame_index:  25
frame_index:  110
frame_index:  352
frame_index:  123
    self.not_empty.wait()
  File "/home/cvr-lab/anaconda3/envs/yu/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
  File "/home/cvr-lab/anaconda3/envs/yu/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15615) is killed by signal: Killed. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
frame_index:  122

Have you ever encountered this kind of problem?

**Comment by mdfirman** [comment]
Hi @yuliang1995 ,

Did you follow the advice in the error and run with num_workers=0? This should help you narrow down the problem.

Thanks

**Comment by yuliang1995** [comment]
Thank you for your reply.I changed it after.I got an error :CUDA Error:out of memory
I changed batch_size=2,either.hat else do I need to change?
My GPU is GTX1080 8G  CUDA10

**Comment by mrharicot** [comment]
Hi @yuliang1995 ,
an input size of 1280x704 is very high, I would recommend resizing your images to a much lower resolution, say 320x176 as a first step.

**Comment by yuliang1995** [comment]
Thank you for answering me, it can already be trained.

**Comment by yuliang1995** [comment]
![000052](https://user-images.githubusercontent.com/39020380/70014593-2c51a200-15b6-11ea-8c33-93d6c571b7f0.jpg)
![000052_disp](https://user-images.githubusercontent.com/39020380/70014595-2c51a200-15b6-11ea-94f6-ca9464994681.jpeg)

I found that the effect was not obvious after training,is there any way to improve.
I use
K=[1.09, 0, 0.5,  0]
     [0, 1.94, 0.5, 0]
     [0 , 0 , 1 , 0]
     [0 , 0 , 0 , 1]
epoch=20,resnet=18 ,input=320*192
